### ISSUE TITLE
V5: it is not clear from the docs what need to be put into auth.config.ts or auth.ts with nextjs middleware

### ISSUE THREAD

**Issue by da1z** [nextauthjs/next-auth#10343]
### What is the improvement or update you wish to see?

Clear instructions what needs to be in auth.config.ts and auth.ts . nextjs middleware runs on edge and if add something that is not compatible(like email provider or db adapter) into auth.config.ts then everything breaks. I do not understand what need to be in auth.config.ts when half of my provider that not edge compatible are in auth.ts ? what is purpose of shared config when half is not there? what should be in shared cofig?

### Is there any context that might help us understand?

trying to get it work with next js middleware

### Does the docs page already exist? Please link to it.

https://authjs.dev/guides/upgrade-to-v5

**Comment by darrenpierre90** [comment]
@da1z I've had the same frustrating problem trying to work with this library for weeks. Here's what I've done :
1. Put everything that is compatible with the edge in auth.config.ts
2. Then in your `middleware.ts` you want to add the following code :
`import authConfig from "./auth.config"`
`import NextAuth from "next-auth"`
`export const { auth: middleware } = NextAuth(authConfig)`
3. In your `auth.ts` you want to add code that isn't edge compatible such as your email provider and db adapter and use the spread operator  ` ...authConfig,`

**Comment by chungweileong94** [comment]
Yeah, the documentation for NextAuth v5 isn't great at the moment, because the old documentation is still being migrated from https://next-auth.js.org/ to https://authjs.dev/, plus the v5 is still in active development (but quite stable for production based on my usage).

I would suggest you refer to this NextJS tutorial doc instead, it somehow explains to you why you need a sharable config for edge runtime. https://nextjs.org/learn/dashboard-app/adding-authentication

**Comment by JonnyBoy333** [comment]
Chiming in as I spent the better part of today troubleshooting edge related issues. The database I'm using is not edge compatible and it gets used in the `authorize` method of the CredentialsProvider. This means that I had to put the CredentialsProvider in the `auth.ts` file in the providers array, while the rest of my OAuth providers are in the `auth.config.ts` file (I spread these providers into the auth.ts provider array), also had to make sure callbacks were present in both configs since they apply to all providers.

This just feels like a very strange way to have to set this up (I'm not even %100 sure if this is the best way to do this). The documentation talks about database adapters in terms of edge compatibility but it doesn't really state that no edge incompatible functionality can exist at all in the `auth.config.ts` file, I can see others getting stuck on this as well. I wish there was a way to specify parts of the `auth.config.ts` file as not edge compatible so we don't have to maintain two different files.

**Comment by ndom91** [comment]
Hey folks we've just released some new docs, specifically for v5. 

https://authjs.dev/getting-started/adapters/prisma#edge-compatibility

In short, the workaround suggested to split up your config into `auth.ts` and `auth.config.ts` (for example), was only required as long as you're using a database which does nto support running on the edge. So if that's not you, then you don't need this workaround and the added complexity in the first place.

The most common use-case was folks using the prisma adapter, as they didn't support running in an edge runtime yet. However, they recently shipped support for this with a few specific database adapters (prisma database adapters, not auth.js database adapters :sweat_smile:).

Check out the link above for the `@auth/prisma-adapter` specific edge compatability info, including links to the prisma docs on edge compatability and supported databases, etc.

**Comment by ndom91** [comment]
In addition, there's this section on "Edge Compatibility" in the "migrate to v5" page: https://authjs.dev/getting-started/migrating-to-v5#edge-compatibility

**Comment by Olaw2jr** [comment]
> @da1z I've had the same frustrating problem trying to work with this library for weeks. Here's what I've done :
> 
> 1. Put everything that is compatible with the edge in auth.config.ts
> 2. Then in your `middleware.ts` you want to add the following code :
>    `import authConfig from "./auth.config"`
>    `import NextAuth from "next-auth"`
>    `export const { auth: middleware } = NextAuth(authConfig)`
> 3. In your `auth.ts` you want to add code that isn't edge compatible such as your email provider and db adapter and use the spread operator  ` ...authConfig,`
> 
> I hope this helps

is it necessary that the auth.config and auth be at the route of the application?

**Comment by ndom91** [comment]
> is it necessary that the auth.config and auth be at the route of the application?

It is not necessary for them to be at the root. You can put them wherever works for you 👍

**Comment by ndom91** [comment]
I'm going to close this issue as I think we've answered the original question. If anyone still has problems, feel free to open a new one
