### ISSUE TITLE
Sveltekit documentation using depreceted method

### ISSUE THREAD

**Issue by Set27** [nextauthjs/next-auth#10406]
### What is the improvement or update you wish to see?

route/+layout.server.ts
```typescript
import type { LayoutServerLoad } from './$types';

export const load: LayoutServerLoad = async (event) => {
  return {
    session: await event.locals.getSession()
  };
};
```

**getSession() is depreceted**

### Is there any context that might help us understand?

no

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/providers/credentials-tutorial

**Comment by Zofren** [comment]
It works with : 

```javascript
export async function load({ locals }) {
    return  { 
       session = await locals.getSession();    
    }
}
```

**Comment by AlbertMarashi** [comment]
Sorry, this fix I proposed doesn't seem to be actually fixing the issue. The `locals.auth()` returns a null session when logging in with credentials mode user

**Comment by ndom91** [comment]
@AlbertMarashi since yuo're using the credentials provider, unless you return something from the `authorize` method on the `CredentialsProvider()`, Auth.js won't know anything about your user

As an example, in the SvelteKit dev app in the repo we've got this setup for testing the credentials provider:

```ts
  providers = [
    Credentials({
      credentials: { password: { label: "Password", type: "password" } },
      async authorize(credentials) {
        if (credentials.password !== "password") return null
        return {
          name: "Fill Murray",
          email: "bill@fillmurray.com",
          image: "https://source.boringavatars.com/marble/120",
          id: "1",
        }
      },
    })
  ]
```

And this will return the following from `locals.auth()`:

```
{
  "user": {
    "name": "Fill Murray",
    "email": "bill@fillmurray.com",
    "image": "https://source.boringavatars.com/marble/120"
  },
  "expires": "2024-05-12T15:25:37.414Z"
}
```

![image](https://github.com/nextauthjs/next-auth/assets/7415984/c06a440e-5269-48b7-a795-d69036108f46)

**Comment by ndom91** [comment]
Closing this issue because the original issue has been fixed with the [new docs](https://authjs.dev) :pray: 

If anyone still has any probelms with SvelteKit setup, feel free to open a new issue
