### ISSUE TITLE
Verification token encryption/hashing to prevent email security issues

### ISSUE THREAD

**Issue by kripod** [nextauthjs/next-auth#1051]
**Summary of proposed feature**

Currently, verification tokens are sent by email in plaintext format, which could be traced and potentially be stolen by bad actors.

**Purpose of proposed feature**

Overcome the inherent security issues of email transmission.

**Detail about proposed feature**

When requesting a token to an email address, the server should send back a randomly generated key as a secure HTTP-only cookie. It should act like a password for the corresponding verification token. (The verification token could be as simple as a secure hash of the generated key. SHA-256 should be sufficient for the purpose as long as most cryptocurrencies are considered secure.)

When opening the sign in link received by email, the server should check for the presence of the previously server-generated key in the request’s cookies.

- If a key is found, then check if its hash computes to the server-stored verification token. Proceed as usual if the two values match, or redirect back to the `signIn` page and show an error detailing the mismatch otherwise.
- If no key is found, redirect back to the `signIn` page, showing an error which prompts the user to try again by opening the link from the same browser as it was requested from.

**Potential problems**

Previously stored verification tokens may not be compatible with the new ones. False positive error messages might be shown during a very short migration period – possibly a few minutes.

**Comment by kripod** [comment]
Not stale

**Comment by iaincollins** [comment]
Hi there,

* The single use tokens are already stored hashed on the server (using sha256).

  This is how tokens like these are normally stored - this is more secure than storing the hash on the client, because if read access to the database is compromised then you still can't sign in as other users because you won't know what the token is (even if you can read the salted hash).

* This is how sign in by "magic link" normally works with virtually every service that implements it.

  The specific server side hash and the duration of the hash are typically the only variables, but the solution is fundamentally the same across all providers. It is unusual that tokens are also client specific, except sometimes in the case of short tokens.

* It is fully configurable if you want different behaviour.

  With NextAuth.js you can actually configure the token generation in the provider and you can configure how and what is sent (e.g. email, SMS, etc), how long it is valid for, how it is stored / verified / expired using custom `createVerificationRequest` / `getVerificationRequest` / `deleteVerificationRequest` methods in the Database Adapter. You can every set a custom verification endpoint if you want to apply additional logic to the check.


We have no plans to introduce an additional client specific token to restrict the single use tokens to only functioning when used on the same device made to initiate the request at this time, though this is something we may consider as an option when we come to add support for more convenient shorter tokens to facilitate cross device sign in.

**Comment by iaincollins** [comment]
PS: Thank you for the submission! Please do feel free to open this again when we round to looking at short tokens!

If anyone has a link to the current open issue about short tokens (I'm not sure which one is canonical) would be good to link it back here for future reference, even if this isn't something we have capacity for right now.

**Comment by kripod** [comment]
@iaincollins thank you for your well-detailed answer. I understand that this isn’t mandatory but seemed like an inherent security issue depending on the transmission channel’s security (e.g. email or SMS).

I wouldn’t like to weaken the current system but add a potentional option called `e2eTokenEncryption` as an additional layer of security when the transmission channel is deemed to be insecure.
