### ISSUE TITLE
MissingSecret error during Next build since 5.0.0-beta.16

### ISSUE THREAD

**Issue by nphmuller** [nextauthjs/next-auth#10538]
### Environment

  System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 198.45 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.2.5 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    bun: 1.0.30 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 17.4
  npmPackages:
    next: 14.1.4 => 14.1.4
    next-auth: ^5.0.0-beta.16 => 5.0.0-beta.16
    react: ^18 => 18.2.0

### Reproduction URL

https://github.com/nphmuller/nextauth-secret-repro

### Describe the issue

This is a duplicate issue for https://github.com/nextauthjs/next-auth/issues/10432 and https://github.com/nextauthjs/next-auth/issues/10478 which, in my understanding, were closed incorrectly.

Since beta 16 AUTH_SECRET suddenly was required during the build, while it previously was not.

### How to reproduce

- `npx create-next-app@latest`
- `npm i next-auth@5.0.0-beta.16`
- Implement `auth.ts`, ` api/auth/[..nextauth]/route.ts` and `middleware.ts` [according to the docs](https://authjs.dev/getting-started/installation#configure) (very basic, no special config)
- Make sure NOT to configure AUTH_SECRET. Assume this var is only available after the app is deployed.
- Run `npx run build`.

### Expected behavior

In beta 15 the build succeeded.
In beta 16 the build fails with:

```
Collecting page data  .O: Missing secret, please set AUTH_SECRET or config.secret. Read more at https://errors.authjs.dev#missingsecret
 at /Users/nphmuller/Dev/nextauth-secret-repro/.next/server/app/api/auth/[...nextauth]/route.js:357:51531
 at iZ (/Users/nphmuller/Dev/nextauth-secret-repro/.next/server/app/api/auth/[...nextauth]/route.js:357:52127)
 at /Users/nphmuller/Dev/nextauth-secret-repro/.next/server/app/api/auth/[...nextauth]/route.js:357:56740
 at 6518 (/Users/nphmuller/Dev/nextauth-secret-repro/.next/server/app/api/auth/[...nextauth]/route.js:357:56884)
 at t (/Users/nphmuller/Dev/nextauth-secret-repro/.next/server/webpack-runtime.js:1:127)
 at r (/Users/nphmuller/Dev/nextauth-secret-repro/.next/server/app/api/auth/[...nextauth]/route.js:373:20451)
 at /Users/nphmuller/Dev/nextauth-secret-repro/.next/server/app/api/auth/[...nextauth]/route.js:373:20478
 at t.X (/Users/nphmuller/Dev/nextauth-secret-repro/.next/server/webpack-runtime.js:1:1191)
 at /Users/nphmuller/Dev/nextauth-secret-repro/.next/server/app/api/auth/[...nextauth]/route.js:373:20464
 at Object.<anonymous> (/Users/nphmuller/Dev/nextauth-secret-repro/.next/server/app/api/auth/[...nextauth]/route.js:373:20505) {
type: 'MissingSecret',
kind: 'error'

```

**Comment by nphmuller** [comment]
Sorry that it took a while to get a minimal repro going... 

I know of the workaround by setting the value during the build to a fake value, but is that the official solution? It might be a bit confusing, since there's quite a bit of discussion due to this change in beta 16 (see https://github.com/nextauthjs/next-auth/pull/10305 but also in the other issues linked).

**Comment by Theoblanc** [comment]
When deploying with Git CI/CD, I also encounter the same errors, and the web server fails to run.

I replaced AUTH_SECRET with NEXT_PUBLIC_AUTH_SECRET, which made it run. However, this is not a proper solution but a temporary workaround.

**Comment by hu-qi** [comment]
the same, but in version `5.0.0-beta.15`, it works.

**Comment by pranavmappoli** [comment]
Any fix is available for this ? , I have AUTH_SECRET in my env, still facing issue

**Comment by robliou** [comment]
> Any fix is available for this ? , I have AUTH_SECRET in my env, still facing issue

Same issue with me as well. After cloning the next-auth repository, and completing the .env file with my secrets, I get the same error even though AUTH-SECRET has been entered. 

I tried downgrading to ``5.0.0-beta.15`` and that error goes away, but a different one emerges.

**Comment by matthawk60** [comment]
using NEXT_PUBLIC_AUTH_SECRET is the only thing that worked for me other than hardcoding the secret.  I believe this is likely do to using the auth object in client contexts where AUTH_SECRET would not be available

**Comment by balazsorban44** [comment]
`NEXT_PUBLIC_AUTH_SECRET` is a horrible idea, please don't even suggest that. Those replies are marked as spam.

**Comment by balazsorban44** [comment]
Fix is incoming https://github.com/nextauthjs/next-auth/pull/10592

**Comment by matthawk60** [comment]
> `NEXT_PUBLIC_AUTH_SECRET` is a horrible idea, please don't even suggest that. Those replies are marked as spam.

Just to be clear, no one was suggesting to try this.  But if you don't need help with the issues I'll go somewhere else.  I was just trying to give you helpful data in my debug process, no need to accuse me of spam.

**Comment by itzjacki** [comment]
@matthawk60 it was probably marked as spam not because you seem like a spammer, but because the suggestion is dangerous. My (limited) understanding is that the whole point of having a server-side secret like that is that it lets you be more lenient with what you store in cilent browsers, since it can be encrypted with said secret. If you hand out the secret to the client (which becomes possible when following your suggestion), enctyped cookies suddenly become decryptable.

See https://next-auth.js.org/configuration/options#secret

**Comment by matthawk60** [comment]
> @matthawk60 it was probably marked as spam not because you seem like a spammer, but because the suggestion is dangerous. My (limited) understanding is that the whole point of having a server-side secret like that is that it lets you be more lenient with what you store in cilent browsers, since it can be encrypted with said secret. If you hand out the secret to the client (which becomes possible when following your suggestion), enctyped cookies suddenly become decryptable.
> 
> See https://next-auth.js.org/configuration/options#secret

I don't want to continue this but my point was that I was only trying to help debug the problem.  Obviously I was not suggesting that someone should use the NEXT_PUBLIC_AUTH_SECRET as a solution in production.  More to the point as this is Beta software so no one should really be using it in production anyway.  The point I was trying to make was, I am a busy developer who uses next-auth, I hit a but and I took time to try to help the maintainer locate and fix a bug.  Instead of being thanked, I was chastised and accused of being a spammer.  It's fine, as I said I don't have to contribute my time and I'm sorry I did.  I'm doing my best to find an alternative solution.

**Comment by matthawk60** [comment]
> @matthawk60 it was probably marked as spam not because you seem like a spammer, but because the suggestion is dangerous. My (limited) understanding is that the whole point of having a server-side secret like that is that it lets you be more lenient with what you store in cilent browsers, since it can be encrypted with said secret. If you hand out the secret to the client (which becomes possible when following your suggestion), enctyped cookies suddenly become decryptable.
> 
> See https://next-auth.js.org/configuration/options#secret

Obviously  I was not suggesting NEXT_PUBLIC_AUTH_SECRET  should be used in production.  Perhaps I should have added that disclaimer.  But by that thinking, no one should be using a beta release of software in the first place.  However, if you want to use the app router and next-auth that is currently our only option.
My testing indicated the Nextjs was removing the secret becuase it was being exposed to the client, which would be a major problem. My comment was meant to help find the problem.  While this issue has only been open for a few days, there are others which have been around since beta-16 was released. 
My intention was not to help users, I was commenting on an issue hoping to help debug the problem and fix the underlying issue with the software.

**Comment by itzjacki** [comment]
@matthawk60 

Okay, then I see where you're coming from. In the future I would still be careful about phrasing it in the way you did, because I would be willing to bet my savings that if the comment didn't get marked as spam (and therefore hidden by default) it would be tried by at least one confused developer trying to fix the error they're getting without taking the time to read up on the context around it (or what the `NEXT_PUBLIC_` prefix means. It's perfectly plausible to me that it would end up as production code in that scenario.

> Obviously I was not suggesting NEXT_PUBLIC_AUTH_SECRET should be used in production.

To someone new to next.js and nextauth I don't necessarily think it's obvious that you're not suggesting to use `NEXT_PUBLIC_` as a production fix.

**Comment by peppescg** [comment]
Hi folks I am continuing to have the same issue. Tried to use `5.0.0-beta.15` but I got a different error on session.
Could someone help me please 🙏 ?
```
Uncaught MissingSecret: Missing secret, please set AUTH_SECRET or config.secret.
```

with this provider configuration
```JSX
const providers = [
  KeycloakProvider({
    id: 'keycloak',
    clientId: process.env.AUTH_KEYCLOAK_ID,
    issuer: process.env.AUTH_KEYCLOAK_URL,
    clientSecret: process.env.AUTH_SECRET,
  }),
]
```

**Comment by matthawk60** [comment]
The fix isn't in  5.0.0-beta.15.  You will either have to wait for the next beta or do a patch.  I"m using pnpm to apply the patch, you can also use patch-package.  https://github.com/nextauthjs/next-auth/pull/10592 is what fixed it for me.

**Comment by peppescg** [comment]
> The fix isn't in 5.0.0-beta.15. You will either have to wait for the next beta or do a patch. I"m using pnpm to apply the patch, you can also use patch-package. #10592 is what fixed it for me.

hi @matthawk60 👋 
did you experimented that calling signout fn on a server action, raised an error ` Cookies can only be modified in a Server Action or Route Handler.`? this happens only after upgrading to the last `5.0.0-beta.17` 
Ho you are using the signout? My use case is that I want to match the 401 and in this case signout

**Comment by everspader** [comment]
I'm still experiencing this issue on version `5.0.0-beta.25`
I already tried:
* Setting `AUTH_SECRET` and `NEXTAUTH_SECRET` in the `.env` file.
* Setting `AUTH_SECRET` and `NEXTAUTH_SECRET` as environment variables in the shell session

The error persists. Only solution is to passe the secret explicitly to the `getToken`

**Comment by MihirModi1421** [comment]
> I'm still experiencing this issue on version `5.0.0-beta.25` when attempting to call:
> 
> const token = await getToken({ req });
> On my `middleware.ts` file.
> 
> I already tried:
> 
> * Setting `AUTH_SECRET` and `NEXTAUTH_SECRET` in the `.env` file.
> * Setting `AUTH_SECRET` and `NEXTAUTH_SECRET` as environment variables in the shell session
> 
> The error persists. Only solution is to passe the secret explicitly to the `getToken`

Hi, @everspader from that token how did you get JWT token object 
as i cannot decode that token
how did you tackle this

**Comment by jhoanborges** [comment]
solved doing this in middleware.ts

// middleware.ts
```
import { NextResponse } from 'next/server';
import { getToken } from 'next-auth/jwt';
import type { NextRequest } from 'next/server';
const secret = process.env.NEXTAUTH_SECRET
export default async function handler(req, res) {
    // Check if the user has a valid token
    const token = await getToken({ req, secret })
    console.log("JSON Web Token", token)

    // Define the URL of the login page
    const loginPage = new URL('/login', req.url);

    // If the user is not authenticated and is trying to access protected routes
    if (!token && req.nextUrl.pathname.startsWith('/admin')) {
        // Redirect to the login page
        return NextResponse.redirect(loginPage);
    }

    // Allow the request to proceed
    return NextResponse.next();
}

// Configure the matcher to apply middleware to specific routes
export const config = {
    matcher: ['/admin/:path*'],  // This is correct
};

```
