### ISSUE TITLE
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant

### ISSUE THREAD

**Issue by Set27** [nextauthjs/next-auth#10534]
### What is the improvement or update you wish to see?

https://warnings.authjs.dev#env-url-basepath-redundant 
invalid link

### Is there any context that might help us understand?

https://warnings.authjs.dev#env-url-basepath-redundant 
invalid link

**Comment by northcoder-repo** [comment]
More background in case it helps:

In my case, the warning was being generated because I was using the following environment variable in my next.js app

```
AUTH_URL=http://localhost:3000/api/auth
```

I see [here](https://authjs.dev/reference/core#basepath) that `/api/auth` is the default value, anyway.

When I removed the `AUTH_URL` env variable, I stopped getting the warning.

I see that there is an "errors" page here:

[https://authjs.dev/reference/core/errors](https://authjs.dev/reference/core/errors)

So, I assume there needs to be a similar documentation page - probably here (but this page does not currently exist):

[https://authjs.dev/reference/core/warnings](https://authjs.dev/reference/core/warnings)

I see there is a Markdown page here for some warnings, including the above warning:

[warnings.md](https://github.com/nextauthjs/next-auth/blob/3d5c3043ea07036db547b8be5444f22a5e2fa289/docs/docs/reference/warnings.md)

Maybe this page is not yet live?

---

For reference, here is what it says:

> Env URL and basePath redundant
> 
> AUTH_URL (or NEXTAUTH_URL) and authConfig.basePath are both declared. This is a configuration mistake - you should either remove the authConfig.basePath configuration, or remove the pathname of AUTH_URL (or NEXTAUTH_URL). Only one of them is needed.

**Comment by ndom91** [comment]
Thanks for pointing this out! We're missing a new copy of the pre-existing "warnings" page atm. We only have the extra "errors" page. I've brought it up to the team :pray:

**Comment by ndom91** [comment]
We're going to add back the `warnings` page so the printed URLs in the console for warnings (there's 5 total I think, including this `env-url-basePath-*` one) should work as expected again :+1:

**Comment by Set27** [comment]
@DanB-Web thank for information
