### ISSUE TITLE
Google One Tap

### ISSUE THREAD

**Issue by keslert** [nextauthjs/next-auth#1058]
Is it possible to use next-auth with [Google One Tap](https://developers.google.com/identity/one-tap/web/guides/get-google-api-clientid)?

**Comment by iaincollins** [comment]
I didn't know about this but its really interesting! Thanks for raising this.

**Comment by keslert** [comment]
Yep, I'm starting to see it used more and more around the web. And the stats I've seen around it show that it has a substantial improvement on signups.

**Comment by asdutoit** [comment]
also interested to see the best method of implementation is

**Comment by edustef** [comment]
I'm really curious as well how you would implement something like this with next-auth.

**Comment by arclogos132** [comment]
Anyone still waiting?

**Comment by balazsorban44** [comment]
I've just looked at this video https://youtu.be/qS4dY7syQwA and got some ideas how to integrate it into NextAuth.js

I cannot say I'll prioritize it, but I happily reopened the issue to track this.

If anyone wants to jump on it and try to implement, please do!

**Comment by asdutoit** [comment]
Hi Fabrizio,
I am definitely interested and would appreciate and assistance in this
regard.
Thanks!

**Comment by balazsorban44** [comment]
@ramiel please do!

**Comment by arclogos132** [comment]
@ramiel Please help us all!

**Comment by ramiel** [comment]
👍  I'm going to wrap up everything in the next few days.

**Comment by balazsorban44** [comment]
I got a sneak-peak of @ramiel's post, and it's super nice! 👀 I think we can add support for it and have it integrated (partially) into the core. There will be a small code snippet to copy for the front-end part, but not that bad!

**Comment by asdutoit** [comment]
Awesome thanks so much

**Comment by ramiel** [comment]
And finaly here the tutorial: https://www.ramielcreations.com/next-auth-google-one-tap

Many thanks to @balazsorban44 for help and suggestions

**Comment by asdutoit** [comment]
Fantastic, thanks @ramiel & @balazsorban44, will try it out later this evening.   Appreciate your efforts!

**Comment by balazsorban44** [comment]
https://twitter.com/nextauthjs/status/1444604464837632001

**Comment by balazsorban44** [comment]
@keslert it is now! :slightly_smiling_face: I will close this for now, but we might revisit it in the future if we could provide better integration or even built-in support. Busy with other stuff, so don't hold your breath. ut @ramiel's article should get you started.

**Comment by keslert** [comment]
Awesome, thanks @ramiel!

**Comment by asdutoit** [comment]
Hi @balazsorban44 & @ramiel, 

Thanks for the tutorial.   I got pretty far but encountered the following issues:
- Upon authenticating, the one-tap window reopens.
- The Session object returns an empty "user" object. 

Notes:
- I used Next-Auth version 3, not the new beta 4.   
- I used a custom DB connection for sake of testing.   (Data gets loaded to the MongoDB DB just fine.  No problems there)

What am I missing/doing wrong that prevents the authentication from completing?
My code is available here:  [Google One-Tap using Next-Auth](https://github.com/asdutoit/next-auth-template-with-google-one-tap)

If possible, could you provide a minimum working solution to Github that we can download and work from?

Thanks in advance

**Comment by ramiel** [comment]
Hello @asdutoit I had a look at your code an I think you're returning an array of users instead of a single one from your DB. 

```js
const user = await db.collection("users").find({ email }).toArray();

// later you return an array (the name of the variable is misleading
return user
```

Also your code is not correct because you're defining the `user` as const on line 101 and then trying to reassign on line 107.

I think you should use `findOne` instead of `find`

```js
let user = await db.collection("users").findOne({ email })
if (!user) {
  user = await db.collection("users").insertOne({
    name: [given_name, family_name].join(" "),
    email,
    image,
    emailVerified: email_verified ? new Date() : undefined,
  });
}
```

**Comment by asdutoit** [comment]
@ramiel, thanks for your reply. 
I think I am using the Mongo driver for Node.  You have to append the `.toArray()` method otherwise you are presented with an entire class object.  However, your answer still helped.   I just had to return `user[0]` instead of `user`.    Thanks for spotting my error there. 

The issue that now still persists is the One-Tap div that keeps popping up even though I have successfully authenticated.  

Not sure if this is relevant, but it seems that the `isSignedIn` boolean returned from the `useOneTapSignin` hook returns false even on a successful sign in.   (PS, I have added the `isSignedIn` to the hook to be returned for testing purposes)
<img width="1386" alt="Screenshot 2021-10-04 at 13 00 04" src="https://user-images.githubusercontent.com/20240370/135840146-c4451e23-a824-4c8e-8bb9-578370841e73.png">

I suspect the reason for this is that the `const { status } = useSession()` only works with Next-Auth version 4 whereas I am using v3.  

For now, in order to circumvent this issue (I have no idea whether this is a good idea though), I adapted the code in both the `header.js` and `useOneTapSignIn.js` files. 
Link to code:  [Google One-Tap using Next-Auth - Updated](https://github.com/asdutoit/next-auth-template-with-google-one-tap)

Now it works as expected.   

Thanks for all your help!

**Comment by ramiel** [comment]
Since you're using mongoDB native driver for node, the method [`findOne` is available](https://mongodb.github.io/node-mongodb-native/4.1/classes/Collection.html#findOne).

Yes, the guide is for NextAuth.js v4, you have to slightly modify to use with NextAuth.js v3 and your adaptation is good. A simpler version is to get rid of useEffect. I mean, this should work too:

```js
const [session, loading] = useSession();
const isSignedIn = !!session;
```

**Comment by ramiel** [comment]
Also, your code still has some issue: you return `user[0]` but if the user doesn't exist and you create a new one, `user` is an object, not an array.

**Comment by asdutoit** [comment]
Thanks @ramiel, I have made some of the recommended updates.  
I also tried `const isSignedIn = !!session;`. but this did not seem to work for my case.   I am sure I am just overlooking something.   Will investigate a bit more later. 
I think the issues I still have are minor problems that I will slowly identify and iron out.   

Again, thanks for all your help.

**Comment by ankitsinghvisionias** [comment]
When we are using nextauth google provider we don't need to use any adaptor, so can we create google one tap login without creating any new database.

**Comment by todaysprint** [comment]
> And finaly here the tutorial: https://www.ramielcreations.com/next-auth-google-one-tap
> 
> Many thanks to @balazsorban44 for help and suggestions

can you share the code along with email signin and one tap 
thanks

**Comment by FlyingThaCat** [comment]
> We at [hypersay.events](https://hypersay.events) already have one-tap implemented with next-auth. It's a matter of creating a custom credentials provider. If anybody is interested I could try to write an article. ![Screenshot_20211001_132219](https://user-images.githubusercontent.com/324687/135612033-e1c455c0-4768-4e44-b24a-40d9a1adbb88.png)

hi do you know how to fix this problem it seems only showing in dark mode
![image](https://user-images.githubusercontent.com/95353217/209437630-a021efd1-26c6-46a4-912a-0ca5fff32c3c.png)

**Comment by ramiel** [comment]
I actually know somebody who knows 😜 I'll ask him to join the discussion as soon as I find his handle

**Comment by DennieMello** [comment]
> hi @ramiel do you know how to fix this problem it seems only showing in dark mode. While im using light mode it seems not show any border but when switch to dark and to light mode weirdly it show the same white background
> ![image](https://user-images.githubusercontent.com/95353217/209437630-a021efd1-26c6-46a4-912a-0ca5fff32c3c.png)

set the block "color-scheme: light" in css
