### ISSUE TITLE
Credentials Documentation missing saltAndHashPassword

### ISSUE THREAD

**Issue by atonse** [nextauthjs/next-auth#10699]
### What is the improvement or update you wish to see?

Please include a best practices example for `saltAndHashPassword` in your credentials provider, or just implement password hashing as part of the overall provider.

Currently it just has a comment saying: 
```js
// Your own logic for dealing with plaintext password strings; be careful!
```

Asking folks to implement their own password hashing/salting would be a recipe for disaster security-wise. Is there another popular library that does this where we can get a well-tested implementation from?

Should we patch the credentials provider to follow certain best practices? (like using `argon2` or `bcrypt2` for hashing, and having this built in to the provider by default?)

I could work on a PR to begin work on it but this is best a community effort.

### Is there any context that might help us understand?

For something like implementing password hashes, there are well-accepted best practices (like using `argon2` or `bcrypt2` for password hashing). Can we make a default implementation in the credentials provider instead of relying on users to implement their own?

**Comment by ndom91** [comment]
Yeah so ideally we'd want to avoid folks doing this in the first place. Please use OAuth or magic links or webauthn instead of username / passwords. But because of popular demand we've kept this functionality / example of course. That being said, we're not going to wade into the waters of how specifically to manage passwords, that's up to you as the developer if you _really_ want to go down this path. 

If you come across a nice guide online, maybe we can link to it, but we don't want to encourage this any more than is necessary :sweat_smile:
