### ISSUE TITLE
Use Session Token in My API in Credential Mode

### ISSUE THREAD

**Issue by c7nasr** [nextauthjs/next-auth#1070]
**Your question**

1- So now I'll use next auth to authenticate users to my backend then nextjs auth will create sessions for me.
NextAuth creates a token session update every second I think? so I need to use this token in my backend with every request to validate the user. but always the JWT package on my backend(NodeJS) returns (INVALID SIGNATURE) for the auth nextjs session token. even if I defined my own secret. so how I use this token to my backend?

2- JWT generated for the session is handled by **maxAge** property. so the token expires in the time I defined in seconds unless the user not idle then it's refreshed. but how can I make the JWT valid for like (5 seconds) and refreshed without logging the user out due to inactivity? to prevent session steal?

**What are you trying to do**

**Reproduction**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by lnikell** [comment]
@c7nasr 
1 - Check the source code of the next-auth, on your backend you have to reproduce exactly the same verification logic as the next auth does on their side. 

https://github.com/nextauthjs/next-auth/blob/2f88880ee39e17012d4fc5ccdefe04016471a34b/src/lib/jwt.js#L90

I guess you can't verify it on your backend because you don't have a correct signing key.

If you have only `secret` set as a string,  Next.js  auth generate signing key the following way:

https://github.com/nextauthjs/next-auth/blob/2f88880ee39e17012d4fc5ccdefe04016471a34b/src/lib/jwt.js#L139-L148

2 - That's the question I also have :) I will try to read the source code more, however, it seems that there is no way at this moment to have to make the session and JWT work alongside.
