### ISSUE TITLE
Incorrect redirect URI in docs for Google OAuth for Next.js (400: redirect_url_mismatch)

### ISSUE THREAD

**Issue by janek** [nextauthjs/next-auth#10713]
### What is the improvement or update you wish to see?

It seems like `/api/auth/callback/google` should be `/auth/callback/google`. 

### Is there any context that might help us understand?

In docs (https://authjs.dev/getting-started/authentication/oauth and https://github.com/nextauthjs/next-auth-example?tab=readme-ov-file) the uri to put into google is defined as `http://localhost:3000/api/auth/callback/google` (assuming http://localhost:3000 as origin). 

When I clone the Auth.js Next example repo and follow the instructions, this gives me the following error:
<img width="394" alt="image" src="https://github.com/nextauthjs/next-auth/assets/2146927/5ebc1423-b0ae-4789-b286-ae1fa8469c2a">

Based on the details of the error message, I've changed it to `http://localhost:3000/auth/callback/google` (removed "/api" from the middle) and it worked. Maybe it's a "pages router vs app router" thing and the docs were not updated?

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/authentication/oauth
https://github.com/nextauthjs/next-auth-example?tab=readme-ov-file

(2-3 instances in each of those docs + perhaps somewhere else, too)

**Comment by janek** [comment]
I can now confirm that it's a "pages vs app router" thing, as I decided to use v4 instead of v5-beta in my project and the redirect URI from the docs works for a "pages" nextjs project.

**Comment by fernandomarca** [comment]
Similar problem in Kubernetes

"next": "14.1.4" "next-auth": "^4.24.7"

```bash

 Next.js 14.1.4
- Local:        http://localhost:3000
- Network:      http://0.0.0.0:3000

[next-auth][error][SIGNIN_OAUTH_ERROR]
https://next-auth.js.org/errors#signin_oauth_error only valid absolute URLs can be requested {
error: {
message: 'only valid absolute URLs can be requested',
stack: 'TypeError: only valid absolute URLs can be requested\n' +
'    at e.exports (/app/.next/server/chunks/638.js:39:36528)\n' +
'    at _.discover (/app/.next/server/chunks/638.js:39:42111)\n' +
'    at o (/app/.next/server/chunks/638.js:6:129314)\n' +
'    at s (/app/.next/server/chunks/638.js:6:121669)\n' +
'    at Object.s (/app/.next/server/chunks/638.js:30:8642)\n' +
'    at _ (/app/.next/server/chunks/638.js:6:107014)\n' +
'    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
'    at async a (/app/.next/server/chunks/638.js:30:18310)\n' +
'    at async e.length.t (/app/.next/server/chunks/638.js:30:19720)\n' +
'    at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484',
name: 'TypeError'
},
providerId: 'keycloak',
message: 'only valid absolute URLs can be requested'
}
```

**Comment by ndom91** [comment]
If yuo look closely on the page you linked (https://authjs.dev/getting-started/authentication/oauth), the **default** callback URL pattern varies depending on framework unforunately. This is somethign we kept this way to basically give better backward compatibility and avoid breaking existing folks things unnecessarily.

But anyway, so for **default** `next-auth@5.0.0-beta.*+` installations, the callbackUrl pattern is `/api/auth/callback/[providerId]`. 

For `@auth/sveltekit` and `@auth/express` the default is `/auth/callback/[providerId]`. 

In the example app you linked we also changed the `next-auth@v5.beta` setup to use the `/auth/callback/[providerId]` pattern via the `basePath` configuration option, because the example apps all share Google/GitHub/Twitter/etc OAuth Applications and therefore have to have the same callbackUrl, which is pointing to our proxy. This change made that easier.

The docs will work for `next-auth@v5` for both pages and app router, theres no difference there. 

@fernandomarca that seems to be a different issue. Can you open a new issue for that and provide more configuration detail if yuo do? Thanks!

**Comment by fernandomarca** [comment]
@ndom91 Thanks.
The issue I've investigated so far is that inside kubernetes /auth/callback/[providerId] doesn't work.
Nextjs executes requests with relative path such as: POST /api/auth/signin/keycloak
