### ISSUE TITLE
Update Edge Compatibility section for Middleware

### ISSUE THREAD

**Issue by IlyyA** [nextauthjs/next-auth#10821]
### What is the improvement or update you wish to see?

The middleware section in the [migrating to v5 page](https://authjs.dev/getting-started/migrating-to-v5#edge-compatibility) does not let the user know that you cannot access the authenticated user through the middleware if using the database. It currently reads as if making the relevant changes will be a successful workaround for all usecases, when instead it merely just allows the user to use the database adapter in other parts of the applicatoin **except** the middleware completely.

### Is there any context that might help us understand?

Inform the user that following this process to remove any Edge Runtime errors in the middleware will result in no database access in the middleware, resulting in no ability to protect resources in the middleware level, only on each individual page.

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/migrating-to-v5#edge-compatibility

**Comment by ndom91** [comment]
Thanks for pointing this out, we've just shipped a more general edge compatibility doc and mentioned the fact that when applying the split config workaround, that the middleware then doesn't ahve any access to the db.

https://authjs.dev/guides/edge-compatibility

**Comment by Chenalejandro** [comment]
@ndom91 

The provided documentation doesn't seem to work, I'm getting the error:
```
[auth][error] JWTSessionError: Read more at https://errors.authjs.dev#jwtsessionerror
[auth][cause]: JWEInvalid: Invalid Compact JWE
```
The error described in https://errors.authjs.dev#jwtsessionerror shouldn't be possible (It says that it is related to jwt strategy) since I am using the database strategy (since having an adapter in auth.ts automatically uses that stategy).

Another side note: I'm using an edge compatible driver (@vercel/postgres) and deploying to vercel (edge middleware), so in theory I am able to access the database in the middleware.
The problem I faced was too much latency (each page takes more than 1200ms to load). This is because the middleware always runs in edge, which is a problem when the database is in another region (for example, if the edge middleware is in India and the database is in us-east). It only works when the edge middleware is being run in the same region.

Vercel does not allows you to change the edge middleware region, it always default to the region nearest to the user.

**Comment by ndom91** [comment]
@Chenalejandro yeah having your DB far away is one of the inherent downsides to middleware / edge regions. Unfortuantely there's nothing we can do about that. See: https://twitter.com/leeerob/status/1780705942734331983
