### ISSUE TITLE
Wrong env variables examples in .env.example for contributors

### ISSUE THREAD

**Issue by lnikell** [nextauthjs/next-auth#1083]
**Describe the bug**
According to [Guide for contributors](https://github.com/nextauthjs/next-auth/blob/canary/CONTRIBUTING.md) we need to populate `.env.local` from `.env.example` which contains of

```
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_TWITTER_ID=
NEXTAUTH_TWITTER_SECRET=
NEXTAUTH_TWITTER_USERNAME=
NEXTAUTH_TWITTER_PASSWORD=
NEXTAUTH_GITHUB_ID=
NEXTAUTH_GITHUB_SECRET=
NEXTAUTH_GITHUB_USERNAME=
NEXTAUTH_GITHUB_PASSWORD=
NEXTAUTH_GOOGLE_ID=
NEXTAUTH_GOOGLE_SECRET=
NEXTAUTH_GOOGLE_USERNAME=
NEXTAUTH_GOOGLE_PASSWORD=
```
However inside this file we refer to variables such as GITHUB_ID and GITHUB_SECRET
https://github.com/nextauthjs/next-auth/blob/416d92c33f051c2a13219814e6deb6010e6462f5/pages/api/auth/%5B...nextauth%5D.js#L7-L12

So having `NEXTAUTH_GITHUB_ID` and  `NEXTAUTH_GITHUB_SECRET` won't work because `GITHUB_ID` and `GITHUB_SECRET` returns undefined. 

Another missing env variable that results in error in Sign in is:
https://github.com/nextauthjs/next-auth/blob/416d92c33f051c2a13219814e6deb6010e6462f5/pages/api/auth/%5B...nextauth%5D.js#L44

**Steps to reproduce**
- Clone git@github.com:nextauthjs/next-auth.git, then copy .env.example to .env.local. 
- Fill NEXTAUTH_GITHUB_ID and NEXTAUTH_GITHUB_SECRET
- Run 'npm run dev'
- Try to Sign In, you will get a 404 error from Github

**Comment by balazsorban44** [comment]
My bad. there is Yeah, I could have been more clear with the note under:

> NOTE: You can configure providers of the dev app in pages/api/auth/[...nextauth].js

You can override any env variables you want, just remember to edit them in the `[...nextauth].js` file as well.

But yeah.. At least the .env.example should match the default configuration.

**Comment by iaincollins** [comment]
Ugh sorry this my fault for using `NEXTAUTH_GITHUB_ID` in some places.

The tests use these and I also have a secret (requires long winded explanation) reason for experimenting with that prefix  on env vars - tl;dr related to easier / automatic provider configuration, as well as dynamic behaviour of the tests themselves.

On a possibly unrelated note my view has been we should ideally avoid having a pages dir in the root as it proved problematic in v1 because it masked some issues during testing, but I appreciate not having it makes life harder and working around it is a PITA and requires a bunch of work that is more convoluted to have it work any other way, so folks might take a different view. If we have tests that check the build is good in a Docker image then I guess we don't care and it's fine!

(@balazsorban44 has actually asked me about tests elsewhere, sorry I didn't respond about it yet!)
