### ISSUE TITLE
Please improve Express documentation.

### ISSUE THREAD

**Issue by uhidontkno** [nextauthjs/next-auth#10900]
### What is the improvement or update you wish to see?

The Auth.js docs are really lacking for Express, and as I'm a first-time user using Auth.js, it is hard to get the ropes when half the time I see:
![image](https://github.com/nextauthjs/next-auth/assets/86028086/9ac4d934-9408-4e83-8049-09c0190557fd)

### Is there any context that might help us understand?

*No response*

**Comment by ndom91** [comment]
Yeah Express is definitely the newest and least supported framework in terms of explicit documentation examples. 

Once you have the initial setup in Express though, the rest of the settings and options, etc. are identical to the next.js and svelte ones. 

For a basic setup, check out our [Express example app](https://github.com/nextauthjs/express-auth-example), and then you can tweak any settings in the `/src/config/auth.config.ts` file, just like in the other frameworks.

Anyway, I'm going to close this issue because its something we're aware of and working to improve all the time :pray: 

If yuo want to add anything we'd love any PRs :blush:

**Comment by uhidontkno** [comment]
Check out #10901

**Comment by ndom91** [comment]
> Check out #10901 

Awesome thanks a lot. Merged!
