### ISSUE TITLE
Transforming object received from OAuth authorization server on login

### ISSUE THREAD

**Issue by novelette17** [nextauthjs/next-auth#1095]
**Your question**
Is it possible to transform an object received from an OAuth authorization server?

**What are you trying to do**
The problem is that my OAuth authorization server returns like this:
```javascript
{
    data: {
        token_type: 'Bearer',
        expires_in: 3600,
        access_token: ...,
        refresh_token: ...
    },
    ...
}
```
Both tokens are inside the "data" object. The authorization server is based on Symfony (php). If I use the above object format, then there are authorization issues. To avoid problems with authorization, the response format should be as follows:
```javascript
{
    token_type: 'Bearer',
    expires_in: 3600,
    access_token: ...,
    refresh_token: ...
}
```
Unfortunately, but the format of the response from the backend cannot be changed, because such rules in our company. Is it possible, for example, using callbacks to write a "wrapper" to convert the "result" to another object?

So far, I've managed to achieve this by changing this line in the Next-auth sources (in node_modules/next-auth/dist/server/lib/oauth/callback.js:265):
![изображение](https://user-images.githubusercontent.com/77344700/104347358-5815ba00-5522-11eb-88f9-957775af7fbe.png)

Is there a more elegant way so that you don't have to edit the source like in my example solution?
Thank you!

**Feedback**

* [x] Could not find relevant documentation
* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there! Thank you for creating this issue!

So in an effort to simplify the Provider API (#1022), we kind of wouldn't like to expose more and more options on the Providers left and right, that are one-offs for certain providers, and so we started to handle special cases internally instead. It is extremely easy when we have a known `provider.id`, but it might be a bit strange when we don't know anything about a custom provider.
(I guess we could assume a certain `provider.id` anyway, but we probably wouldn't like to reserve provider IDs that we don't have [first-class support](https://next-auth.js.org/configuration/providers) for.)

`results.data` sounds like it could be a common case, so we might just add a fallback, like:

```js
results = results.data ?? results
```

and everything would be OK. But I just would like to take a round on this with @iaincollins before proceeding and hear his opinion.

We COULD expose more provider options, but I think we have to be very considerate about them, so they support as many cases as possible, to prevent the above mentioned one-off situations.

So the fix is not hard, we just need to decide on a good way of doing it.

**Comment by novelette17** [comment]
> Hi there! Thank you for creating this issue!
> 
> I am glad that you actually went and found the part of the code in the `src` that causes the trouble.
> 
> So in an effort to simplify the Provider API (#1022), we kind of wouldn't like to expose more and more options on the Providers left and right, that are one-offs for certain providers, and so we started to handle special cases internally instead. It is extremely easy when we have a known `provider.id`, but it might be a bit strange when we don't know anything about a custom provider.
> (I guess we could assume a certain `provider.id` anyway, but we probably wouldn't like to reserve provider IDs that we don't have [first-class support](https://next-auth.js.org/configuration/providers) for.)
> 
> `results.data` sounds like it could be a common case, so we might just add a fallback, like:
> 
> ```js
> results = results.data ?? results
> ```
> 
> and everything would be OK. But I just would like to take a round on this with @iaincollins before proceeding and hear his opinion.
> 
> We COULD expose more provider options, but I think we have to be very considerate about them, so they support as many cases as possible, to prevent the above mentioned one-off situations.
> 
> So the fix is not hard, we just need to decide on a good way of doing it.
> 
> It is worth mentioning though, that according to the OAuth 2.0 Access Token response spec (https://tools.ietf.org/html/rfc6749#section-4.1.4), the response should have the form:
> 
> ```json
> {
>   "access_token":"2YotnFZFEjr1zCsicMWpAA",
>   "token_type":"example",
>   "expires_in":3600,
>   "refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA",
>   "example_parameter":"example_value"
> }
> ```
> 
> Note there is no `data` property.
> So you might just want to take another round at work and ask for a good reason why the custom format? Do you maybe have a link to some kind of documentation?

Hi, Balázs Orbán! And thank you for answering! :-)

The problem is that the backend is based on Bitrix, the engine is quite outdated. At the moment, many of our microservices are configured for this object format. And changing the object format will create a lot of problems ...

You suggested a fallback in this form:
```js
results = results.data ?? results
```

This would be the perfect solution for us. But what if someone has a different key name instead of "data"? It would be great if you can specify this key in the **[... nextauth].js** file.

What if you do something like this (?):
![изображение](https://user-images.githubusercontent.com/77344700/104357866-8cdc3e00-552f-11eb-8814-9d138dd22049.png)

That is, just letting you set the mapping function. And we can already transform the object as we want :-)

What do you think?

**Comment by balazsorban44** [comment]
As said, the problem is not how to solve this problem, but how to solve this so it is future proof.

I'll try to get back to you at the weekend when I have talked to @iaincollins

**Comment by balazsorban44** [comment]
So after a talk, we agreed that we could maybe provide better, more flexible "hooks" into different stages of the OAuth process with provider options. Although it might not be included in the next release, since this requires us to think thoroughly through where do we want the users to be able to override things.

As a workaround, I suggest you write a script that adds the changes you need before deployment or fork the repo, create your changes, and publish it under a different npm scope. The library is licensed so nothing stops you from this. 🙂
