### ISSUE TITLE
wrong import in DuendeIdentityServer6 example

### ISSUE THREAD

**Issue by fmaule** [nextauthjs/next-auth#11265]
### What is the improvement or update you wish to see?

The provided example in the OAuth docs [here](https://authjs.dev/getting-started/authentication/oauth) has a wrong import.

### Is there any context that might help us understand?

`import DuendeIdentityServer6 from "next-auth/providers/duende-identityserver6"`

the provider is actually called `duende-identity-server6` https://github.com/nextauthjs/next-auth/blob/d00d91328e8f8284bc2d752855c1030a5d533f66/packages/core/src/providers/duende-identity-server6.ts#L96

The callback is probably wrong as well (`[origin]/api/auth/callback/duende-identityserver6`)

I believe the strings are automatically generated based on https://github.com/nextauthjs/next-auth/blob/d00d91328e8f8284bc2d752855c1030a5d533f66/docs/pages/data/manifest.json#L71

Happy to raise a PR to fix the docs

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/authentication/oauth

**Comment by k-taro56** [comment]
The function name is used for the import and does not need to be changed.
https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/duende-identity-server6.ts#L92C25-L92C35

The callback URL also does not need to be changed.

**Comment by k-taro56** [comment]
The `OAuthUserConfig.id` is part of the callback URL, and the `OAuthUserConfig.name` is the function name, and an import statement is generated.

The import statement and callback URL for each provider are read directly by the following script, rather than being automatically generated based on `next-auth/docs/pages/data/manifest.json`.

https://github.com/nextauthjs/next-auth/blob/main/docs/components/OAuthProviderInstructions/OAuthProviderSelect.tsx
