### ISSUE TITLE
Okta Documentation

### ISSUE THREAD

**Issue by beelarr** [nextauthjs/next-auth#11447]
### What is the improvement or update you wish to see?

I would like to see a sub section in this page that gives some specifics on setting up auth for preview deploys for specific providers.  https://authjs.dev/getting-started/deployment#securing-a-preview-deployment

### Is there any context that might help us understand?

I'm integrating Okta and chose not to use the AUTH_REDIRECT_PROXY_URL environment variable. Instead, I used wildcards in Okta to set the sign-in redirect URIs to `https://<project-name>*<vercel-team-id>.vercel.app/auth/callback/okta` and the sign-out redirect to `https://<project-name>*<vercel-team-id>.vercel.app/`.

## [Okta](https://support.okta.com/help/s/article/Does-Okta-Support-Wildcard-Redirect-URIs?language=en_US#:~:text=Okta%20supports%20the%20use%20of,not%20include%20a%20fragment%20component.)

_The `AUTH_REDIRECT_PROXY_URL` environment variable is not needed instead set wildcard URIs._
1. Set the sign-in redirect URIs to `https://<project-name>*<vercel-team-id>.vercel.app/auth/callback/okta`  (for app directory, pages directory would be /api/auth/callback/okta)
2. Set the sign-out redirect to `https://<project-name>*<vercel-team-id>.vercel.app/`
3. Make sure to select the option `Allow wildcard * in login URI redirect. 

### Does the docs page already exist? Please link to it.

https://authjs.dev/getting-started/deployment#securing-a-preview-deployment

**Comment by beelarr** [comment]
I am happy to work on this if y'all could use the help.

**Comment by balazsorban44** [comment]
Thanks for the suggestion, but I don't think we would like to advice for this, especially because a lot of our users are deploying on platforms like Vercel, where your default URL is `.vercel.app`, making it too easy to mess this setting up (imagine somebody setting `*.vercel.app` out of laziness). In addition, only a handful of providers actually support wildcards, making it more confusing when you want to set this up correctly with multiple providers, while our solution works uniformly.

Related: 
[OAuth 2.0 Security Best Current Practice: Redirect URI Validation Attacks on Authorization Code Grant](
https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#section-4.1.1)
