### ISSUE TITLE
Where are callbacks and events documented for typescript?

### ISSUE THREAD

**Issue by realtebo** [nextauthjs/next-auth#11766]
### What is the improvement or update you wish to see?

I am looking fom callbacks and events documentation. 
I also need Typescript examples

I am unable to find a way to reach this documentation starting from home page

### Is there any context that might help us understand?

No, simply, as user of the doc website, I cannot find a path from home to documentation I need

Also, When I reached the doc page, there is nothing about typescript

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/nextjs#callbacks

**Comment by k-taro56** [comment]
https://github.com/nextauthjs/next-auth-example/blob/9dfe43e70c2a501297605c0f58e1c73703f6c6e5/auth.ts#L100-L118

**Comment by realtebo** [comment]
Thanks.
But in this example params are not typed.

**Comment by k-taro56** [comment]
https://authjs.dev/reference/nextjs#type-declaration-2

**Comment by k-taro56** [comment]
> Thanks.
> But in this example params are not typed.

This example is written in TypeScript

**Comment by halvaradop** [comment]
I'm not entirely sure what your specific expectations are regarding the use of TypeScript in this context. Since Auth.js is written in TypeScript, there is usually no need to type things explicitly. We typically use TypeScript directly when we want to extend the default types provided by the library. For more information, please refer to the [Auth.js TypeScript documentation](https://authjs.dev/getting-started/typescript). You can also use the built-in AI on the website to clarify any doubts you may have.

On the other hand, in the case shown by @k-taro56 , the use of TypeScript is not very noticeable, but you should keep in mind that these functions were created in TypeScript, so there is no need to re-type them as they infer their types.

I hope this clarifies your doubts.

**Comment by balazsorban44** [comment]
https://authjs.dev/getting-started/typescript is the only specific docs we have for TypeScript users, other than the [API reference](https://authjs.dev/reference/nextjs). As stated above by others, all Auth.js libraries are written in TS, and you rarely need to type things manually. If you are having a TS issue, please open a bug report/Help request instead.
