### ISSUE TITLE
CSRF mismatch because of missing cookies

### ISSUE THREAD

**Issue by timonweber** [nextauthjs/next-auth#1179]
**Describe the bug**
We are currently having trouble with our custom provider because the state verification fails:

```
[next-auth][error][callback_oauth_error] Error: Invalid state returned from oAuth provider
```

I looked further into it (with some quick and dirty `console.log`) and noticed, that the CSRF cookie is renewed after the final redirect and therefore causing a CSRF mismatch.

This seems to be a symptom of not being able to retrieve the expected cookie (`next-auth.csrf-token`) after returning from the provider. Indeed, both NextAuth cookies (`next-auth.csrf-token` and `next-auth.callback-url`) are missing on the `GET` request that hits `/api/auth/callback/custom?code=abc&state=xyz` as part of the OAuth callback. But other session cookies used by our application can be found within that request.

**Steps to reproduce**
I am not able to provide a detailed reproduction as this may also depend on the configuration of our internal provider, sorry.

**Expected behavior**
I expect the previously issued CSRF cookie to be found after authenticating on the provider and the state verification to pass.

**Additional context**
As far as I can see, the cookie cannot be found on line 160, the check on 171 fails and then the cookie gets recreated on 176:

https://github.com/nextauthjs/next-auth/blob/78fd783bac990d8f2109487ac6598a38e3173f40/src/server/index.js#L160-L177

**Feedback**
* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by timonweber** [comment]
Maybe related to #656?

**Comment by balazsorban44** [comment]
Which version of `next-auth` are you using?

**Comment by timonweber** [comment]
Thanks for the quick response! You are right, I simply quoted the wrong code… I updated my initial post to align with `v3.1.0`.

So chances are that the issue is going to be resolved soon anyway? 🎉

**Comment by balazsorban44** [comment]
Hmm, I am not totally sure, the logic how we set the CSRF cookie and how it will compare the state is not planned to change. You can at least follow #1172 to see when I implement it in a PR, and you can test out the `canary` if it resolves your problem.

**Comment by iaincollins** [comment]
Thanks for reporting an issue. I don't know why this would happen, but I'll see if we can add some logging so that is easier to see if/when something like a CSRF cookie is rejected so it's more transparent / easier to debug.

We may not be able to resolve this without a way to replicate it, so any steps we can use to replicate would be helpful. I can't think of a scenario where the provider would matter, but perhaps client specific behaviour (or browser behaviour) that is not anticipated causes this to be the case.

The existing CSRF cookie should be left alone IIRC, but I'll check that behaviour and create a test for it.

It would be helpful to know:

- Which providers do you see this with? (no problem if custom, just good to know)
- Are you using the built in sign in pages or custom sign in pages (or Client API calls like signIn())?
- Do you see this in "production" or is it specific to local development builds?

**Comment by balazsorban44** [comment]
@timonweber #1172 has been fixed now (#1184), I also added some more debugger logging. (set `debug: true`).

**Comment by af608** [comment]
Hi, I am getting the same error using the latest canary build [3.2.0-canary.35].  The issue seems to be limited to the Safari browser (I am testing with Safari Version 14.0.2 [16610.3.7.1.9]) and it happens only when Safari was restarted.   It seems to work fine in Chrome [88.0.4324.96], Brave [v1.19.86 / Chromium: 88.0.4324.96] and Firefox [84.0.2].

It seems to work also fine on all browser versions with "state: false".

I tried to use also "protection: pkce", but this seems to have a similar issue on Safari.

This is the error I am getting with "state: true"

![najs-err-state](https://user-images.githubusercontent.com/3190283/105641619-daaf4b00-5e39-11eb-8640-8e723b22d8b3.png)


This is the error with "protection: pkce"
![najs-err-pkce](https://user-images.githubusercontent.com/3190283/105641651-06cacc00-5e3a-11eb-8bdf-1f28f078af3e.png)

**Comment by timonweber** [comment]
@iaincollins Thanks for looking into this. I am happy to provide the details you asked for:

- We are only using a single custom provider at the moment, which implements our own OAuth server (based on [`oidc-provider`](https://github.com/panva/node-oidc-provider)).
- Everything is set up with the Client API. The described issue is related to a `signIn()` call.
- We saw this in production first (local and staging environment were working fine), but last week it started to happen on my local machine as well. Very wild… 🤷

@balazsorban44 Thank you for the ping. I will try out the canary release and let you know if this changes the issue somehow.

@af608 Thanks for provide some more details. Indeed, it seems to be related to Safari…

**Comment by maerzhase** [comment]
FYI. I am experiencing the same error:
```
[next-auth][error][callback_oauth_error] Error: Invalid state returned from oAuth provider
```
But only when the projects runs in production on firebase hosting. 

The exact same project works just fine when:
- Running production in local firebase emulator (most peculiar...)
- Running production in vercel
- Running development locally

I am using the "Azure Active Directory B2C" Provider. 
Not sure how to go from here... Because i don't really understand at which point the state is lost...

**Comment by balazsorban44** [comment]
@maerzhase you say you use `canary` but the format of your error message suggests that you still use 3.1.0.

See https://github.com/nextauthjs/next-auth/blob/9ba15d8077eaa598dc7d574774d31d047c403a8a/src/server/lib/oauth/state-handler.js#L28 (OAuth casing has changed)

Can you verify that you use a canary version through checking what is inside node_modules?

**Comment by maerzhase** [comment]
@balazsorban44 sorry for laziness reasons i copied the error message from above... i verified it and the error message is actually from `canary` I also updated it in my post :)

**Comment by maerzhase** [comment]
This is the debugging log from the `POST /api/auth/signin/azureb2c`
```
cookies: {
    '__Host-next-auth.csrf-token': '40530180...|460ff4a178f55...',
    '__Secure-next-auth.callback-url': 'https://xxx.web.app/sign-in'
  },
  body: {
    csrfToken: '40530180...',
    callbackUrl: 'https://xxxweb.app/sign-in'
  }
} 
```
 ```
[next-auth][debug][oauth_callback_protection] Added state to authorization params {   state: '5b7adbbef4a347708514213e70e24f4fdeee7b9b76360ea7df680574efc67646' }

[next-auth][debug][get_authorization_url] https://login.microsoftonline.com/bd6f2e9e-9bd5-4b02-94da-0372e0d18593/oauth2/v2.0/authorize?response_type=code&response_mode=query&state=5b7adbbef4a347708514213e70e24f4fdeee7b9b76360ea7df680574efc67646&redirect_uri=https%3A%2F%2Fajour-cov.web.app%2Fapi%2Fauth%2Fcallback%2Fazureb2c&scope=offline_access%20openid&client_id=5a725ad4-b091-4ea0-b977-fd5fd83b024a 
```

It appears strange to me that the state added to the authoritation params is differrent than the actualy `csrfToken` received from body and cookie. Any idea why this could be happening?

**Comment by maerzhase** [comment]
The more I look into this I have the feeling it's due to this: https://firebase.google.com/docs/hosting/manage-cache#using_cookies

So with the limitation of cookies being stripped from incoming request and only one possible cookie available called `__session`, I guess its not possible to use `next-auth` with firebase hosting... what do you think @balazsorban44 ?

**Comment by balazsorban44** [comment]
Yes, I think so, very sorry for this. You could try writing to their support team.

**Comment by timonweber** [comment]
Unfortunately, I was not able to update to the latest version. After the version bump from `v3.1.0` to `v3.2.0` I noticed another cookie issue: This time the `next-auth.session-token` cookie that should be set after login was completely missing. (I am not completely sure whether this is a related issue. If you want, I can open another ticket.)

I tried to track this down a bit and saw that the correct `Set-Cookie` header was actually provided, but the browsers I tried (Safari, Chrome, Firefox) did not set that cookie. After reviewing [the changes between `v3.1.0` to `v3.2.0`](https://github.com/nextauthjs/next-auth/compare/v3.1.0...v3.2.0) I have a first wild guess: As the redirect method was changed from `options.redirect` to `res.redirect`, maybe we have a problem with header overwrites here? But as I know way too less about this change and the whole request/response thing, it is really just a thought, don’t judge me… 😬

https://github.com/nextauthjs/next-auth/blob/cdc1ac52b2f20a62a3218ce0f1c7e0aac04c08fb/src/server/routes/callback.js#L113

**Comment by balazsorban44** [comment]
So we moved `options.redirect`, but the logic did not change, so I don't think it has changed behaviour, but I'll double check:

https://github.com/nextauthjs/next-auth/blob/cdc1ac52b2f20a62a3218ce0f1c7e0aac04c08fb/src/server/lib/extend-req.js#L28-L34

**Comment by timonweber** [comment]
@balazsorban44 Thanks for the fast reply! 🙂 I’m glad you have already a clue what’s going on. If there is anything I can to help, let me know!

**Comment by balazsorban44** [comment]
@timonweber I recently had a deeper dive into this topic, and I posted some of my findings here: https://github.com/nextauthjs/next-auth/issues/1664#issuecomment-815285862

I see that you used `response_mode=query`, but configuring the cookies as suggested in the above comment might help. Could you try to verify?

**Comment by timonweber** [comment]
@balazsorban44 Thanks for the update and sorry for the late reply! I finally found the time to upgrade NextAuth to `v3.18.0` (built-in types, yey!). I can confirm that the state issue is gone as I can see the following in the server console now:
```
[next-auth][debug][oauth_callback_protection] Comparing received and expected state {
  state: '2b03d568ce05161ea9f5df9b13187ae00e927214c31a5f6133bb79208cef1c98',
  expectedState: '2b03d568ce05161ea9f5df9b13187ae00e927214c31a5f6133bb79208cef1c98'
}
```

But unfortunately I am still not able to upgrade, because the whole authentication flow is broken for me in newer versions as described in [my comment above](https://github.com/nextauthjs/next-auth/issues/1179#issuecomment-777371063). Even adding your custom `cookies` configuration does not help. Should I open a new issue about that?

**Comment by balazsorban44** [comment]
Hooray! I am going to close this issue then!

It sounds like you are having a different issue, and since it was a minor change, breaking is not acceptable, so I kindly ask you to open a new bug report (with a proper reproduction), and I'll try my best to help you track this down.

The change you mentioned seems irrelevant. Even though the redirect method changed its location, it should still have the exact same behavior as before. But I won't say it 100% yet. A bug report and reproduction would help terribly much! :pray:

**Comment by timonweber** [comment]
@balazsorban44 Alright, I will open a separate issue about that problem once I get this clear. I am bit afraid about providing a reproduction though, because there is a custom provider involved. If you have some advice regarding this, I am happy to learn… 😉

Anyway: Thanks for all your work! 😊

**Comment by balazsorban44** [comment]
you could try creating a dummy github app for example, or something similar. if you cannot reproduce it with another provider than it might be an issue with yours and we are closer to the solution anyway.
