### ISSUE TITLE
next@canary requires headers to be awaited

### ISSUE THREAD

**Issue by richardasymmetric** [nextauthjs/next-auth#11992]
### Environment

```
  System:
    OS: Linux 6.8 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 9.95 GB / 14.98 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  npmPackages:
    next: ^15.0.0-canary.179 => 15.0.0-canary.179 
    next-auth: ^5.0.0-beta.22 => 5.0.0-beta.22 
    react: ^19.0.0-rc-1460d67c-20241003 => 19.0.0-rc-1460d67c-20241003 

```

### Reproduction URL

https://github.com/vercel/next.js/blob/canary/examples/auth

### Describe the issue

with recent next@canary, it's expected that certain functions are now awaited, such as headers:
`
In route / a header property was accessed directly with `headers().get('x-forwarded-proto')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
`

### How to reproduce

1. Clone the next-auth/next example repo
2. update next to canary, react to rc, and next-auth to latest beta. 
3. fill in .env
4. yarn dev

### Expected behavior

no errors or warnings

**Comment by balazsorban44** [comment]
This issue was marked with the `good first issue` label by a maintainer.

This means that it is a good candidate for someone interested in contributing to the project, but does not know where to start.

Have a look at the [Contributing Guide](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md) first.

This will help you set up your development environment to get started. When you are ready, open a PR, and link back to this issue in the form of adding `Fixes #1234` to the PR description, where `1234` is the issue number. This will auto-close the issue when the PR gets merged, making it easier for us to keep track of what has been fixed.

Please make sure that - if applicable - you add tests for the changes you make.

If you have any questions, feel free to ask in the comments below or the PR. Generally, you don't need to `@mention` anyone directly, as we will get notified anyway and will respond as soon as we can)

> [!NOTE]  
> There is no need to ask for permission "can I work on this?" Please, go ahead if there is no linked PR :slightly_smiling_face:

**Comment by balazsorban44** [comment]
I believe these two files are all the places this needs to change:

https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/lib/actions.ts
https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/lib/index.ts

**Comment by MJomaa** [comment]
Hey @balazsorban44 we appreciate the work you put into this library. Just a quick question, since Next 15 RC 2 is out, will this take a bit longer? If yes no problem, I would provide an NPM patch for now.

Problem is that RC 2 and canary 178+ has a nasty bug fix regarding revalidation on redirect, but this dynamic API change got introduced in canary 171.

**Comment by khuezy** [comment]
Can this be ported to v4 soon?

**Comment by TephrosisDEV** [comment]
This error is still an issue.
Using next 15 beta
