### ISSUE TITLE
Middleware Returning Null Session

### ISSUE THREAD

**Issue by joshuaepstein** [nextauthjs/next-auth#12226]
### Environment

```
  System:
    OS: macOS 15.2
    CPU: (8) arm64 Apple M3
    Memory: 80.00 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
    pnpm: 9.12.3 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 18.2
  npmPackages:
    @auth/prisma-adapter: ^2.7.3 => 2.7.3 
    next: 15.0.2 => 15.0.2 
    next-auth: 5.0.0-beta.25 => 5.0.0-beta.25 
    react: 19.0.0-rc-02c0e824-20241028 => 19.0.0-rc-02c0e824-20241028 
```

### Reproduction URL

https://github.com/joshuaepstein/logicate/tree/middleware-authentication

### Describe the issue

When logging in, the browser stores the cookies and shows that it is logged in via the nav bar. The middleware however, doesn't respond the same and returns the session as null. I've tried adjusting my Next Auth Config but couldn't figure it out or find any similar issues

(Hosted on vercel and works in development environment)

I have also tried without prisma adapter and it did not resolve the issue.

### How to reproduce

You can see the website here: https://logicate.uk

And login with email: test@logicate.uk - And password: "password"
Once logged in it should take you to the home page and if you try to access the dashboard or canvases page it will return you back to the login page.

### Expected behavior

Should return the correct session from the JWT getToken function.

**Comment by balazsorban44** [comment]
The problem you have is likely that you forgot to configure the `secureCookie` option on `getToken`:

https://github.com/nextauthjs/next-auth/blob/1c37d9219e5ca5ff31a798488f0d05e8bac3f61c/packages/core/src/jwt.ts#L148

On HTTPS deployments, cookies are default prefixed with `__Secure`. This creates a mismatch with what your `getToken` implementation expects, causing the session cookie to not be found, and the session to be reported as null.

I see you host on Vercel, so one option is to set `secureCookie: process.env.VERCEL_ENV === "production"`, since all Vercel deployments will serve your site via https.

Ref: https://vercel.com/docs/projects/environment-variables/system-environment-variables#VERCEL_ENV

Note: `getToken` is likely going to be deprecated in favor of `auth()`, which should solve you issue as well. See https://authjs.dev/getting-started/migrating-to-v5#authenticating-server-side

**Comment by joshuaepstein** [comment]
Hi, I've tried to use your suggested fix with `secureCookie` but it didn't fix the issue. I also tried a different vercel project to see if that was the issue but it didn't work.
When I tried to use the `auth()` function it didn't work as I am doing this in the middleware and it gave a prisma error.

Is there anything I can try? I've re-opened my repo if you would like to see any of the middleware or authentication code.
