### ISSUE TITLE
Rate Limiting for Email Sign-In in NextAuth

### ISSUE THREAD

**Issue by hamedyosefian** [nextauthjs/next-auth#12288]
### Environment

NextAuth version: 4.24.7
Node.js version: v18.19.0
Database: PostgreSQL
Framework: Next.js

### Reproduction URL

https://github.com/hamedyosefian/next-auth-example

### Describe the issue

The /api/auth/signin/email endpoint in NextAuth does not implement any rate limiting. This allows users to send an unlimited number of email requests, making the system vulnerable to abuse and spam.

### How to reproduce

1-Set up a NextAuth project with email sign-in enabled.
2-Use a tool like Postman to make repeated POST requests to the /api/auth/signin/email endpoint.
3-Observe that multiple email requests can be sent without any restrictions.

### Expected behavior

There should be a rate limiting mechanism in place to prevent excessive email requests to the /api/auth/signin/email endpoint. This would help protect against spam and abuse by limiting the number of requests from a single source within a specified timeframe.

**Comment by balazsorban44** [comment]
Hi there! Since I cannot find your public contact information, I am not going to delete this issue, but in the future please reach out responsibly if you are unsure about a security-related issue. Many OSS projects will have a page like: https://authjs.dev/security

Thanks for understanding!

That being said: Rate-limiting is not currently a built-in feature of the Auth.js/NextAuth.js libraries, however you can use any off-the-shelf solution.

For context, the endpoint is CSRF protected via double-submit cookies, and won't send emails unless the check passes. Furthermore, we use Magic links with very high entropy, so brute forcing is effectively not possible.

I have been considering to implement an OTP variant of the Email login, in which case we would either add a built-in minimal rate-limiter, or inform you in the documentation to add one.

I am going to close this issue, as right now we don't have plans adding a rate-limiter.

If you have any follow-up questions around this, please reach out in email, using the information available at https://authjs.dev/security
