### ISSUE TITLE
Is it possible to use magic link sign-in only for pre-existing users? 

### ISSUE THREAD

**Issue by KerimG** [nextauthjs/next-auth#1229]
I would like to migrate our website to Next.js and we already have a database with users. I would like to move to magic links for sign-in but only for those existing users. 

Unfortunately, the docs for the email auth provider don't show how to accomplish that.

**Comment by iaincollins** [comment]
You should be able to use the signIn callback for this:
https://next-auth.js.org/configuration/callbacks#sign-in-callback

You should be able to look up the email address in the database (or just against a hard coded list!), I think it will be in `user.email`. If it doesn't exist in the database you can return `false` or a URL to redirect to (otherwise, returning `true` will allow them to sign in).

This works great for restricting access via email and OAuth providers like Google that have a 'email verified' property. You can even use this with oAuth providers that verify email addresses to provide access control on small sites without needing a database, as you can just have an array of email addresses (or a flat file with a list of them) and only allow listed accounts to create a session.

**Comment by iaincollins** [comment]
NB: This is an area I think we could improve on and reduce the code required, with some sort of "existing accounts only" option that would apply to all providers, but that's going to need a bit of thinking about with regard to should be tied to email address or specific OAuth provider account; email addresses are not trust worthy across all oAuth providers but tying it to an OAuth account would require knowing things like each users Account ID (which they are not going to know).

Ultimately a good way to address this is probably to implement some sort of "invite" option, where people can generate one time links to invite people to activate (much like the email sign in links), though that will also require some thought.

**Comment by KerimG** [comment]
Thanks a lot, @iaincollins! I completely forgot about the sing-in-callback!
