### ISSUE TITLE
No session after signin with redirect: false

### ISSUE THREAD

**Issue by cgerikj** [nextauthjs/next-auth#1264]
**Describe the bug**
When using the new redirect: false feature with credentials (https://github.com/nextauthjs/next-auth/pull/1219) in 3.3.0-canary.6, useSession returns null for the session and false for loading. Only a hard refresh/redirect updates the session.

**Steps to reproduce**
Steps to reproduce the behavior.
1. await a signIn with 'credentials' and { redirect: false }
2. router.replace('/profile')

**Expected behavior**
The session updates

**Sample code**
```
const signinResponse = await signIn('credentials', {
  email: email,
  password: password,
  redirect: false,
})
if (signinResponse.status === 200) {
  // getSession should not be needed here but even after this, useSession returns null in the /profile route
  getSession().then(session => {
    // session looks good here..!
    router.replace('/profile')
  })
} else {
  setError('Could not sign in!')
}

```

**Temporary solution**
```window.location.href = '/profile'```

**Comment by balazsorban44** [comment]
Hi there! The point of adding `redirect: false` is exactly stopping the page from redirecting to anywhere. Since it is the redirect that will update the session, disabling it will not update the session either.

I assumed this option has been asked from us to make it possible for users to handle errors on the same page.
You could do something similar to what we have in the dev app:

```jsx
...
const handleLogin = async () => {
  const response = await signIn('credentials', options)
  if (response.ok) return window.location.reload()
  // Handle errors here
  console.log(response.error)
}
...
return (
  <button onClick={handleLogin}>Login</button>
)
```

**Comment by iaincollins** [comment]
Hmm, if this is confusing for folks I wonder if we should call getSession() from the signIn() and signOut() functions when they are not redirecting?

**Comment by balazsorban44** [comment]
Yes, I had to think for a second about how to do this, but it makes sense. I created #1267 with a fix for this. I tested locally, and it looks fine for me.

**Comment by balazsorban44** [comment]
I have to say, that `signOut({redirect: false})` is a very nice experience, if you don't need to redirect the user to any other page than the one you are on...

**Comment by iaincollins** [comment]
Oh wow that was quick! 😀

Good point about the user experience.

I wonder if that should even be the default for signOut?

**Comment by balazsorban44** [comment]
Was thinking the same, we can decide on that later. I updated the PR with some docs as a tip for this.

**Comment by cgerikj** [comment]
Thank you, this is perfect! :)

**Comment by its-kos** [comment]
Can someone clarify for me. Because setting { redirect: false } still refreshes the login page, and inspecting the network I see a request with the same page as callback. Is this expected behavior ? Should calling signIn refresh the page even with the above option set ? Can I somehow make it not refresh the page ?

**Comment by Danilo-Guedes** [comment]
I always come back to this problem, in my application I use de signIn function with redirect : false, because in case of wrong credentials I show a toast and reset the fields. But when the user get the right credencials, it seems that for some reason the router object from the userRouter (next/navigation) does not work properlly, I've tryed router.push() router.replace() router.reload() and none of this trigger any action, and the only way to realy redirects the user is using the window.location methods.

**Comment by hashirshoaeb** [comment]
is this issue fixed in NextAuth v5?

**Comment by hashirshoaeb** [comment]
in NextAuth v5

For now i have called 
```
await __NEXTAUTH._getSession({ event: "storage" });
```
in client component right after 
```
await signIn("credentials", {
      phone: data.phone,
      password: data.otp,
      redirect: false,
    });
```
sigin's success. 

Thanks to: https://github.com/nextauthjs/next-auth/pull/1267

**Comment by DrewLandgraveCbsi** [comment]
Coming in 2025 with next-auth@beta and Next 16. I'm doing the signIn in server actions and the signIn function is returning the redirect string. 

I'm wanting the session so I can create some cookies in this method before it goes back to the user. We have other cookies that require data returned from the user data

```ts
   const result = await signIn('credentials', {
      email: formData.get('email'),
      password: formData.get('password'),
      redirect: false
    });

console.log(result) // http://localhost:3000/login
```

Any help here?
