### ISSUE TITLE
Credentials provider with db sessions instead of JWT

### ISSUE THREAD

**Issue by jeremygottfried** [nextauthjs/next-auth#1301]
**Summary of proposed feature**
Make it possible to use Credentials provider with db sessions instead of JWT.

**Purpose of proposed feature**
Credentials are a common way for users to log in to web apps. I am curious why this is not already supported considering how common email/password is.

**Detail about proposed feature**
User logs in with a username and password, and stays logged in with the next-auth db session.

**Potential problems**
I'm not sure. That's why I'm here.

**Describe any alternatives you've considered**
JWT authentication. But part of the reason I am using next-auth is because I don't want to use JWT. Next-auth makes it easier to do session auth.

If this is already possible, is there an example somewhere in the documentation for how to use session auth with credentials?
Even if it required customization, I'd prefer that over using JWT.

**Comment by balazsorban44** [comment]
the docs says:

> It comes with the constraint that users authenticated in this manner are not persisted in the database, and consequently that the Credentials provider can only be used if JSON Web Tokens are enabled for sessions.

> The functionality provided for credentials based authentication is intentionally limited to discourage use of passwords due to the inherent security risks associated with them and the additional complexity associated with supporting usernames and passwords.


https://next-auth.js.org/providers/credentials

**Comment by jeremygottfried** [comment]
@balazsorban44 How is a username and password inherently more risky than signing into my email with a username and password, and then clicking on a link to sign in?

> It's intentional. The docs says:
> 
> > It comes with the constraint that users authenticated in this manner are not persisted in the database, and consequently that the Credentials provider can only be used if JSON Web Tokens are enabled for sessions.
> 
> > The functionality provided for credentials based authentication is intentionally limited to discourage use of passwords due to the inherent security risks associated with them and the additional complexity associated with supporting usernames and passwords.
> 
> https://next-auth.js.org/providers/credentials

**Comment by iaincollins** [comment]
> @balazsorban44 How is a username and password inherently more risky than signing into my email account with a username and password, and then clicking on a link to sign in?

The problem with passwords is that people share passwords across accounts, [then they get compromised](https://haveibeenpwned.com/), then their accounts are hijacked; it sets users up for failure and it doesn't matter how secure your site is, because it comes down to the security of some other random site a user may have used the same (or similar) password on.

A goal of this project is to provide a solution that allows people to avoid those and other common security pitfalls - such as storing sessions in local storage or client side readable cookies where they can be hijacked, or putting private data in client accessible JSON Web Tokens and assuming "encoded" is the same as "encrypted".

With regard to email sign in there is more we can do make password more frictionless, including supporting shorter codes out of the box and cross-device verification (e.g. request a token via the desktop and tap a message on a phone to sign in on both devices) and I'd like to see us go in that direction.

NB: Using a username and password for your email without 2FA or a OTP is not a good idea and email providers like Google (and on services like Facebook) repeatedly prompt users to add 2FA if they are not using it already. 

That said, using a service like Google for Email *without* 2FA this is still more secure than using a simple username and password on a site as service providers like Google implement sophisticated threat detection, making it much harder for an attacker without local access to access your account, even if they know your credentials.

They are also likely to be able to provide better security for users than most developers managing their database of credentials; this is likely to be true with regard to maintaining security but also with regard to monitoring and handling disclosure and notifying impacted user in the event of a breach. These are things that are hard to do without adequate resources.

**Comment by jeremygottfried** [comment]
@iaincollins coming back to this after a year of using next-auth. While I understand there are security risks to username/password auth, I'm concerned that restricting people to JWT might have the opposite effect of encouraging devs who don't know any better to set long expiration dates on their JWT, with potential nightmares if a JWT is compromised.

One of the advantages to DB sessions is you can invalidate a session if the password is compromised/changes.

Personally, I chose to use `express-session` instead of `next-auth` for all non-admin sessions so my users could sign up with username/password. Customers expect this, and I can't just tell them, "sorry, the library I'm using doesn't let me have username/password". I think devs should be able to make this decision themselves, especially when practically every website with accounts offers username/password auth.

BUT 

If the security risks of username/password are an important issue to you, why not offer a custom username/password provider with additional levels of security similar to google, apple, etc? For example:

1. If signing up with username/password
2. User can select, "trust browser" to remember that IP.
3. If browser is not yet trusted, user is required to use some kind of 2FA.

Surely, that would be secure enough?

**Comment by tavindev** [comment]
I agree with @jeremygottfried here. If credentials login is less secure, providing only the JWT strategy makes it even worse. Not being able to invalidate the session if the password is compromised/changed is a not ideal at all.

And Jeremy really couldn't have put it better:

> Customers expect this, and I can't just tell them, "sorry, the library I'm using doesn't let me have username/password". I think devs should be able to make this decision themselves, especially when practically every website with accounts offers username/password auth.

Having db session for the Credentials provider would be really great.

**Comment by DennieMello** [comment]
+1

**Comment by nitedani** [comment]
> It comes with the constraint that users authenticated in this manner are not persisted in the database, and consequently that the Credentials provider can only be used if JSON Web Tokens are enabled for sessions.
 
How do users of auth.js use the credentials provider? Do they only call third-party services for authentication? Or, do they use the database to persist the user and password? I think it's very likely, they persist the user and password in the database, and validate the password locally. In this case, the intentional limitation(incompatibility with database providers) of the credentials provider causes insecurity, because users could insecurely implement the authentication logic on their end.
