### ISSUE TITLE
Getting error when changed NEXTAUTH_URL

### ISSUE THREAD

**Issue by yashSangai** [nextauthjs/next-auth#1342]
**Your question**
I am getting an error when I changed the NEXTAUTH_URL and with respect to that in the pages folder
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/usr/Documents/app/node_modules/nodemailer/lib/sendmail-transport'


> Build error occurred
Error: > Build failed because of webpack errors
```

**What are you trying to do**
I changed the value of NEXTAUTH_URL to `http://localhost:3000/edge/api/authentication` and corresponding to that changed the file path of [...nextauth].js to pages/edge/api/authentication/[...nextauth].js

Now when I execute `npm run build`, I get the above-mentioned error.

I followed [this](https://next-auth.js.org/getting-started/rest-api), at the end where **NOTE** is written.

PS: I am using the latest version of next-auth

Please help me in knowing what I am doing wrong.

**Comment by balazsorban44** [comment]
Hmm. I am not sure what the intention in the docs was (cc @iaincollins), but to get this working, I did the following:
1. Let the `[...nextauth].js` file be in the `/api/auth` folder
2. Set `NEXTAUTH_URL` to `http://localhost:3000`
3. Add a rewrite to `next.config.js`:
```js
//next.config.js
module.exports = {
  rewrites () {
    return [
      {
        source: '/edge/api/authentication/:path*',
        destination: '/api/auth/:path*'
      }
    ]
  }
}
```

Then you can use `/edge/api/authentication` for your `next-auth` related endpoints as they are explained in the docs: https://next-auth.js.org/getting-started/rest-api

**Comment by yashSangai** [comment]
Thanks for the explanation @balazsorban44.
Could you please also help me in telling me how can I change the `next-auth` related endpoints, I am getting a bit confused here?

My [...nextauth].js file:
```
import NextAuth from "next-auth";
import Providers from "next-auth/providers";

const options = {
  // Configure the google authenticator provider
  providers: [
    Providers.Google({
      clientId: process.env.NEXTAUTH_GOOGLE_ID,
      clientSecret: process.env.NEXTAUTH_GOOGLE_SECRET,
      authorizationUrl:
        "https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline&response_type=code",
    }),
  ],
  jwt: {
    encryption: true,
    secret: process.env.JWT_SECRET,
    signingKey: process.env.JWT_SIGN_KEY,
    encryptionKey: process.env.JWR_ENCRYPTION_KEY,
  },
};

export default (req, res) => NextAuth(req, res, options);

```

**Comment by balazsorban44** [comment]
Your config does not have to change, it looks fine as is. (Although it can be simplified to:
```js
import NextAuth from "next-auth";
import Providers from "next-auth/providers";

export default NextAuth({
  // Configure the google authenticator provider
  providers: [
    Providers.Google({
      clientId: process.env.NEXTAUTH_GOOGLE_ID,
      clientSecret: process.env.NEXTAUTH_GOOGLE_SECRET,
      authorizationUrl:
        "https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline&response_type=code",
    }),
  ],
  jwt: {
    encryption: true,
    secret: process.env.JWT_SECRET,
    signingKey: process.env.JWT_SIGN_KEY,
    encryptionKey: process.env.JWR_ENCRYPTION_KEY,
  },
});
```
)

**Comment by yashSangai** [comment]
Oh ok. I will simplify it.

My bad, maybe I didn’t explain my point clearly. What I meant to ask is after doing the required change suggested by you in next.config.js,
How can I do this
`Then you can use next-auth related endpoints as they are explained in the docs, only change /api/auth with /edge/api/authentication: https://next-auth.js.org/getting-started/rest-api`

My intention is to change the base path of all next-with REST API endpoints

**Comment by balazsorban44** [comment]
With the rewrite, if you go to eg.:

`/edge/api/authentication/session`, it will correspond to `/api/auth/session` in the docs. You don't have to do anything else

**Comment by yashSangai** [comment]
@balazsorban44 I get that by using rewrite in `next.config.js`, `/edge/api/authentication/session` will correspond to `/api/auth/session`. 

But what is happening on the client next-auth API calls are happening to /api/auth/* only, whether it is signI, signOut, callback, session, csrf. How can I change the base path to /edge/api/authentication/session` 

>  for these when these calls happen.

**Comment by balazsorban44** [comment]
Huh, you are actually right. I am actually not 100% sure what is happening so hopefully, Iain could clear this up.

**Comment by iaincollins** [comment]
Hi there!

Hmm yes, setting `NEXTAUTH_URL` to `http://localhost:3000/edge/api/authentication` should work as expected in this scenario.

The path in `NEXTAUTH_URL` is optional, and defaults to `/api/auth` but if a path is specified will use whatever you put in and should "just work" (this is a feature I have also used from time to time). The magic of environment variable is that it is exposed both client and server side and so the **domain** and **base path** configuration only needs to be specified in one place.

It assumes that you have something in front of your application (like a CDN or an nginx proxy, etc) handling the URL re-writing. I don't actually know how it interacts with re-writes in `next.config.js` and would need to try that out. I am not sure, but it may be that the `rewrites` feature is only for pages and doesn't work for API routes and so that is not the option you are looking for (you may need to run a custom server if you wish to prefix API routes this way, without using something like nginx, varnish or a CDN). 

I don't know what is causing that build error but I don't think it actually has anything to do with the value in `NEXTAUTH_URL`. It seems like something else about the configuration is a causing a problem and we would need access to the repo to be able to debug.

I suggest cloning the example repository used for https://next-auth-example.now.sh/, getting it working locally, then doing the minimal tweaking it to get URL re-writing working with it, then comparing what is different with your repo with the example repo.

**Comment by balazsorban44** [comment]
@iaincollins the Ops issue is that they defined an api route outside the pages/api. You cannot actually define api routes elsewhere in pages, because Next.js expects page components to be exported as the default. See #1228 as well.

**Comment by yashSangai** [comment]
@iaincollins I am using a serverless NextJS app and currently, there is no CDN, proxy, or Nginx in front of it. When I changed the `NEXTAUTH_URL` to `http://localhost:3000/edge/api/authentication`, it threw me an error that this URL does not exist.

Are you suggesting me to have a custom server for my NextJS App and do the re-writing of the URL there?

I cloned the example repository and only changed the NEXTAUTH_URL variable, the same error occurred!
cc: @balazsorban44

**Comment by yashSangai** [comment]
@iaincollins If it is possible Can you share an example repo for the same?

**Comment by iaincollins** [comment]
> @iaincollins If it is possible Can you share an example repo for the same?

I don't have another example repo to share with you, other than the example project I created that is is ready to go and that I have already linked to. Again, I suggest adding the URL customisation to that project.

Note that if `http://localhost:3000/edge/api/authentication` maps to `http://localhost:3000/api/auth` then neither of those will exist as that is not a route handled by `[...nextauth].js`.

You would need to try a route like `http://localhost:3000/edge/api/authentication/signin` or `http://localhost:3000/api/auth/signin`.
