### ISSUE TITLE
MySQL "caching_sha2_password" Support

### ISSUE THREAD

**Issue by velocity23** [nextauthjs/next-auth#1347]
**Summary of proposed feature**
Currently, only `mysql_native_password` is supported by the default adapter, it would be nice if the more modern `caching_sha2_password` were also supported.

**Purpose of proposed feature**
Provide support for the most recent version of MySQL and it's default (and more secure) authentication method.

**Detail about proposed feature**
N/A, not too familiar with the adapters side of things

**Potential problems**
Not sure whether this would involve updating the `mysql` package and dealing with breaking changes that come with that, but that is a possibility.

**Describe any alternatives you've considered**
For now I can just use `mysql_native_password` with MySQL 8, but it would be ideal if SHA2 was compatible.

**Additional context**
N/A

*Please indicate if you are willing and able to help implement the proposed feature.*
If needed, yes. But I'm not so good with low-level DB stuff.

**Comment by iaincollins** [comment]
Hi there, I looked into this (but have lost the references!) and I think this is actually an issue with the MySQL driver for Node.js.

I seem to recall it's also an issue that's been raised with the TypeORM folks, though again I don't actually think it's something they can do anything about either and that the driver just doesn't support it currently.

If the driver DOES get support then it should "just work".

Closing this as I don't think we can help, but if anyone wants to add any info to this ticket for those looking for a citation, or if you want to re-open with new information because there is action we can take, then please do.
