### ISSUE TITLE
Auth0 doesn't ask for login details again after logging out 

### ISSUE THREAD

**Issue by Jonofat** [nextauthjs/next-auth#1384]
I am using Auth0 as my login method and have got it working. However, when I logout and then click on login again, it doesn't present me with the Auth0 login like the first time where I need to enter my username and password, it just seems to auto log me in. I don't want this to happen. If I log out and click to log in again, it should make me input username and password. 

```
        <button
          onClick={() =>
            signOut({ callbackUrl: "http://localhost:3000/admin" })
          }
        >
          Sign out
        </button>
```

**Comment by balazsorban44** [comment]
It's because currently we don't support federated logout yet. Meaning when you log in the first time, you will have to log in in your Auth0 account. But logout will only log out from the current app rather than from Auth0. It's achievable in user space but we should support it for better OIDC compliance
