### ISSUE TITLE
Return Multiple Session Object 

### ISSUE THREAD

**Issue by SabariVig** [nextauthjs/next-auth#143]
If the person is logged in from multiple devices return back multiple session objects.Better If the users are serialized first

**Comment by iaincollins** [comment]
To keep the size of the `session` object down, in particular with an eye on JWT token support in future, I don't think we will add a list of all sessions to the current session object.

However, I don't see why we couldn't provide a similar API endpoint (e.g. `/api/auth/sessions`) that behaved the same way, and also allowed people to terminate sessions belonging to them in order to log themselves out of other computers (a commonly supported feature).
