### ISSUE TITLE
"Securing pages" example wrong?

### ISSUE THREAD

**Issue by Glutch** [nextauthjs/next-auth#1487]
Page: https://next-auth.js.org/tutorials/securing-pages-and-api-routes

You pass down the session prop but never use it and declare the client side version of session. I assume this is wrong?

```javascript
import { useSession, getSession } from 'next-auth/client'

export default function Page() { //server side session prop not used
  const [ session, loading ] = useSession() //declare a new client side prop (?)

  if (typeof window !== 'undefined' && loading) return null

  if (session) {
    return <>
      <h1>Protected Page</h1>
      <p>You can view this page because you are signed in.</p>
    </>
  }
  return <p>Access Denied</p>
}

export async function getServerSideProps(context) {
  const session = await getSession(context)
  return {
    props: { session } //server side session prop
  }
}
```

**Comment by kennethvandenberghe** [comment]
If I understand next-auth correctly (being a new user of this library), this is my take:

If you also have the Provider configured in _app.js (as explained here: https://next-auth.js.org/getting-started/example#add-session-state), it is technically the serverside session we are getting in the useSession hook in our Page component.

If we have a look at the source code of useSession:
```
export function useSession (session) {
  const context = useContext(SessionContext)
  if (context) return context
  return _useSessionHook(session)
} 
```

So here we see that if we have a sessionContext around our page, the useSession hook will use that session info and not create new info. And since we pass that session prop from getServerSideProps to our _app, and that is setting that prop on the context, the useSession hook in our Page component actually points to the session object in our context (and thus the one received from getServerSideProps).

```
export default function App ({ Component, pageProps }) {
  return (
    <Provider session={pageProps.session}>
      <Component {...pageProps} />
    </Provider>
  )
}
```

So either way if you define session as an incomming prop, or use the useSession with context, you are pointing to the same session info.

Hope I make sense here.

**Comment by Glutch** [comment]
@kennethvandenberghe Oh... Thank you for explaining! That's some magic there :)

**Comment by balazsorban44** [comment]
Perfect explanation by @kennethvandenberghe! We could improve the docs on this, already tracking it here: #1132 Closing this, as it is a "known problem" with the docs. It is up for taking, as a good first issue, if anyone interested :) Check out #1132
