### ISSUE TITLE
Results from linkedin auth are null besides name

### ISSUE THREAD

**Issue by ludersGabriel** [nextauthjs/next-auth#1540]
**Your question**

Is linkedin auth bugged for email?
**What are you trying to do**

I'm trying to recover the email from linkedin with the scope 'r_emailaddress r_liteprofile', but the results are null. Linkedin's login confirmation page shows that the app is requesting email and I have another website that uses the same linkedin app that works, so I'm starting to believe that this might be a bug.
**Reproduction**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by balazsorban44** [comment]
It's probably because the built-in LinkedIn provider does not set the email by default:
https://github.com/nextauthjs/next-auth/blob/776b9480da7d0b51bf3b1358be61fa0490126011/src/providers/linkedin.js#L20

try overriding the profile callback and return e-mail for your provider. If it is something that can be fetched in one pass (meaning that adding a scope), I think the default LinkedIn provider behavior could also be tweaked to get the e-mail by default.
