### ISSUE TITLE
Github auth not redirect correctly

### ISSUE THREAD

**Issue by IgorDePaula** [nextauthjs/next-auth#1640]
**Describe the bug**
When  I authenticate using github provider, all time I'm redirect to login page. 

**Steps to reproduce**
configure the github provider
try auth using github account

**Expected behavior**
I expect get access to protected page.

**Screenshots or error logs**
No error is trhowing

**Additional context**
I add console log in all steps, I receive token, session is created, but the session is no passed to protector provider.

the repo is https://github.com/IgorDePaula/nextjsauth / is not personal project, is a test for another projects.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ x ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by IgorDePaula** [comment]
![Uploading Captura de Tela 2021-04-02 às 09.34.58.png…]()

**Comment by IgorDePaula** [comment]
![Captura de Tela 2021-04-02 às 09 34 58](https://user-images.githubusercontent.com/2833993/113416553-faae3e00-9397-11eb-8c1c-f31c01231e00.png)

**Comment by balazsorban44** [comment]
https://www.github.com/IgorDePaula/nextjsauth/tree/main/pages%2Flogin.js

line 35,it is `"github"`, not `"GitHub"`.

You also haven't provided an`callbackUrl` option, and by default, you will be redirected to the same page you started on (in this case, login)

docs: https://next-auth.js.org/getting-started/client#specifying-a-callbackurl

**Comment by IgorDePaula** [comment]
I'll try. Thank you very much.

**Comment by IgorDePaula** [comment]
Not work, When redirects to my callback URL, the user is redirected to login again.

**Comment by IgorDePaula** [comment]
@balazsorban44  Your suggestion not work, the problem persists.

**Comment by balazsorban44** [comment]
It's because of the logic in `/welcome` you have written and the way you are using the callbacks.

You check for the existence of `accessToken`, but if you print out `session`, it won't be there, because by default we don't forward it to the client. You can override this with the jwt and session callbacks (which you have done, only incorrectly, read further)
https://github.com/IgorDePaula/nextjsauth/blob/52c0197f9e02f3b3226ba70527f058f3222214c9/pages/welcome.js#L11

If you want to send an access token to the client, add this line back:
https://github.com/IgorDePaula/nextjsauth/blob/52c0197f9e02f3b3226ba70527f058f3222214c9/pages/api/auth/%5B...nextauth%5D.js#L57

The `accessToken` is on the third argument ( we call it account), not on `user`, especially not `data`. Change line 48 accordingly, and please have a look at the documentation!
https://github.com/IgorDePaula/nextjsauth/blob/52c0197f9e02f3b3226ba70527f058f3222214c9/pages/api/auth/%5B...nextauth%5D.js#L43-L48

https://next-auth.js.org/configuration/callbacks#jwt-callback
https://next-auth.js.org/configuration/callbacks#session-callback
https://next-auth.js.org/getting-started/client#specifying-a-callbackurl

**Comment by IgorDePaula** [comment]
@balazsorban44 Thank you very much, You opened my mind. I make another tests and I now fix the problem. Again, Thank you very much.
