### ISSUE TITLE
Auto-generate src/providers/index.js

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1778]
It is simply a re-export of the default functions in the same folder.

- [x] use named function declaration for all built-in providers (like the Instagram one)
- [x] add script to generate `src/providers/index.js` on build
- [ ] Add JSDoc comments, like in Instagram https://github.com/nextauthjs/next-auth/blob/main/src/providers/instagram.js
- [ ] Explore ways of autogenerating documentation pages in https://github.com/nextauthjs/next-auth/tree/main/www/docs/providers

**Comment by ndom91** [comment]
So I was beginning to create the jsdoc examples in all the provider config files, and its alright when its just the basic usage example and the two standard links, but some providers have all sorts of extra info in there which leads the jsdoc to sometimes because twice as long as the actual config haha.

Are we sure we want to pack all that info in the comments of a the provider .js files?

**Comment by balazsorban44** [comment]
Hmm, maybe just a compressed version. But it is nice if the user won't have to leave the IDE if they have  a basic use case.

We might not get away with generating everything from a single file for now.

**Comment by balazsorban44** [comment]
I think the third item on the todo list should be incorporated in #2395. cc @lluia

The last item might be a bit magical, but #2395 probably could make it easier as well. Closing this to track progress in that PR instead.
