### ISSUE TITLE
Using NextAuth on Subdomains / Redirect loop back to Login Page

### ISSUE THREAD

**Issue by douglaseggleton** [nextauthjs/next-auth#1888]
## Question 💬

This project is great  🙌🏻 Are multiple subdomains an issue?

I have multiple sites setup on Netlify as separate projects (with NextJS plugin), `<site1>.test.com`, `<site2>.test.com` and `test.com`. I also have Google Auth setup to authenticate on all 3 of these under separate OAuth Clients (each with their own client ID/secret).

test.com works as expected, I can login and a session exists (and persists)

`<site1>.test.com` and `<site2>.test.com`do not work as expected, they will endlessly keep redirecting to `api/auth/signin?csrf=true` without redirecting to google or creating a session,

I've not seen any issues similar but did attempt to play around with the custom cookies (settings `domain:`) but without much luck. Would appreciate tips/suggestions or help 🤗

## Contributing 🙌🏽

It takes a lot of work 🏋🏻‍♀️ maintaining a library like `next-auth`; any contribution is more than welcome 💚

In case you're willing to help answer this question, please let us know here, and we'll reach you 😊 . Otherwise, you can have a look at the issues labelled with [`"good first issue"`](https://github.com/nextauthjs/next-auth/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and pick any of them.

**Comment by spencerarogers** [comment]
Hi @douglaseggleton,

We just ran into this issue too and it's on Netlify's end, see this issue here:

https://answers.netlify.com/t/bug-netlify-functions-event-headers-cookie-sometimes-suddenly-used-comma-instead-of-semicolon/36793

Good luck!

**Comment by julianengel** [comment]
Yeah, it is something that started popping up around the 21st of April on Netlify's end, where randomly the cookies are separated by comma instead of semicolon....

**Comment by douglaseggleton** [comment]
@julianengel @spencerarogers Thanks for chiming in! 🙏🏻  I didn't even think to check this

I'm indeed having the same issue - the cookie headers are sometimes separated by commas as opposed to semicolons.
It was ~1 week ago our auth became flakey, then just stopped working (we switched over to Netlify at the start of April)

**Comment by tmilewski** [comment]
@julianengel @douglaseggleton Here's a quick "get things running again" pass at how @spencerarogers and I are working around it.

Please poke holes if you see any.


### [...nextauth].ts
```tsx
// [...]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type NetlifyNextApiHandler<T = any> = (req: NetlifyNextApiRequest, res: NextApiResponse<T>) => void | Promise<void>

const authHandler: NetlifyNextApiHandler = (req, res) => {
  // We do some fun stuff here. In reality, `options` would just be your NextAuth config object.
  const base64Context = req?.netlifyFunctionParams?.context?.clientContext?.custom?.netlify
  const options = dynamicOptions(base64Context)

  const keys = Object.keys(req.cookies)
  const badState = keys.length === 1

  if (badState) {
    const firstKey = keys[0]
    const remainingVals = req.cookies[firstKey]
    const parsedVals = remainingVals.split(',')

    req.cookies = {
      [firstKey]: parsedVals.shift(),
      ...Object.fromEntries(
        parsedVals.map(val => val.split('='))
      )
    }
  }

  return NextAuth(req, res, options)
}

export default authHandler
```

**Comment by douglaseggleton** [comment]
@tmilewski Thanks - Worked a treat 👌🏻

**Comment by joshsny** [comment]
@tmilewski This really saved my site. Have been trying to debug my NextAuth config for the last day or so, didn't think that it could be an issue on Netlify's side.

**Comment by ELF1sH** [comment]
We faced quite the same problem. Our project is hosted on several subdomains:
1. `domain.com`
2. `subdomain1.domain.com`
3. `subdomain2.domain.com`
4. ...
5. `subdomain9.domain.com`

Authorization flow works perfectly fine on `localhost` because it is a single domain name. After hosting the project on the remote server, `next-auth`, while being opened on the `subdomain1.domain.com`, right after successful login tries to redirect to `http://domain.com` since that is the url specified in the `NEXTAUTH_URL` env variable. As a result, it displays the error page with a note `Try signing in with a different account`. This means that we need to somehow dynamically set the env variable `NEXTAUTH_URL`. We use `next-auth 4.24.7`, Keycloak Provider and `next 14.0.3`. Although the following solution should apply to different types of providers and `next-auth`'s versions.

***Step 1.***
Get rid of the `NEXTAUTH_URL` env variable. Since we are using Keycloak provider, the only authentication-related env variables we have are `KEYCLOAK_CLIENT_ID`, `KEYCLOAK_CLIENT_SECRET`, `KEYCLOAK_ISSUER` and `NEXTAUTH_SECRET`.

***Step 2.***
Rewrite the `next-auth` api handler. The official `next-auth` documentation suggests using the following approach (applied to `next.js` with the app directory):
`touch app/api/auth/[...nextauth]/route.ts` and paste the following code there:

```
import NextAuth from "next-auth/next";

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };
```

There is a huge disadvantage to this approach. You cannot customize the handler itself. There is no function body where you can insert your own custom code. Therefore, we suggest rewriting the file as follows:

```
import { NextApiRequest, NextApiResponse } from 'next';
import { NextRequest, NextResponse } from 'next/server';
import NextAuth from 'next-auth';

async function auth(req: NextRequest, res: NextResponse) {
  return await NextAuth(req as unknown as NextApiRequest, res as unknown as NextApiResponse, authOptions);
}

export { auth as GET, auth as POST };
```

It works exactly the same while being more flexible. Every auth request goes through this 'middleware'. Here we're going to dynamically set the `NEXTAUTH_URL` env variable depending on the host and protocol of the request headers

```
async function auth(req: NextRequest, res: NextResponse) {
  const protocol = req.headers.get('x-forwarded-proto');
  const host = req.headers.get('host');

  process.env.NEXTAUTH_URL = `${protocol}://${host}/api/auth`;

  return await NextAuth(req as unknown as NextApiRequest, res as unknown as NextApiResponse, authOptions);
}

export { auth as GET, auth as POST };
```

***Step 3.***
Specify the `redirect` callback in the `authOptions`.

```
callbacks: {
  // ...
  // your callbacks here, such as `jwt` and `session`
  // ...
  async redirect({ url }) {
    return url;
  },
}
```

The first `url` argument is the url received from the client side of the application. In other words, this is the url that you pass as the `callbackUrl` argument when calling the `signIn` function.

```
await signIn('keycloak', { redirect: false, callbackUrl: window.location.origin });
```

***Step 4.***
Make sure you pass `window.location.origin` as the `callbackUrl` every time you invoke `signIn` or `signOut` functions.

After completing the previous steps, your authorization flow should work fine. If you're concerned about the rest of the code, you can follow these tutorials: [part1](https://medium.com/inspiredbrilliance/implementing-authentication-in-next-js-v13-application-with-keycloak-part-1-f4817c53c7ef) and [part2](https://medium.com/inspiredbrilliance/implementing-authentication-in-next-js-v13-application-with-keycloak-part-2-6f68406bb3b5).

However, you may encounter a bug: when different users from different computers log in at the same time, their redirect URLs after successful login may get mixed up, and, as a result, users may end up in someone else's subdomain. Because of that users see `Try signing in with a different account` error page once again. In order to avoid this behavior, complete the upcoming step.

***Step 5.***
Your `SessionProvider` should look like this.

```
export default function AuthSessionProvider(props: PropsWithChildren) {
  const { children } = props;

  return (
    <SessionProvider refetchInterval={REFETCH_INTERVAL} refetchOnWindowFocus>
      {children}
    </SessionProvider>
  );
}
```

Avoid using `basePath` prop of the `SessionProvider` at any cost. It took us several weeks to find out that this prop was causing the bug with incorrect redirects after successful logins.
