### ISSUE TITLE
Can I custom user agent when signin to Google ?

### ISSUE THREAD

**Issue by YoannBuzenet** [nextauthjs/next-auth#1986]
Hello,

When connecting to google through Linkedin webview, my users get an error and can't connect.

![image](https://user-images.githubusercontent.com/28066290/118027097-d57ef900-b361-11eb-85d8-4cd6578f6184.png)

I saw that I could precise user agent by my self to get validated by Google. However, I'm not sure if I can do it ? I tried to see the signIn function but I'm not sure I can do this ?

Thank you for your help and for this amazing lib !

Yoann

**Comment by balazsorban44** [comment]
This is out of scope for `next-auth`. You probably don't want to do it anyway. When a User-Agent is checked, it might be because that particular browser does not support something that it is supposed to for the process to work. In any way, your communication between google and linked in doesn't get to us, so it is totally out of our hands.
