### ISSUE TITLE
Cannot build next-auth-example with target: serverless (typeorm)

### ISSUE THREAD

**Issue by andyjaar** [nextauthjs/next-auth#2048]
## Description 🐜

When I build the next-auth-example project with a couple of minor changes, I get:
```ModuleNotFoundError: Module not found: Error: Can't resolve 'mongodb' in '/Users/andyhall/Documents/Git/sgt/next-auth-example-project/node_modules/typeorm/platform'```
(sometimes `mongodb` is replaced by `mysql` or another DB provider from typeorm)

The changes are:
1. Add barebones `pages/api/[...nextauth].js` file with no providers and DATABASE_URL commented out
2. Set `next.config.js` to `module.exports = { target: "serverless" };` 
3. Clean env.local from unused values

When I run `yarn build` (also tested `npm run build`)  I get the typeorm error.

## How to reproduce ☕️

- clone next-auth-example
- `yarn`
- `echo 'module.exports = { target: "serverless" }' >next.config.js`
- set `pages/api/[...nextauth].js` to:
```
import NextAuth from "next-auth";
export default NextAuth({
    providers: [],
    secret: "test-secret",
    session: { jwt: true },
    jwt: {},
    pages: {},
    callbacks: {},
    events: {},
    debug: false,
});
```
- run `yarn build` 

## Screenshots / Logs 📽

Although not from next-auth-example, I built a repo with the same problem:
https://gitlab.com/supergoteam/next-auth-serverless-test/

## Environment 🖥

  System:
    OS: macOS 11.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 2.19 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 87.0
    Safari: 14.1

**Comment by balazsorban44** [comment]
Have you installed mongodb as a dependency?

**Comment by balazsorban44** [comment]
**UPDATE**: I tested this locally, I basically cloned our example repo, and added `target: "serverless"` to `next.config.js`, nothing else. I got the same errors as the OP here. I then did the same change (eliminated the `database` option from `node_modules/next-auth/dist/server/index.js`) as #1919, and this has seemed to fix the build issue. Now I don't know what is happening here, because in theory, it would mean that all of our serverless deployments (like when people deploy to Vercel) should error with this thing, right? I am not sure why this isn't happening, so I'll keep this issue open for a bit longer, maybe someone will have a good idea of what is happening.

**Comment by andyjaar** [comment]
Thanks for confirming this is an issue, I was down a bit of a rabbit-hole yesterday.
Have you got any changes I can make locally in installed package to avoid this error?

I also found that the error does not occur if I downgrade to Next 9.5.3. However, I'm then back with my original issue of "fetch is undefined" on production when using getSession() in API routes, which I believe is resolved in Next 10+.

**Comment by balazsorban44** [comment]
Since Next 9.4, it should not be necessary to polyfill `fetch` https://nextjs.org/blog/next-9-4#improved-built-in-fetch-support so I am not sure why you have this issue.

If you do not use that TypeORM adapter at all, I have a hacky solution for you though. As I mentioned in my previous comment.

Basically, you have to make sure that TypeORM is not automatically included in the `next-auth` package.

There is a package you can use to patch `next-auth` until `next-auth@4` comes out: https://www.npmjs.com/package/patch-package

I believe that @kripod have been using it in prod for a very similar usecase, maybe he could better explain what and how to do, but basically you will want to get rid of the following:

Remove this line:
https://github.com/nextauthjs/next-auth/blob/4b1271ba7537d7a507e33234ae9c3a14938bea26/src/server/index.js#L1

https://github.com/nextauthjs/next-auth/blob/4b1271ba7537d7a507e33234ae9c3a14938bea26/src/server/index.js#L108-L110

Rewrite the above to: `const adapter =  userOptions.adapter`

Hope this helps. I will have to verify why this happen when setting a serverless target... It doesn't seem like any Vercel deploy has this problem, so I am not entirely sure where this comes from.

**Comment by balazsorban44** [comment]
https://github.com/nextauthjs/next-auth/discussions/1611#discussioncomment-795110 might be relevant. apparently using target: serverless is not recommended anymore.

Found this https://github.com/vercel/next.js/issues/20487#issuecomment-753884085

**Comment by IgorDePaula** [comment]
This and another tricks not work for me.
