### ISSUE TITLE
Incorrect typing for credentials parameter in Credentials provider's `authorize` method

### ISSUE THREAD

**Issue by j0nas** [nextauthjs/next-auth#2080]
## Question 💬

First of all, thank you for a great library! I've never worked with auth in JS/TS that was so plug&play before! I migrated my Next.js project from Firebase Auth to NextAuth.js, and all my auth headaches were solved. I was able to greatly simpify auth logic in my app and delete many lines of code. :100: 

As for my issue: I suspect the typing for the `authorize` method for `Providers.Credentials` is wrong/bugged. For me, the `credentials` parameter is typed as `Record<never, string>`, which seems wrong:
![image](https://user-images.githubusercontent.com/6001131/119930299-7cc57800-bf7f-11eb-88f1-648b8c5c1ee4.png)

I'm on the latest published version at the time of writing, _3.23.2_, and Typescript _4.3.2_. This is the relevant part of my code:
```typescript 
  ...
  providers: [
    Providers.Credentials({
      name: "username and password",
      credentials: {
        email: { label: "E-mail", type: "email", placeholder: "example@user.com" },
        password: { label: "Password", type: "password", placeholder: "password" },
      },
      async authorize(credentials, req) { // `credentials` is typed as an empty object
        console.log("CREDS", credentials);

        const user = await prisma.user.findUnique({ where: { email: credentials.email } }); // TS2339: Property 'email' does not exist on type 'Record'.
        if (!user) {
          return null;
        }

        const correctPassword = await compare(credentials.password, user.passwordHash);
        if (!correctPassword) {
          return null;
        }

        return {
          id: user.id,
          email: user.email,
        };
      },
    }),
  ],
  ...
```

Here, the `console.log` statement logs the following:
```
CREDS [Object: null prototype] {
  redirect: 'false',
  email: 'test@test.com',
  password: 'test',
  csrfToken: 'fe99993acda0720143a1732e3d9f37faf77ea3451cfbe82306147bf7f393204b',
  callbackUrl: 'http://localhost:3000/login',
  json: 'true'
}
```

So the various properties are correctly set, but types report the object as empty.

This is the interface in question:
```
interface CredentialsConfig<C extends Record<string, CredentialInput> = {}>
  extends CommonProviderOptions {
  type: "credentials"
  credentials: C
  authorize(credentials: Record<keyof C, string>, req: NextApiRequest): Awaitable<User | null>
}
```

Now, this looks to be a bit above my Typescript skill level. `Record<keyof C, string>` looks to me like it should work, but it doesn't. I'd be happy to submit a PR if I knew what the fix was, but unfortunately that's not the case, and I'd love some input here. :slightly_smiling_face: 

I've simply added a `// @ts-ignore` above the `authorize` signature to work around the issue so far.

**Comment by balazsorban44** [comment]
So this is coming from here:

https://github.com/nextauthjs/next-auth/blob/f218697fd640713a44fcdacaff64a956686eb642/types/providers.d.ts#L114-L119

Apparently, the relation between `credentials` and `authorize` is not picked up correctly. Any idea how to improve it?

I don't have a good idea either, I'm sorry.

**Comment by wyozi** [comment]
I'm facing the issue. I'd guess that the default generic is the issue here (`= {}`). Because `CredentialsProvider` type doesn't provide a generic at all, the default parameter is always used.

With some changes I managed to make the type correctly inferred. See [playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcAKUIDcCWATYKAFWVQF44AiCAQwFcYALSuAHyuAFsacAbF9pQDGUYAQB2MHDV4BnSgCgFoSLDg5JhAGY0hqAMIROnCOIzZ8hAPJgpp2XADeCuOrwAuOLJhQNAcxc4cRpOYE9vX3EA1yQUT3NcAmJSBQBfJQB6ACoslyy4fVEJKRkHBMsoPIylDRhtXQMi4ElpXgBJcTAGJ0DeGgAjYF4AfnCff0DY4FGvcajArBk6abHI6LgwPr1GCF4kmYiJ9IVa+r0CppbSw3EtHD8AHn04UDrxPAcAJWAhaDwHw5RAA0FzEzRK7U6DAAfNDAq9mh8CkYTGZMIlrLYcPYejFSJ5hJcIfJAiIwVc5J59IF6ExoDgAF7AAAUZOKrVknm+vyg-wA1sBEBAtAUQYC-NCQaIAI6eGjiRAASjlCrSShU0HgU1B7NK5SSTxeIDeSO5fwBcz8IMK5IhHS6MFhcAozMCECx9niNFgrSeRI5Nzuj30sIUiud0J14IDpiDTzhynAmoQpCjFNk+sIJBQzqoNt1ckU6qTam1ACE6HwYB1M1AHBRnK5XPno6VPIaEe8vj9zeLrf6ZPaYdDXU2x3B3XZxJz0N6IX7bTHbvd43Cx+GyJGW+nAyuQ2qFAQhH1RHBftP4LWZxWqzX0RVZEoFFeAHTb4nMxtNtmtym48euHQsiEMEoSeF+AFjn0gy8J4ADkACi3B8HBQKBJBTZTPBdTGqh6HjqkaEYWANCyLIADufzgfhGHQUM8FoKRFF-HhGFjlhcBwSRZGUbycE0U2hH4UJY60jsvhMp4bL1pGEHjtJL5cDwvAANwCa4ClASBITAGpY7pKkioKEAA)

**Comment by balazsorban44** [comment]
Yeah. I gave it a try locally, and ended up propagating the generic as you did. I guess there is no better way, right?

**Comment by akomm** [comment]
@balazsorban44

There are a few issues with the typing.

1. `CredentialsConfig` is not instantiated on `CredentialsProvider`

Current:
```ts
export type CredentialsProvider = (
  options: Partial<CredentialsConfig>
) => CredentialsConfig
```
Should be:
```ts
export type CredentialsProvider = <C extends CredentialsConfig<Record<string, CredentialInput>>>(
  options: Partial<C>
) => CredentialsConfig
```
**reason, if you care, otherwise jump to 2.:**
- Generics for `type aliases` and `interfaces` need to be explicitly provided and are never inferred (you can work-around this). If a default is specified and you don't explicitly provide the generic, the default is always picked and does not change afterwards. Hence, the default `{}` is currently hard-coded for all cases.
- Generics for `methods` and `functions` only need to be provided explicitly, if typescript can not infer them via the input to the function and typescript does not allow to infer implicit any (strictness setting). You can pass down inferred method/function generics as type alias & interface generics, remove the need to provide them explicitly by user. But only when the generics can be auto-inferred on the function and method call... This is what is done in the above proposal.

This should already improve the typing, so that you don't get a type error and the types of fields in `authorize` are `string`. But the typing is not yet fully fixed, because the credential field-names are not validated, which leads to the next issue.

2. The problem here is, that `keyof C` in `CredentialsConfig` is based on the non-inferred `C` (constraint), which defines key type as `string`:
```ts
interface CredentialsConfig<C extends Record<string, CredentialInput>>
  extends CommonProviderOptions {
  type: "credentials"
  credentials: C
  authorize(credentials: Record<keyof C, string>, req: NextApiRequest): Awaitable<User | null>
}
export type CredentialsProvider = <C extends CredentialsConfig<Record<string, CredentialInput>>>(
  options: Partial<C>
) => CredentialsConfig

// need to change to this

interface CredentialsConfig<C extends Record<string, CredentialInput>, K extends keyof C>
  extends CommonProviderOptions {
  type: "credentials"
  credentials: C
  authorize(credentials: Record<K, string>, req: NextApiRequest): Awaitable<User | null>
}
export type CredentialsProvider = <C extends Record<string, CredentialInput>>(
  options: Partial<CredentialsConfig<C, keyof C>>
) => CredentialsConfig
```
In my case I did not need any defaults on `CredentialsConfig`, but if some other typing outside of my testing scope fails, because its not adopted, you might either make a similar fix there, or define some defaults on `CredentialsConfig`, like for example `K extends keyof C = keyof C`

**reason:**
The `keyof C` is an own instantiation, because of being inside an own type (`CredentialsConfig`). Its not instantiated after the C is passed down, but before. Hence the infered key type is `string` from `C`'s constraint in `CredentialsConfig.

**Comment by akomm** [comment]
Note:
```ts
export type AppProviders = Array<
  Provider | ReturnType<BuiltInProviders[keyof BuiltInProviders]>
>
```
Will remain a problem, because an array has uniform types. For it to work, more drastical changes might be needed, including inferring AppProviders as a tuple type. I'v just done changes that should mostly be BC

**Comment by balazsorban44** [comment]
I intend to stop supporting the `import Providers from "next-auth/providers"` import in v4, so it might not be a big issue.

Rather each provider should be imported explicitly like so:

`import Auth0Provider from "next-auth/providers/auth0"`

**Comment by akomm** [comment]
Unless I missunderstand something, it should not matter for this issue. Using the constructor functions works, because you can instantiate generics when you call the constructor. It does not matter from where you import them. But if you have type definition for possible providers in an array, the credentials typing can impossible be inferred, because array item types are uniform. You can't have two Credentials providers with different credentials, unless you hard-code 2 or 3 different instantion of the geneircs of CredentialsConfig in the library itself - the user can't do that though. 

So when building `Nextconfig`, providing `providers` without building them via factories won't give proper typing, but constructing with factories will work.
