### ISSUE TITLE
jwt callback doesn't get called on page transitions

### ISSUE THREAD

**Issue by HsnVahedi** [nextauthjs/next-auth#2106]
## Description 🐜

I'm using next-auth Credential provider to implement authentication between my next js application and a custom django backend. I want jwt callback to get called on page transitions (Because I use useSeesion on all of pages).

But unfortunately it only gets called on tab changes (when the user changes the tab on his/her browser) and on hard refreshes (when the user manually refreshes a page).

## How to reproduce ☕️

Define your jwt callback like this:

```
async jwt(token, user, account) {
    if (user && account) {
      // The user has just logged in.
      const decoded = jwt_decode(user.access)
      token.accessToken = user.access
      token.refreshToken = user.refresh
      token.accessTokenExpires = decoded.exp
      return token
    }
    if ((Date.now() + 15 * 1000) <= (token.accessTokenExpires * 1000)) {
      // The user has logged in before but the token.accessToken has not been expired.
      return token
    }
    // token.accessToken is expired and we need to get a new jwt using token.refreshToken.
    const newJwt = await refreshJwt(token.refreshToken)
    if (newJwt) {
      token.accessToken = newJwt
      const decoded = jwt_decode(newJwt)
      token.accessTokenExpires = decoded.exp
      return token
    }
    // token.accessToken and token.refreshToken are both expired.
    return {}
}

```

After the jwt (token.accessToken) expires, jwt callback won't get called. The use has to refresh the page or change browser's tabs in order to refresh the jwt token.
## Environment 🖥

npx: installed 1 in 9.14s

  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 771.81 MB / 7.26 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1

**Comment by balazsorban44** [comment]
Related #2071 although not the same. Your usecase is a bit different, and it is not a bug. I am guessing you use `Provider` to cache the session, and don't contact the backend on each `useSession` invocation. The `jwt` callback is only invoked when you contact the `/api/auth/session` endpoint. You have several options, one is to time the expiry of the client cache so it will contact the backend right before the acces token expires, or remove the caching at all. In any case, this is not a bug, but more of a shortcoming, since we don't support token rotation out of box just yet. Unfortunately more and more signs show that it is not trivial, as race conditions can arise which is a problem especially when a refresh token is only usable once.
