### ISSUE TITLE
Why isn't there relative `callbackUrl` support?

### ISSUE THREAD

**Issue by nicholaschiang** [nextauthjs/next-auth#2152]
## Question 💬

Why can't you use relative `callbackUrl` options by default? It seems like a very common feature.

To do so right now, you have to define a custom `redirect` callback (as mentioned [here](https://next-auth.js.org/getting-started/client#specifying-a-callbackurl)):

```typescript
callbacks: {
  redirect(url, baseUrl) {
    if (url.startsWith('/')) return url; // Relative path; allow them.
    if (url.startsWith(baseUrl)) return url; // Valid absolute path.
    return baseUrl; // Fallback to the `baseUrl`.
  },
}
```

**Comment by balazsorban44** [comment]
To be honest, I am not sure of the historical reasons, but we do document how to overcome this. Feel free to open a PR to address this, but I would like @iaincollins to give his opinion, there might be a good reason maybe.

He may be slow to respond though, and unfortunately, I cannot give satisfactory reasoning and since there is no bug reported here, I will close this for now, hope you don't mind.
