### ISSUE TITLE
Svelte Support

### ISSUE THREAD

**Issue by tuxsaurus** [nextauthjs/next-auth#2190]
I was trying to use next-auth on a Svelte app and I got this error

```shell
rollup-plugin-svelte: The following packages did not export their `package.json` file 
so we could not check the `svelte` field. 
If you had difficulties importing svelte components from a package, 
then please contact the author and ask them to export the package.json file.

- next-auth

```

Does next-auth has plans of supporting others frameworks rather than React?

**Comment by balazsorban44** [comment]
Hi support is in (very) long term plans. As a start, we refactored the current client-side code to be more React specific. (this is coming hopefully this sommer in v4. see the `next` branch if interested) 

For other frameworks to be compliant, they will need a backend where we can run our server-side logic.

Our backend code is a bit monolithic at the moment, and should be modularized/refactored first so we could better tailor it to frameworks.

 For clients, I don't think it would be very hard to support new ones, all our client-side code fits in a single file.

**Comment by brillout** [comment]
@tuxsaurus

There is a [demo of using NextAuth.js with Vite instead of Next.js](https://github.com/s-kris/vite-ssr-next-auth) which is good news for SvelteKit since SvelteKit uses Vite under the hood.

Only thing missing is view framework agnosticity https://github.com/nextauthjs/next-auth/issues/2294#issuecomment-889029103.
