### ISSUE TITLE
Return all data from Github through the profile

### ISSUE THREAD

**Issue by lucasantoniooficial** [nextauthjs/next-auth#2423]
### Question 💬

Within providers there is a function called profile().

When we give console.log(profile) it shows all the data that was requested from github, but when we return this profile the provider slashes and returns only name, email and image.

Is there any way to return this profile data?

### How to reproduce ☕️

Putting it this way in [...nextauth].js

```js
export default NextAuth({
    providers: [
        Providers.GitHub({
            clientId: process.env.GITHUB_ID,
            clientSecret: process.env.GITHUB_SECRET,
            scope: 'user',
            async profile(profile) {
               return {...profile};
            }
        })
    ]
})
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by sastraxi** [comment]
@balazsorban44 flagging to you as I think this is an interesting one -- it's likely common that users will want to grab some additional info from the oauth-provided profile that might not be of specific interest for authorization purposes, but would be critical for app functionality.

For example, we might need to know exactly which scopes were _accepted_ by the user, rather than just those we asked for. There may be other fields of interest as well.

What makes this problem interesting to me is that I'm unclear where the separation of concerns should be between Provider and Adapter: my knee-jerk reaction is to have some optional way to store the entire profile in e.g. a json / string field in the database for later use, or maybe allowing users to "extend" the object that is about to be stored in the database themselves.

@lucasantoniooficial, are you using a database adapter? If you can explain a bit more about your use case here, I'm sure we can point to the best plan-of-action for right now, and also what that might look like in the v4 release that the team is preparing now.

**Comment by balazsorban44** [comment]
I am assuming the issue here is that the `profile` information doesn't reach the front-end (eg `useSession`).

You can use the `session` and `jwt` callbacks to do that:
https://next-auth.js.org/configuration/callbacks#session-callback

This is a very common use case, and the reason we only return a subset is to provide a secure default. We might have documented it poorly or not visibly enough because I have probably answered this literally dozens of times. I am open to suggestions on how to rephrase the docs or add new sections explaining this better.

**Comment by sastraxi** [comment]
Does this also work if the user has opted not to use jwts? I see that the docs refer to a "User object (if using database sessions)" for the `session` callback, but no mention of the profile. It appears to me that currently there's no good way of accessing this additional profile information if you're depending on server-side sessions.

**Comment by balazsorban44** [comment]
You can extend the User in the database as well, but you have to make sure your database will handle that:

https://next-auth.js.org/tutorials/typeorm-custom-models

In the case of Prisma, you will have to migrate the schema.

**Comment by vahidtakro** [comment]
Can I add custom model on v4?
I am using Prisma provider, and I added new column to User table, called `username`, 
I want to get `{session.user.username}` how can I add `username` property?
now I get this error:


![Screenshot 2021-10-30 143726](https://user-images.githubusercontent.com/40500566/139530481-30ad2714-ac63-4827-ad7c-1060a7496cd8.jpg)
