### ISSUE TITLE
Support for Session Cookies

### ISSUE THREAD

**Issue by rikonor** [nextauthjs/next-auth#2534]
### Description 📓

Per [MDN/Cookies#define_the_lifetime_of_a_cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_the_lifetime_of_a_cookie):
1. A _Session Cookie_ will expire at the end of a session, e.g when the browser is closed. This is due to lacking an _Expires_ field in the cookie.
1. In contrast, a _Permanent Cookie_ has an Expires field and will persist across sessions (assuming it has not expired yet).

To the best of my understanding, NextAuth _always_ generates a _Permanent Cookie_ as it always adds an _Expires_ field to the cookie:

https://github.com/nextauthjs/next-auth/blob/0fae0c7a8eb224964e38da409ecb9ba0497e8c50/src/server/routes/callback.js#L273-L280

Assuming a Sign-In page that allows users to uncheck _Remember Me_, a _Session Cookie_ should be generated for the user instead of a _Permanent Cookie_. Is it possible to indicate to NextAuth that a _Session Cookie_ should be created?

### How to reproduce ☕️

N/A

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
This has been asked before, but no interest was shown from the community and got stale/closed: https://github.com/nextauthjs/next-auth/issues/974

`next-auth` rotates the session expiry, meaning whenever the user visits the `/api/auth/session` endpoint (eg. through `useSession()`), the lifetime of the cookie is reset, keeping it active. If you use `Provider` as well (which I think you should and it will actually be required in the upcoming release), the default is to only visit that endpoint once in the lifetime of the page (eg.: manual reload).

I am wondering, what would your use case be?

Setting a relatively short session expiry through `session.maxAge` would get you almost there. Am I wrong?

Ref:
https://next-auth.js.org/configuration/options#session
https://next-auth.js.org/getting-started/client#client-max-age

**Comment by rikonor** [comment]
Regarding the use-case, as mentioned in the stale issue as well - websites commonly provide a checkbox for "Remember Me", where if you uncheck the checkbox, after logging in you will have a _Session Cookie_, i.e a cookie with no _Expires_ field.

This means that after you close the browser, the cookie is deleted. A common case where this is desirable is when logging in from a public computer.

Setting a lower `maxAge` is not a true solution to this as even if you set, e.g `1 Hour`, it does not mean someone else can't re-open the browser after you leave and re-use your cookie.

The implementation for this is pretty simple, it just requires _not_ setting an _Expires_ field, but I'm not familiar enough with the codebase to propose the best way to do this.

Also, keep in mind I'm sure many folks can get by without this feature - but it does allow conforming to other common login systems, so IMO it's worth putting in.

**Comment by balazsorban44** [comment]
I did mention (https://github.com/nextauthjs/next-auth/issues/974#issuecomment-789305509) in the other issue as well, even if our session cookie is deleted when closing the browser, the OAuth provider (assuming that this is our most popular flow) won't log you out most probably, leaving your accounts logged in anyway.

I will leave this open for discussion. Not against the idea, I just don't think it is that useful.

**Comment by rikonor** [comment]
> even if our session cookie is deleted when closing the browser, the OAuth provider won't log you out, leaving your accounts logged in anyway

Sorry, I think I missed this point. Lets assume this flow:

1. Visit www.example.com and choose to log in with Google with "Remember Me" _unchecked_.
1. I input my Google credentials.
1. NextAuth provides me with a Session Cookie that gets deleted if I close the browser.
1. I close and re-open the browser and visit www.example.com again.
1. I choose to log in with Google again.
1. ?

Are you saying that at the last step of this flow, Google would just log me in again without requiring my credentials? If that's the case, then I agree that this feature has little value.

**Comment by balazsorban44** [comment]
Not even at step 6. You never logged out of your Google account, just go to Google and you are still logged in. There has to be an explicit action from the user's side to initiate a logout in my opinion. To log out of all the places, you will need to implement federated logout which I also mentioned in the other issue.

So yes, probably only the credentials provider would make sense here, and we actually advocate against using that, so I'm not sure we want to implement anything making that flow more appealing.

**Comment by rikonor** [comment]
Sounds good. We are in agreement 🙂 .

**Comment by kyle-mccarthy** [comment]
@balazsorban44 can this functionality be provided outside of a federated logout? I want to be able to provide different expire values based on the provider selected, specifically, I want one provider to use a session cookie and the others to persist the cookie after the browser session ends.

I don't think that federated logout is standard. Other sites/implementations of the OIDC client flow, provide the functionality to logout or expire session cookie without revoking the token from the IDP or performing a federated logout. Additionally, the ability to control the behavior of the cookie and/or session duration could help implement flows like adaptive or step-up authentication.

**Comment by kyle-mccarthy** [comment]
@balazsorban44 I would be interested in making a PR for this issue. Do you have any opinions about the implementation? I was thinking of making it so the sessions `maxAge` property can optionally accept a function that accepts contextual information about the authorization request and returns a numerical value to use for the `maxAge`.

**Comment by balazsorban44** [comment]
On  second thought, I'm not sure your usecase is generic enough to implement it in the core. What you could do is wrap `NextAuth` with the handler like so:

```js
export default function auth(req, res) {
  // do anything here
  NextAuth(req, res, options)
}
```

and add your provider specific changes. (check `req.query.nextauth`)

**Comment by ilijaNL** [comment]
Bump

I think to make an assumption that federated flow is most used so we don't add more functionality is not the correct way of thinking, this makes credentials provider also less secure since many closed system (think of bank) do not have any federated login which heavy rely on session closed mechanism.

**Comment by nilskaspersson** [comment]
I, too, want to allow users to not have persistent sessions, specifically for GDPR compliance. A "Remember me"-checkbox in a Credentials login flow would be sufficient cookie consent.

As proposed by the WP29:

> Persistent login cookies which store an authentication token across browser sessions are not
exempted under CRITERION B. This is an important distinction because the user may not be
immediately aware of the fact that closing the browser will not clear their authentication
settings. They may return to the website under the assumption that they are anonymous whilst
in fact they are still logged in to the service. The commonly seen method of using a checkbox
and a simple information note such as “remember me (uses cookies)” next to the submit form
would be an appropriate means of gaining consent therefore negating the need to apply an
exemption in this case.

[Source](https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf)

**Comment by balazsorban44** [comment]
They are not persistent though. You can set any expiry (can be as low as 1 sec 🤷‍♂️) and if the user does not interact with the site in that time frame, the cookie is removed by the browser.

**Comment by nilskaspersson** [comment]
A short expiry would not work, I can't have sessions be terminated unexpectedly. Even then, a 1 second expiry is technically "persistent" in a way a `Session` cookie is not, and would require collecting user consent.

I believe the previously quoted user expectation from the WP29 is justification enough.

**Comment by balazsorban44** [comment]
Sessions won't be terminated. We have session rotation implemented, which means if the user tries to access any page within the allowed time, the session expiry is renewed.

Otherwise, the session expires and the cookie is automatically deleted.

See my comment here: https://github.com/nextauthjs/next-auth/issues/2534#issuecomment-988110940

That would actually be worse, as if the Chrome process isn't killed forcefully, the session will *never* expire, which is much worse than a low expiry date.

**Comment by PhilipHassialis** [comment]
As an aside, is it possible to have JWT authentication w/o any kind of cookies whatsoever? Is it possible for next-auth to simply act as a middleware where it will return the user to a configurable (e.g. custom 403 or a login) page and as soon as the user is authenticated, return us to a page that upon navigation from it or when using a call to a /api backend, be automatically checked and verified by next-auth, perhaps get a new JTW re-issued and so on in an as-possible transparent manner? The idea is not to have anything left on the browser, not even a cookie history.   

The idea is not to use "sessions" at all but instead have every interaction with the next runtime be middleware-wise authenticated first by next-auth before the user can navigate to the protected pages, much like you would always send the JWT in the headers of an API call so that the API would know that a verified user is attempting to reach the endpoint.

**Comment by JensMou** [comment]
> They are not persistent though. You can set any expiry/maxAge (can be as low as 1 sec 🤷‍♂️) and if the user does not interact with the site in that time frame, the cookie is removed by the browser.
> 
> In my experience, even `Session` cookies aren't removed by browsers like Chrome upon closing the window. I have to manually kill the process for it to work.

Hello, 

I'm using an impersonation feature, where I need to remove the permanent cookies and sign in again, when you want to stop/start the impersonation. How can this be done without the controls of the cookies (and not removing them manually with javascript)? I only want to set the expiry (to -1 or whatever) in this case and not generally on the page. Maybe I missed something here.

**Comment by aleehedl** [comment]
I also think this feature is important and shouldn't be very difficult to implement for someone with some knowledge of the code base. Conceptually, the implementation only requires that we have some setting (like `maxAge: false`) and the session expiration is never set to a Date value but instead to literal value `Session`. Or am I missing something?

Also, I find that this is useful not only for _credentials_ method but also _OAuth_, because they often have the "remember me" option available as well.

For instance, when logging into Gitlab you have the "remember me" option also for when using Google login etc.

**Comment by MichaelWheldon** [comment]
Just +1 to all of this. This is the only critical feature of nextAuth I think is missing.

**Comment by naturom** [comment]
I think its a critical feature as well maxAge: false. I implemented an OAuth (with permissions control), if the oauth no longer allow an user to login, currently user still able to login as the next auth session is not expired yet even when browser is reopen again. Setting the session cookie would be very helpful in such case.

**Comment by Crane101** [comment]
Might be possible to leverage NextJS middleware to achieve the desired result here? Something like this:

```
export const middleware = (request: NextRequest) => {
  const response = NextResponse.next();

  const authCookie = request.cookies.getWithOptions(
    config.nextAuthCookieName
  );

  if (authCookie.value) {

    response.cookies.set(
      config.nextAuthCookieName,
      authCookie.value,
      {
        ...authCookie.options,
        expires: undefined,
        maxAge: undefined,
        httpOnly: true,
        secure:
          config.nextAuthCookieName.startsWith('__Secure'),
      }
    );
  }

  return response;
};

```

This is only a rough POC, but it seems to work as expected when I tried it out.
Feels like it might be a terrible idea though 🙂

**Comment by tsmithdk** [comment]
We really need a fix for this... 

Setting maxAge to a few seconds gets us halfway there however if you just refresh the browser you need to log in again. That is why we need an option to change the session-token cookie to a session only cookie. The workaround now with setting maxAge is troublesome because we have to request the provider more than necessary and it is not a 100% fix from a security aspect. 

Please give an option to set maxAge to false or something in order to change the session-token cookie to a session only cookie.
