### ISSUE TITLE
[V4 Beta][Prisma] Installing latest `@next-auth/prisma-adapter@next` force-downgrades to bad next-auth

### ISSUE THREAD

**Issue by TheoBr** [nextauthjs/next-auth#2675]
### Description 🐜

Installing the correct prisma-adapter for V4 next-auth (`v0.5.2-next.5`) forces `next-auth` to resolve to `v4.0.0`, which is a bad package.

Fix for me:
```bash
npm install next-auth@beta --save-exact
npm install @next-auth/prisma-adapter@next --force
```

### Is this a bug in your own project?

No

### How to reproduce ☕️

```bash
npx create-next-app --ts
npm install next-auth@beta # Good at this point
npm install @next-auth/prisma-adapter@next # installs correct prisma adapter, peer dep forces next-auth to v4.0.0 (bad package)
```

### Environment 🖥

Modern MacOS + node 16 LTS

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This happens because of a bad release I accidentally made a while back..

This release https://www.npmjs.com/package/next-auth/v/4.0.0
is wrong!

Unfortunately, I cannot seem to deprecate or delete it...

Current solution is to forcefully install `4.0.0-beta.1` AFTER you installed the adapter.

Makenaure that the next-auth version doesn't have a `^`

cc @ndom91 we should add some docs to mention this in the migration guide

**Comment by balazsorban44** [comment]
I address this here https://github.com/nextauthjs/docs/pull/13
