### ISSUE TITLE
credentials: 'include' in the getSession call so that it can be used on domain and any subdomain.

### ISSUE THREAD

**Issue by itzmukeshy7** [nextauthjs/next-auth#2718]
### Description 📓

I am using NextAuth for multiple subdomain and main domain, all auth working fine except that not able to get session on any other subdomain except the one I am using to set Cookie.

On other subdomains it's not sending the cookies with the request.

Other API endpoints are working fine after adding withCredentials: true for axios.

But not sure if we have any option to do so in NextAuth.

### How to reproduce ☕️

Same as description.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by balazsorban44** [comment]
This might help https://next-auth.js.org/configuration/options#cookies

**Comment by itzmukeshy7** [comment]
@balazsorban44 using this option and I can access the cookies on other sub domains but the getSession request is not including the cookies for other sub domain which are not part of auth flow.

![image](https://user-images.githubusercontent.com/5780768/132872048-206a88bc-a6e1-445a-a76f-1ba63f807dd6.png)

**Comment by balazsorban44** [comment]
`getSession` is basically a fetch call right now.

Could you see if you recreate it of your own, you can control it better?

https://github.com/nextauthjs/next-auth/blob/main/src/client/index.js#L161-L167

Generally I want us stop using that method server-side, since fetch calls to API routes is not really recommended. See #1535.

I intend to do the necessary rewrite when v4 lands in stable.
