### ISSUE TITLE
Ability to extend provider's profile with additional keys

### ISSUE THREAD

**Issue by kleyu** [nextauthjs/next-auth#287]
**Summary of proposed feature**
Ability to extend provider's profile with additional keys.

**Purpose of proposed feature**
Some auth providers provide more profile fields than just name, email, image. It would be nice to be able use that and add custom fields to the profile object, so it is available inside `session.user`.

**Detail about proposed feature**
I managed to hack something that's working, not sure if it's ideal solution.

0. Add some fields that you'd like to have available inside `session.user` inside `options.profile`. For example:
```js
 profile: (profile) => ({
        id: profile.id,
        name: profile.display_name,
        email: profile.email,
        image: profile.images[0].url,
        country: profile.country,
        href: profile.href
      }),
```

1. https://github.com/iaincollins/next-auth/blob/173ce2aae64ab148aa912ed79499bd8746e75935/src/server/lib/oauth/callback.js#L106
Add `...profile` spread to this object.

2. Now, when hooking up to `signin` callback, we can observe those fields added to `profile`. They're also available inside `token.user` object which can be logged when providing custom `session` callback. 

3. Set custom `session` callback, example: 
```js
session: async (session, token) => {
      const sessionWithFullProfile = { ...session, user: { ...token.user } };
      return Promise.resolve(sessionWithFullProfile);
    },
```

**Potential problems**
I can't think of any new vulnerabilities.

**Describe any alternatives you've considered**
Best way would be to not mess with custom callbacks and just provide the fields we want to add in `options.profile`.

*Please indicate if you are willing and able to help implement the proposed feature.*
Yes, I can help.

**Comment by iaincollins** [comment]
Thanks for raising this! Agree, we should change this behaviour!

RE: `next-auth/src/server/lib/oauth/callback.js`

Good catch! It seems like should just be the profile object that is returned from the `profile()` function on a provider.

I think, looking at it in retrospect, that it's a mistake that it's not. It's supposed to allow you to return additional properties from a `profile()` function in a provider; I probably hard coded it before the rest of the functionality was well defined and overlooked coming back to it.
  
Appreciate you digging in to work out what was going on and highlighting the issue!

It seems like the only consideration is the normalisation of the email address to lowercase - i.e. if there is an email address property, it should be lowercased - and if we need to move that logic somewhere else, maybe [~ line 40 of `next-auth/src/server/routes/callback.js`](https://github.com/iaincollins/next-auth/blob/173ce2aae64ab148aa912ed79499bd8746e75935/src/server/routes/callback.js#L40)?

I [left a comment on the sign up page](https://github.com/iaincollins/next-auth/blob/173ce2aae64ab148aa912ed79499bd8746e75935/src/server/routes/signin.js#L49) on why I lower case it, even though it's technically against the RFC 2821 - basically this is not how email address work in practice and nobody wants to accidentally end up with two email accounts because they typed in 'joe@example.com' instead of `joe@example.com`.

**Comment by iaincollins** [comment]
Ooh I just thought of a consideration here, it does have implications for type safety.

Some work is going on to add types, and if we support returning arbitrary objects here, that complicates things a bit going forward.

I think I actually need to visually map out how this works because I haven't looked at the code in about a week and I'm already starting to be fuzzy about it! I'll take that as an action so we can follow up on this, before I rush in and change something.

This seems reasonable request but I have a hunch there is a reason why I we already provide the full, raw profile as a separate object (here and in the `signin()` callback as the third argument); I just can't remember if it's a *good* reason…
