### ISSUE TITLE
Azure AD in Beta 4.0.0 Image Link Brokem

### ISSUE THREAD

**Issue by jsabety** [nextauthjs/next-auth#2936]
### Description 🐜

There is a broken image link above the login with Azure AD button

### Is this a bug in your own project?

No

### How to reproduce ☕️

Add Azure AD as a provider to an app

### Screenshots / Logs 📽

![image](https://user-images.githubusercontent.com/2666054/136928140-03aa8faf-62da-49b6-810a-135a88078201.png)

### Environment 🖥

Localhost:3000

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by jsabety** [comment]
Version 4 Beta...  

When I tried, the callback/authorization seemed to fail...I can't remember the exact details anymore...  didn't try more than a day before giving up and going the custom provider route...

**Comment by balazsorban44** [comment]
I think I misunderstood. The broken image you are seeing comes from an unrelated bug, fixed in #2916. Will be out in the next beta release. No ETA yet.

If you don't want to see the signin page, just do `signIn("azure-ad")`

https://next-auth.js.org/getting-started/client#starts-google-oauth-sign-in-flow-when-clicked

The try signing in with a different account sounds like an unrelated issue and would need a reproduction to be able help more.
