### ISSUE TITLE
V4 - Loading state in useSession()

### ISSUE THREAD

**Issue by arminhupka** [nextauthjs/next-auth#3310]
### Question 💬

I'm following documentation for v4 and I noticed information that we can pass session to SessionProvider and this will remove the loading states during using useState. I'm doing something wrong or what? 

**_app.js**
```
import {SessionProvider} from "next-auth/react";

const App = ({Component, pageProps: {session, ...pageProps}}) => {
    return (
        <SessionProvider>
            <Component {...pageProps}/>
        </SessionProvider>
    )
}

export default App
```

**index.js**
```
import {useSession, signIn, signOut} from "next-auth/react";

const HomePage = () => {

    const { data: session, status } = useSession()
    console.log(status)


    if (status === "authenticated") {
        return (
            <>
                <p>Signed in as {session.user.email}</p>
                <button onClick={signOut}>sign out</button>
            </>
        )
    }

    return <button onClick={signIn}>Sign in</button>
}

export default HomePage

```

### How to reproduce ☕️

1. Create new project
2. Set basic next-auth configuration
3. Wrap _<Component/>_ in __app.js_ by SessionProvider and pass pageProps.session to session.
4. Initial useSession() hook and check loading state

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Yes. Missing the actual fetching of the session. Currently, you can only skip the loading state if the session has been passed from `getServerSiderProps` for example.

There is an alternative, when using `useSession({ required: true })`:

https://next-auth.js.org/getting-started/client#require-session


React Server Components (RSC) will make this a bit better since certain components will be rendered on the server already.
