### ISSUE TITLE
Invalid JWT signature

### ISSUE THREAD

**Issue by YoussefAK** [nextauthjs/next-auth#3366]
### Description 🐜

Since version 4, the JWT callback does not allow to add arguments to the jwt token anymore. They seem to be skipped, and the resulting token lacks payload.  

### Is this a bug in your own project?

No

### How to reproduce ☕️

I tried on the official example. I logged with google, and the jwt was missing payload (same thing for my project, regardless of the provider). Please check the attached screenshots. 

### Screenshots / Logs 📽

<img width="1811" alt="Screenshot 2021-12-05 at 15 05 54" src="https://user-images.githubusercontent.com/12718174/144750086-8d9804ce-7f02-4221-b188-95801b8d0b3e.png">
<img width="1340" alt="Screenshot 2021-12-05 at 15 06 07" src="https://user-images.githubusercontent.com/12718174/144750088-165a31ea-b3d5-44e1-802c-50a636497b32.png">

### Environment 🖥

You can check the official demo (https://next-auth-example.vercel.app/).

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://next-auth.js.org/configuration/options#jwt

**Comment by lionelrudaz** [comment]
@YoussefAK have you been able to solve your issue? I run into the same situation. I don't think it's related to storing additional data in your token, as removing it on my side didn't help.

@balazsorban44 can you provide more help than a link on the documentation?

For what it's worth, my code was working on the v3. Now I'm upgrading to v4, and after documenting some errors from the docs, I'm stucked because of this issue. I really have no clue how to solved this. I don't think it's a solution to code my own encryption and decryption functions.

Let me know if you need more information.

**Comment by balazsorban44** [comment]
This was a bug report (I think?) with no reproduction. Hard to say anything. If you have a similar issue, I suggest you open a different bug report with an attached repo/minimal reproduction.

The answer is in the docs though, the JWT is encrypted by default (JWE) so jwt.io cannot and should be able to decode it. That's kind of the point.

**Comment by lionelrudaz** [comment]
Thanks for replying @balazsorban44. That helps me a lot.

I'm using the JWT token to authenticate my user against my API that's not on the same app (it's a Rails API app, this is where the database for users is stored).

So the idea (and it was working in v3) was to send the JWT token in raw mode in my API calls, then my Rails API decodes the JWT to check who's the user and retrieves the appropriate data. 

That leaves me with only the option to encode and decode the JWT token by myself, right?

**Comment by balazsorban44** [comment]
We started recommending to not use the `next-auth` JWT outside of the app (reading token values are fully supported by API routes, data fetching methods). Your backend should return an access token that we can store, and you send with your API requests to your backend which it can encode/decode.

**Comment by lionelrudaz** [comment]
So let me paraphrase to see if I get it correctly:

- In the signIn callback of NextAuth, I should request a token to my Rails API
- My Rails API generates a unique token and sends it back to NextAuth
- With NextAuth, I should record it in the local JWT token, so that I can use it later
- All my calls to the Rails API should include the new token

My questions:

- How is that safer than sharing the token between client and server?
- Should I create 1 token per user or 1 token per session? I've the feeling I'll recreate sessions and reinvent the wheel
- What should be the policy to renew the token on my Rails API? What should I do if it expires? How will I know from the client that a new token should be requested? That should be done from the API I assume.

Thanks again for your help.

**Comment by balazsorban44** [comment]
"In the signIn callback of NextAuth": You probably want this in the `authorize` callback.

Questions:

1. You can proxy requests through the server and never share the token with the client if that's what you want, just use the `jwt` and `session` callbacks, and the `getToken` method according to the docs.
2. 1 token per user session. Correct, you are reinventing the wheel :) That's why we generally recommend OAuth. Creating your own auth provider is a whole lot of work
3. We don't have automatic token rotation, how you keep your tokens alive is up to you. If you want to go that way, you can read up on `refresh_token` in OAuth.

**Comment by lionelrudaz** [comment]
Thanks for your answer @balazsorban44. What I need to do is to send to the API that the call is made by userId 1234, so that the API retrieves only data related to that user. 

My original idea was to use JWT to send this info, so that on the server I could decode it, know which user it is and apply the query correctly.

I can of course create a proxy through an API function in my Next App, that would then send the user ID in the query params or in a custom header. But if I want to open the API one day, that doesn't seem like a good option.

Let me know if you need more information.

**Comment by jgwiazdowski** [comment]
I end up with a same problem yesterday - empty payload - initially I was thinking it's because there is something wrong my logic in CredentialsProvider authorize function, then I tried EmailProvider and other providers as well - payload was always empty

to fix it I end up with writing my own custom encode() decode() functions, which is you ask me seems to be simply better, because you can put anything you want into your payload

**Comment by lionelrudaz** [comment]
> You probably want this in the authorize callback.

Sorry for my late reaction. This callback is not documented in the guide. Is it planned to add it to https://next-auth.js.org/configuration/callbacks @balazsorban44 ?

> to fix it I end up with writing my own custom encode() decode() functions, which is you ask me seems to be simply better, because you can put anything you want into your payload

Well, yes and no. I had to find a good package to encode the JWT, then learn how to use Buffers to decode. Perhaps this could be worth documenting as well.

Let me know if I can be of any help.

**Comment by balazsorban44** [comment]
authorize callback is here:  https://next-auth.js.org/providers/credentials#example

We won't encourage custom auth solutions and probably won't document it better either.

**Comment by drusellers** [comment]
Just ran into this same issue. 

The Session Cookie "LOOKS" like a traditional JWT, with the 3 `.`s - threw me for a good long loop trying to figure out that the bits at the end are not a signature but an encrypted cookie. This could be documented more clearly. 

I am also looking to pass the cookie to down stream API calls. The idea for me was to authenticate with Google. Then stuff some data into the JWT, and then pass that along in my direct API calls. Having to proxy those through my web feels like an unnecessary step.

Is there any way to remove the encryption on the JWT session cookie, so I can have a plain JWT?
