### ISSUE TITLE
Session revalidation on refocus causes unwanted component rerenders

### ISSUE THREAD

**Issue by filipditrich** [nextauthjs/next-auth#3405]
### Description 🐜

With the removal of `clientMaxAge` and `keepAlive` in favor of `refetchInterval`, every time a tab is switched, the session gets revalidated, thus updating a session state in `SessionProvider` which then causes to rerender all components using `useSession`.

Is it possible to disable this "revalidation" upon window refocusing?
Thanks in advance.

### Is this a bug in your own project?

No

### How to reproduce ☕️

```tsx
<SessionProvider
session={pageProps.session}
// re-validate stale session every hour
refetchInterval={60 * 60}
>
  <Component /> {/* <-- on tab switch this component gets rerendered, it "resets" its states */}
</SessionProvider>
```

### Screenshots / Logs 📽

<img width="600" alt="Screenshot 2021-12-08 at 7 21 49 PM" src="https://user-images.githubusercontent.com/35503864/145262648-b11062ac-6097-4447-9370-7e7cbd6020a5.png">

### Environment 🖥

 System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 8.40 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Firefox Developer Edition: 96.0
    Safari: 15.1
  npmPackages:
    next: 11.1.2 => 11.1.2 
    next-auth: 4.0.5 => 4.0.5 
    react: 17.0.2 => 17.0.2 

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This was removed on purpose to simplify our code. Probably ok to add this one back though.

Just need to add a conditional here:

https://github.com/nextauthjs/next-auth/blob/30a0fc6bc0246b30eb03c19b8a0ceb6c040c1b2e/src/react/index.tsx#L381-L391

**Comment by filipditrich** [comment]
> I wonder why this is a problem for you though? Especially if you set up refetch on interval, that extra to have an up-to-date state when the user refocuses shouldn't matter that much IMO.

Yes the up-to-date state on refocus is useful, but in my case it causes unwanted rerendering of components where I access the session data. For example it resets table pagination to initial value, which is kind of inconvenient (after few hours of debugging I came to conclusion that it is indeed caused by the session state update).

I'd be glad if you considered this a feature toward next release.
Would be much appreciated. Thanks

**Comment by balazsorban44** [comment]
Not really sure why session updates would affect table pagination :thinking:

But I as said I am OK with adding this feature back. Feel free to open a PR

**Comment by nodeicode** [comment]
the session update on refocus is totally fine but the issue with my app is that every time we do that session refetch its calling a database query and in a production scenario I'm not sure if its gonna scale well 🤔

**Comment by balazsorban44** [comment]
FWIW, you should not  make database calls on every session check.

**Comment by GGAlanSmithee** [comment]
I am in a similar situation where I have a multitenant SPA that needs to:

1. When the user enters a route like `/something/[id]/something`, register a websocket listening for updates for {id}
2. When the user leaves the above route, unregister the websocket
3. When the user enters the same route, but with a different id, register a websocket for that {id}
4. If a user has multiple tabs open with different {id}s, listen to them all

This requires the user to be authorized, so, the way I did this was to:

```tsx
useEffect(() => {
  if (!socket || !session) {
    return
  }

  socket.emit(topic, { id, user: session.user })

  return () => {
    socket.emit(topic, { id, user: session.user })
  }
}, [socket, session, id])
```

I remember this used to work fine, but it does not, because as soon as tab 1 loses focus, it stops recieving updates. I also had another case with the same behaviour, but I was able to easily refactor that. The above case, is IMO legit though, and not unreasonable. Ofcourse, I could remodel how my app works, but it's quite complex and I would rather not. If you have any pointers, I'd much appriciate it @balazsorban44
