### ISSUE TITLE
Fetching the session when there are no cookies present

### ISSUE THREAD

**Issue by pksu** [nextauthjs/next-auth#3481]
### Question 💬

I'm currently using Next-auth without SSR (but with session provider & useSession) and some of the pages served do not require authentication. Everything works great except the fact that Next-auth calls `/api/auth/session` even when there are no next-auth related cookies present and we actually don't require sign-in. 

Is there a way to keep using session provider but avoid fetching session if user has never even logged in?

### How to reproduce ☕️

Deploy new app using SessionProvider and check network calls

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
This is by design. The session is kept in an HttpOnly cookie. There is no way to check if that cookie exists from the client-side. If the user is not logged in though, the response will be extremely fast, as there is almost no work done on the backend.

This should be very low on your list of performance concerns.
