### ISSUE TITLE
NextAuth Ionic 

### ISSUE THREAD

**Issue by axk2** [nextauthjs/next-auth#3539]
### Question 💬

If i use ionic with next js, would it work with NextAuth? 

### How to reproduce ☕️

No issue

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Not currently. If I guess right what you are after, #2294 might help in the future.

**Comment by mlynch** [comment]
What's the issue? Generally you'd redirect to a custom URL scheme with the token, which should be possible. I don't think this is the same situation as #2294 as Ionic isn't a "framework" in that sense, it's primarily a UI library being used with Next.js

**Comment by balazsorban44** [comment]
I thought it was referring to [Ionic Framework: Cross-Platform Mobile App Development](https://ionicframework.com/) :thinking:

**Comment by jake-amicus** [comment]
@balazsorban44 Ionic is both a UI library and a framework for building cross-platform hybrid (web native) mobile apps (with Capacitor).  The UI library is primarily used to provide native mobile UX, but it's built and runs like any other web app.

Using Ionic in a NextJS project works just fine, albeit with SSR disabled, and using NextAuth would also work since it would still be leveraging at least the initial page load from the server. 

The question arises when the app is built/bundled as a mobile app, at which point the client Javascipt is just static bundles and no longer uses `pages/_app.tsx` to hydrate the application on the page load. If the SessionProvider is limited to a server-side page then the pre-bundled Ionic client may not have access to it.

**Comment by 5hee75** [comment]
@balazsorban44 Ionic is both a UI library and a framework for building cross-platform hybrid (web native) mobile apps (with Capacitor). The UI library is primarily used to provide native mobile UX, but it's built and runs like any other web app.

Using Ionic in a NextJS project works just fine, albeit with SSR disabled, and using NextAuth would also work since it would still be leveraging at least the initial page load from the server.

The question arises when the app is built/bundled as a mobile app, at which point the client Javascipt is just static bundles and no longer uses pages/_app.tsx to hydrate the application on the page load. If the SessionProvider is limited to a server-side page then the pre-bundled Ionic client may not have access to it.
