### ISSUE TITLE
MikroOrm minimum Node version (util/types)

### ISSUE THREAD

**Issue by ryankauk** [nextauthjs/next-auth#3816]
I know the mikro orm adapter is new. (Thanks so much for it btw).

Just started trying it out and got an error 

```
Error: Cannot find module 'util/types'
```

I was on v14.16.1 upgraded to v16.13.1 and it worked. Didn't look into it exactly when node split the modules apart but might be good to just give warning for it. Also just wanted to post it here in case anyone else tries it.

**Comment by ndom91** [comment]
`nextauthjs/next-auth` has been migrated to a monorepository. The adapters code can now be found there under `packages/adapter-*`. Thanks for your interest in the project!

**Comment by boredland** [comment]
oh, so I guess I'd need to create the PR there again

**Comment by ndom91** [comment]
Yeah sorry PR's are obviously a bit more difficult to migrate, if you can reopen it on the main repo that'd be a huge help :pray: 

We've just begun the migration recently, so we're hoping to circle back around to this in a bit once we have all the CI and repo organisation stuff in place in the main repo if people aren't proactive about their PRs (like you were :fire:) in order to help them along.

**Comment by boredland** [comment]
Ya, no worries. I'll wait a bit after mikro-orm v5 got released.

**Comment by balazsorban44** [comment]
Hi @boredland, your PR has been merged and we'll soon be released (#3875) Does this mean that this issue will be resolved then?

**Comment by boredland** [comment]
No, this issue is about me using node16 features, the PR was about the Mikro-ORM version. Will recreate the one fixing this against the monorepo now.
