### ISSUE TITLE
MongoDb adapter: add an option to specify the database instead of relying on the server default database

### ISSUE THREAD

**Issue by patricklafrance** [nextauthjs/next-auth#4118]
### Description 📓

With the Mongo Db adapter, the collections seems to be created in the server default database. Would be useful if the name of the  database to use could be provided, similar to the collection names.

![image](https://user-images.githubusercontent.com/794579/156796087-61e81484-22bd-4e69-b5b2-37ed1e41b9d3.png)

### How to reproduce ☕️

- Create a new Mongo DB server
- Use this new server connection for the adapter
- Log in to your app with a new user

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by ThangHuuVu** [comment]
I think this can be controlled in the connection string. Here is the code we use to create a MongoDB instance to connect:
https://github.com/nextauthjs/next-auth/blob/b0935c7b4a8a7c6dc8befe42764ca558bbae9626/packages/adapter-mongodb/src/index.ts#L76

The MongoClient documentation: https://mongodb.github.io/node-mongodb-native/4.4/classes/MongoClient.html#db
> Optional dbName: string The name of the database we want to use. If not provided, use database name from connection string.

**Comment by balazsorban44** [comment]
@ThangHuuVu is correct, just add it as part of the connection string :+1:

**Comment by FarazFKhan** [comment]
Rather than changing the packages file directly, we can also feed the database name inside the the "MongoDBAdapterOptions" object.

See the 2 pictures attached. Pic 2 shows how to add the database name.

![pic 1](https://github.com/nextauthjs/next-auth/assets/67421013/63306f56-3099-48e4-97b3-4a01ef262281)
![pic2](https://github.com/nextauthjs/next-auth/assets/67421013/61c7c18d-98bf-46d1-ac5d-ef09bd791182)
