### ISSUE TITLE
newUser = true for re-linked account?

### ISSUE THREAD

**Issue by bscaspar** [nextauthjs/next-auth#416]
If a user were to log in with an oauth provider, and then sometime after revoke site/app access through that oauth provider, and then later re-authorize access, would `newUser = true` for that most recent login?

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Great question!

### With a database

If you are using a database, the value should be `newUser: true` on first login and `newUser: false` on subsequent sign in attempts. This should be consistent even if they have revoked access vi their oAuth provider, as the User database is used as the source of truth for "if they exist already".

### Without a database

If you are not using a database for Users the behaviour is not actually defined. Typically we can't know if it's their first sign in or if they have previously signed in (this is not necessarily true for every provider, but is the case for the vast majority - there isn't a reliable way to track it without using a database to store users).

I think actually the current behaviour should be reviewed because I think it might unintentionally return `undefined` in that flow, at least some of the time and that is not documented anywhere.

### Considerations

This value is also unknown for a user if using the 'Credentials' provider as users who sign in with the 'Credentials' provider are not persisted in the User database, so we can't now if they have signed in before.

Given there is an option to redirect users on first sign in if this value is `true`, it seems that not setting the value to `true` unless a database is being used to store user data is the best approach in this model.

We could optionally not return it, or return false or some other value. Feedback welcome on expected behaviour.

**Comment by iaincollins** [comment]
This behaviour
