### ISSUE TITLE
Latest tag on NPM points to v3

### ISSUE THREAD

**Issue by lukahartwig** [nextauthjs/next-auth#4476]
### Environment

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 12.40 GB / 15.60 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v18.0.0/bin/yarn
    npm: 8.7.0 - ~/www/test/node_modules/.bin/npm
  Browsers:
    Chrome: 98.0.4758.80
  npmPackages:
    next: ^12.1.5 => 12.1.5 
    next-auth: ^3.29.3 => 3.29.3 
    react: ^18.0.0 => 18.0.0
```

### Reproduction URL

https://www.npmjs.com/package/next-auth

### Describe the issue

A few hours ago there was a new version published from the v3 branch which has set the `latest` tag on npm to `3.29.3`. I assume this should point to v4 since that's what the documentation is showing by default.

### How to reproduce

```
npm install next-auth
```

### Expected behavior

Should install the latest 4.x version

**Comment by nated0g** [comment]
Yeah, my first experience with next-auth has been very confusing today as a result of this.

**Comment by balazsorban44** [comment]
So this should be fixed now, running `npm i next-auth@latest` will install v4 again.

A small history here:

v3 is unfortunately still used a lot (based on npm stats) and we recently pushed a small security patch and I did not realize it was tagged with `latest`.

We will have to do a better job at helping people [to migrate](https://next-auth.js.org/getting-started/upgrade-v4), because v3 has been considered unmaintained for a while now.

If anyone has suggestions on how we can make moving to v4 a better experience, please let us know!
