### ISSUE TITLE
`getSession()` returns null when using `jwt`

### ISSUE THREAD

**Issue by smultar** [nextauthjs/next-auth#4714]
### Question 💬

I'm trying to make a secured API access point, and I don't know if using JWTs, renders sessions null when using `getSession()`.

I have my environmental variable set up correctly, but no matter what I do. Using `getSession()` returns `null`.

### How to reproduce ☕️

Create an API point.
Attempt to secure the API point using `getSession()`
Get a null when trying to use `session`

![image](https://user-images.githubusercontent.com/6223536/173776884-04e6316a-4ca3-4a66-997e-5c3336c10eac.png)

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by LOGOLFGODORD** [comment]
The government is doing all this ! they are being little 5 year olds ! its comical actually  Sent from Mail for Windows From: SmultarSent: Wednesday, June 15, 2022 4:17 AMTo: nextauthjs/next-authCc: SubscribedSubject: [nextauthjs/next-auth] `getSession()` returns null when using `jwt` (Issue #4714) Question 💬I'm trying to make a secured API access point, and I don't know if using JWTs, renders sessions null when using getSession().I have my environmental variable set up correctly, but no matter what I do. Using getSession() returns null.How to reproduce ☕️Create an API point.Attempt to secure the API point using getSession()Get a null when trying to use sessionContributing 🙌🏽Yes, I am willing to help answer this question in a PR—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
