### ISSUE TITLE
Problems with releases for adapter packages

### ISSUE THREAD

**Issue by zenflow** [nextauthjs/next-auth#4738]
Sorry for breaking the template format. I couldn't find any template that really fits.

This isn't exactly a bug with any of the packages, but I wanted to point out the problems with releases for adapter packages.

### Describe the issue

Recent releases of adapter packages on npm don't seem to be in GitHub releases (or Git tagged) or in their respective CHANGELOG files.

Taking `@next-auth/sequelize-adapter` for example:

1. [Latest release on npm is v1.0.4](https://www.npmjs.com/package/@next-auth/sequelize-adapter?activeTab=versions) but it doesn't have a [GitHub release (tag)](https://github.com/nextauthjs/next-auth/releases) and is not in [the changelog](https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-sequelize/CHANGELOG.md).
2. Latest release (tag) on GitHub is v1.0.3 but it is not in the changelog. None of the patch releases since v1.0.1 are in the changelog.

**Comment by balazsorban44** [comment]
Hi, we currently have some issues, due to how GitHub Actions cannot push commits/release notes to protected branches. This means some manual labor on my side every time we have a release.

See a failed action run here: https://github.com/nextauthjs/next-auth/runs/7320592652?check_suite_focus=true#step:6:513

I think I found the "right" flow for now, so hopefully, this won't happen in the future. In the long term, I hope that GitHub will support this flow better.

If you want to help out, go and upvote this feature request: https://github.com/github-community/community/discussions/13836

**Comment by balazsorban44** [comment]
Here is a release note for newer version of the Sequelize adapter: https://github.com/nextauthjs/next-auth/releases/tag/%40next-auth%2Fsequelize-adapter%40v1.0.5
