### ISSUE TITLE
NextAuth Redirect is Always Port 3000 in Development

### ISSUE THREAD

**Issue by peterje** [nextauthjs/next-auth#4764]
### Environment

  System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 230.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.3
  npmPackages:
    next: ^12.0.11-canary.4 => 12.1.6 
    next-auth: latest => 4.6.1 
    react: ^17.0.2 => 17.0.2 

### Reproduction URL

https://github.com/peterje/next-auth-example

### Describe the issue

NextAuth uses port 3000 for redirects, even when port 3000 is not being used by the application.

When using providers, you are redirect to http://localhost:3000/api/auth/signin/google, for example, instead of http://localhost:3001/api/auth/signin/google.

### How to reproduce

Change NEXTAUTH_URL to http://localhost:3001 and run the example with: yarn dev --port 3001. Be sure that you have set up provider secret first.

Click sign in, and sign in with a provider (I used Google).

### Expected behavior

You should be redirected to http://localhost:3001/api/auth/signin/google

**Comment by LOGOLFGODORD** [comment]
I know google has been doing this to me sense birth   Sent from Mail for Windows From: Peter EdmondsSent: Thursday, June 23, 2022 11:35 PMTo: nextauthjs/next-authCc: SubscribedSubject: [nextauthjs/next-auth] NextAuth Redirect is Always Port 3000 in Development (Issue #4764) EnvironmentSystem:OS: macOS 12.2CPU: (8) arm64 Apple M1 ProMemory: 230.94 MB / 16.00 GBShell: 5.8 - /bin/zshBinaries:Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/nodeYarn: 1.22.19 - /opt/homebrew/bin/yarnnpm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npmBrowsers:Chrome: 102.0.5005.115Safari: 15.3npmPackages:next: ^12.0.11-canary.4 => 12.1.6next-auth: latest => 4.6.1react: ^17.0.2 => 17.0.2Reproduction URLhttps://github.com/peterje/next-auth-exampleDescribe the issueNextAuth uses port 3000 for redirects, even when port 3000 is not being used by the application.When using providers, you are redirect to http://localhost:3000/api/auth/signin/google, for example, instead of http://localhost:3001/api/auth/signin/google.How to reproduceChange NEXTAUTH_URL to http://localhost:3001 and run the example with: yarn dev --port 3001. Be sure that you have set up provider secret first.Click sign in, and sign in with a provider (I used Google).Expected behaviorYou should be redirected to http://localhost:3001/api/auth/signin/google—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by benjaminwaterlot** [comment]
Hello @balazsorban44 🙂

[This comment sums up the issue](https://github.com/nextauthjs/next-auth/discussions/5013#discussioncomment-3702040). 

I believe you weren't able to reproduce because it's only happening when the `VERCEL` env variable is set and evaluates to truthy. 

**→ Therefore, using `vercel env pull` will break next-auth for anyone not using port 3000**
