### ISSUE TITLE
Github email is undefined v4

### ISSUE THREAD

**Issue by omgismartinez** [nextauthjs/next-auth#4934]
### Provider type

GitHub

### Environment

- System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G
    Memory: 2.86 GB / 12.89 GB

- Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD

- Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)   
    Internet Explorer: 11.0.19041.1566

- npmPackages:
    next: 12.2.2 => 12.2.2
    next-auth: 4.10.0 => 4.10.0
    react: 18.2.0 => 18.2.0

### Reproduction URL

https://github.com/omgismartinez/secret-chat

### Describe the issue

I read that this **issue was reported** before in **(v3)** because github doesn't allow displaying email unless mail has it public, the solution was to make a request in github api.

In theory for v4 this was already [**fixed**](https://next-auth.js.org/providers/github#example). But now I'm on the latest version of next-auth (v4) and yes my session email is undefined, I have to go into my profile and make it public for it to work

**NOTE**: it worked before

![dependencies](https://user-images.githubusercontent.com/72507996/179013466-46ee585a-bf5c-4d8d-a7c4-ca17a6f4a49e.png)

![session](https://user-images.githubusercontent.com/72507996/179013536-52a43480-bea3-4ab9-bd37-13817be0f379.png)

### How to reproduce

- Login with github provider
- Redirected home
- Show session data (console or api: ` /api/auth/session`)
- Session email is undefined or does not exist

### Expected behavior

- Login with github provider
- Redirected home
- Show session data (console, api: ` /api/auth/session`)
- Display session email

**Comment by balazsorban44** [comment]
Curious :thinking: 

So the [GitHub docs is here](https://docs.github.com/en/rest/users/emails#list-email-addresses-for-the-authenticated-user), saying:
> Lists all of your email addresses, and specifies which one is visible to the public. This endpoint is accessible with the `user:email` scope.

Unless you modify the `authorization` config option, the default will include the `user:email` scope:

https://github.com/nextauthjs/next-auth/blob/8853000fd524b074f82ad38c57671fe1f640172f/packages/next-auth/src/providers/github.ts#L70


And we attach the first available e-mail to the returned profile here:

https://github.com/nextauthjs/next-auth/blob/8853000fd524b074f82ad38c57671fe1f640172f/packages/next-auth/src/providers/github.ts#L81-L94

I cannot spot an issue. (We could probably tinker the thing a bit to prefer the public email instead of just the first one in the list, but it's irrelevant here as we seem to get zero e-mails back. :shrug:)

Do you maybe have a reproduction repository for this?

**Comment by balazsorban44** [comment]
The issue was:
https://github.com/nextauthjs/next-auth/pull/4938/files#diff-9c342cf6cbd3bad377151456f27b9a3389d05af578c6d17310d58e4ea2608defL70-R68

**Comment by omgismartinez** [comment]
wow a single space killed the code lol. **@balazsorban44 thanks you** 🔥

**Comment by balazsorban44** [comment]
This is now part of [`next-auth@4.10.1`](https://github.com/nextauthjs/next-auth/releases/tag/next-auth%40v4.10.1)!
