### ISSUE TITLE
Users come back from google with error=OAuthCallback

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [nextauthjs/next-auth#4967]
### Provider type

Google

### Environment

 System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 29.14 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Safari: 13.1.2

### Reproduction URL

https://briefy.netlify.app/auth/signin

### Describe the issue

Users are redirected to the oauth after selecting google account they're redirected to login page with error=OAuthCallback as one of the parameters in the url

### How to reproduce

Go to [https://briefy.netlify.app/auth/signin](https://briefy.netlify.app/auth/signin) and sign in with the google option.

### Expected behavior

The user is supposed to be redirected to the dashboard, just the same way as when logging in with other providers

**Comment by balazsorban44** [comment]
Please link to the code. :pray:

**Comment by Onyelaudochukwuka** [comment]
https://github.com/Onyelaudochukwuka/brief

**Comment by balazsorban44** [comment]
Thanks! 
I cloned your repo and was able to log in with Google just fine:

![image](https://user-images.githubusercontent.com/18369201/179852219-caa44df1-50de-4d8b-97c5-a510ab4fd9b9.png)

You likely misconfigured the callback URL in Google, or there is an issue in your database. :thinking:

Please double-check your client id and secret as well (make sure env var names match with your code references). I recommend checking your logs because they might have more information for you.

One thing I noticed. https://github.com/Onyelaudochukwuka/brief/tree/main/pages/api/auth/lib This folder should not be under `/pages/api` because it's not a Next.js API handler. you should move it somewhere outside of `pages`

**Comment by balazsorban44** [comment]
Thanks! 
I cloned your repo and was able to log in with Google just fine:

![image](https://user-images.githubusercontent.com/18369201/179852612-523d91fd-e6fd-42f6-9f73-d4c111f9dc20.png)

You likely misconfigured the callback URL in Google, or there is an issue in your database. :thinking:

Please double-check your client id and secret as well (make sure env var names match with your code references). I recommend checking your logs because they might have more information for you.

One thing I noticed. https://github.com/Onyelaudochukwuka/brief/tree/main/pages/api/auth/lib This folder should not be under `/pages/api` because it's not a Next.js API handler. you should move it somewhere outside of `pages`

**Comment by Onyelaudochukwuka** [comment]
Ok thanks I'll do that

**Comment by Onyelaudochukwuka** [comment]
![Screen Shot 2022-07-20 at 6 58 35 AM](https://user-images.githubusercontent.com/82924100/179907894-249a4966-b611-44a1-ac03-2d79d9b31c6d.png)

I don't think the issue is from my callback url

**Comment by Onyelaudochukwuka** [comment]
I don't realy think the issue is from my database because other providers work fine let me check my private keys again

**Comment by Onyelaudochukwuka** [comment]
There's already

> Thanks! I can confirm this is not a NextAuth.js bug. I cloned your repo and was able to log in with Google just fine:
> 
> ![image](https://user-images.githubusercontent.com/18369201/179852612-523d91fd-e6fd-42f6-9f73-d4c111f9dc20.png)
> 
> You likely misconfigured the callback URL in Google, or there is an issue in your database. 🤔
> 
> Please double-check your client id and secret as well (make sure env var names match with your code references). I recommend checking your production logs because they might have more information for you.
> 
> One thing I noticed. https://github.com/Onyelaudochukwuka/brief/tree/main/pages/api/auth/lib This folder should not be under `/pages/api` because it's not a Next.js API Route handler. you should move it somewhere outside of `pages`

The issue was with my private keys Thank you for your , time i really appreciate it!

**Comment by Onyelaudochukwuka** [comment]
> 

I can't move that out because i have another lib directory connecting my server to the database to the web app
