### ISSUE TITLE
Make `getToken` work without `Headers` polyfill

### ISSUE THREAD

**Issue by mmkal** [nextauthjs/next-auth#4988]
My team use node v14.17.0 and need to parse the token that next-auth creates in a separate express server which doesn't use next.js. `getToken` is throwing because `Headers` is not defined and since we don't `import 'next'`, it doesn't get polyfilled.

Context:

_Originally posted by @mmkal in https://github.com/nextauthjs/next-auth/issues/4983#issuecomment-1191443219_

**Comment by balazsorban44** [comment]
From the comment above, this sounds like not a NextAuth.js/Next.js issue and falls outside the scope of the project currently. You can load a `Headers` polyfill in your environment.

(Just defining `globalThis.Headers = class Headers {}` is likely sufficient in your case, assuming no other code is dependent on this being globally available.)

NextAuth.js is currently only intended to work with Next.js in its current form.

We are working on support outside Next.js, including Express. See #3942

This is similar to the approach in https://github.com/s-kris/vite-ssr-next-auth/blob/master/server/index.ts as well.

**Comment by mmkal** [comment]
@balazsorban44 I don't really understand the resistance to the fix I proposed.  You'll note that I didn't add to the docs "next-auth fully supports vanilla express servers and the developers will be on the hook for everything that goes wrong in them". I literally just added `typeof Headers !== 'undefined'`. Having that random file depend on a polyfill that another library applies seems like a bad invisible dependency, so in my opinion it's a net good change, whether you think the use case I'm describing is legitimate or not.

I guess I'd like to try one more time, and to rephrase my original justification for the issue/pull request. It isn't a bug in next-auth. But it's a confusing and unnecessary error that blocks off a legitimate potential use case which could lead users to install unnecessary dependencies, or spend a lot of time reading threads _far_ beyond the scope of the initial issue. So could you, even if just as a favour to me, accept the `typeof Headers !== 'undefined'` change? Not even because it's required for next-auth to fulfill its obligations - but just because it would be convenient and it's an incredibly easy and safe thing to do for you?

**Comment by balazsorban44** [comment]
As mentioned, the current state of `next-auth` expects you to run in an environment that is equivalent of Next.js. As such, any changes necessary to make it work outside of Next.js is not the library's task to solve.

Adding anything would be unnecessary for all others who are currently using NextAuth.js as intended.

In this case Express users still represent a minority, and so it's easier to ask these people to add

`globalThis.Headers = class Headers {}` or similar workarounds to make this work for them. 

The library is also MIT licensed/open-source, if you disagree with the implementation, you can find the source here and create your own `getToken` method:

https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/jwt/index.ts

Otherwise, if you can reproduce an issue with Next.js and NextAuth.js in its current form that causes an error because of the missing `Headers` check, I would consider it a bug and fix it right away, but in this case, you are not currently using NextAuth.js as intended, and so, it's not the library's responsibility to take care of that your specific need will be met. 

That said, we *are* working on first-class support for many frameworks/environments, Express is likely one of them (when the announcement comes, you are welcome to help out with the implementation), and we will make sure things are polyfilled when that's necessary, or throw better error messages and explain how to solve compatibility issues.

I would also like to call out the manner of how this was reported as well. First of all, there was no previous discussion before opening a PR, so without the necessary contextual information, the PR could not have been justified for merge. When asked for a bug report/reproduction instead, our issue template was ignored/not filled out as expected, and in such cases, we would be entitled to close issues without further notice or comments. Please keep this in mind for the next time. 🙏💚

**Comment by mmkal** [comment]
Fair enough - I also maintain a couple of OSS libraries with much less activity so I know how frustrating it can be when the issue template is ignored. In this case, when you suggested I create an issue instead of the PR, I clicked the "Reference in new issue" button which it seems doesn't populate the issue template. I didn't know there was one but should have hunted for it. 

As for making the PR without prior discussion - sorry for that. The last few PRs I'd raised against this repo had been along the same lines and got merged without issue, some with a couple of comments. I sometimes do that to save time, when I consider the change a "no brainer" (which I still do in this case). The others were just docs though I guess.

I actually completely agree with everything you've said here, by the way. As I mentioned I _don't_ think it's a bug, or nextjs' responsibility to "fix" - that's why I did it for you! And why I didn't make an "issue" first. I still feel the PR made the codebase an tiny amount better overall. I had already done the `globalThis` shim you suggested before opening it. Just trying to improve QOL for others, but I'll leave it now.

I also want to be clear that I'm a big fan of next-auth, and would be happy to help/provide feedback when vanilla express support starts. (I guess we have one more thing to worry about than we could when that time comes! 🙃)
