### ISSUE TITLE
Make crypto usage configurable (enabling NextAuth.js to be used in Cloudlfare Workers, Vercel Edge, Deno Deploy, etc.)

### ISSUE THREAD

**Issue by brillout** [nextauthjs/next-auth#5142]
### Description 📓

@cyco130 and myself are trying to use NextAuth.js with Cloudflare Workers and Vercel Edge.

But NextAuth.js uses Node.js's crypto API which isn't available on these deployment platforms.

Are there plans to make the crypto tooling configurable? In order to enable the use of NextAuth.js with other crypto tools that support Cloudflare Workers / Vercel Edge. (E.g. [`jose`](https://github.com/panva/jose) works with Cloudflare Workers.)

Also, I'm curious: I would guess that making NextAuth.js work with Vercel Edge is a high priority? Since most NextAuth.js users are Next.js users.

(I've seen https://github.com/nextauthjs/next-auth/issues/725 but it's almost two years old and things have changed a lot since then, e.g. Balázs's work and Vercel Edge.)

### How to reproduce ☕️

Trying to deploy any NextAuth.js app to Vercel Edge would do the trick. But let me know if you want some kind of reproduction.

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR. (Edit: probably not in the near future though.)

**Comment by balazsorban44** [comment]
Thanks for your interest! For now, only `next-auth/middleware` is Edge-compatible, but we plan to make the whole core compatible.

I am actively working on migrating away any Node.js-specific APIs from the core of NextAuth.js, and also making it so that you can pass it a standard `Request` and it will return a `Response`.

> Trying to deploy any NextAuth.js app to Vercel Edge would do the trick

This is the eventual goal. AFAIK we don't use `crypto` directly anywhere, it's likely `node-openid-client` that does so, which we are migrating away from in #4299 (rather making it opt-in for backward compatibility).

This will also make it easier to turn the [POC SvelteKit integration](https://github.com/nextauthjs/next-auth/tree/main/apps/playground-sveltekit) into an actual package. cc @wobsoriano 

The remaining tasks are tracked here:

- #4769
- #4299

I don't think it would make sense to have a specific API to make `crypto` configurable, as it will be transitively handled once the above changes are made.

I'm closing this, for now, you can follow the PRs above, and give any suggestions there! :pray:

PS.: We will likely need help (docs/implementation) to recommend Database Adapters that play well with Edge, do let us know if you want to help with that.

**Comment by brillout** [comment]
Thanks for the insightful answer, which makes a lot of sense!

@cyco130 I guess this means NextAuth.js will be able to be used with [HatTip](https://github.com/hattipjs/hattip)? Also https://github.com/nextauthjs/next-auth/pull/4704.

**Comment by brillout** [comment]
(Btw. FYI if/when we manage to make NextAuth.js work with HatTip then it means that NextAuth.js will be able to be used seamlessly across all JavaScript environments!)

**Comment by balazsorban44** [comment]
🔥

**Comment by brillout** [comment]
> I guess this means NextAuth.js will be able to be used with [HatTip](https://github.com/hattipjs/hattip)?

From @cyco130:

> It seems, to. Currently it does accept a Request but returns something custom (which is pretty easy to turn into a Response). So it *should* work [...]

**Comment by konradbjk** [comment]
Been a while, and with the current version, next-auth does not work with its core still. It means that one cannot use Next-Auth on Cloudflare pages. What is the progress on it @balazsorban44 ?

**Comment by markdembo** [comment]
Do we have an update here? It would be so great to have nextauth available von Cloudflare/Vercel/etc.

**Comment by adb-sh** [comment]
hey :) i'm facing a simular issue with using solid-start and deno. wanted to use deno for production instead of node.
