### ISSUE TITLE
RBAC for pages using NextAuth?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [nextauthjs/next-auth#5314]
### Question 💬

So I still don't understand how we can use next-auth to protect pages using RBAC in a way that cannot be hacked on the client?

I have read https://github.com/nextauthjs/next-auth/issues/1210#issuecomment-782630909.

I have also read https://logfetch.com/next-auth-global-session.

Both of these solutions seem to rely on an HOC <Auth> component leveraged inside _app.js. But I don't see how if I am using SSG/CSR based pages that this solution can't be hacked on the client by someone using devtools.

I am sure I am missing something here--hopefully someone can enlighten me

### How to reproduce ☕️

Simple question. No code needed.

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
Since the session token is issued by the server using cryptography, hopefully, nobody can hack you, if you use `next-auth` correctly.

A willing user could access a UI they are not supposed to, but any kind of data that needs protection should come from an API that requires proper authorization.

There is now a way to easily protect whole pages that cannot be "hacked" this way, using Middleware as it always runs on the server. Check out the docs: https://next-auth.js.org/configuration/nextjs#middleware
