### ISSUE TITLE
Trying to test on local

### ISSUE THREAD

**Issue by ni3k** [nextauthjs/next-auth#539]
**Describe the bug**
After yarn build and yarn start the protected api routes which use `import { getSession } from 'next-auth/client'` fails with error:
[next-auth][error][CLIENT_FETCH_ERROR] [
  '/api/auth/session',
  TypeError: Only absolute URLs are supported
      at getNodeRequestOptions (/home/nick/Docs/videocursuri/node_modules/next/dist/compiled/node-fetch/index.js:1:145647)
      at /home/nick/Docs/videocursuri/node_modules/next/dist/compiled/node-fetch/index.js:1:147021
      at new Promise (<anonymous>)
      at fetch (/home/nick/Docs/videocursuri/node_modules/next/dist/compiled/node-fetch/index.js:1:146956)
      at /home/nick/Docs/videocursuri/node_modules/next-auth/dist/client/index.js:276:23
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/home/nick/Docs/videocursuri/node_modules/next-auth/dist/client/index.js:20:103)
      at _next (/home/nick/Docs/videocursuri/node_modules/next-auth/dist/client/index.js:22:194)
      at /home/nick/Docs/videocursuri/node_modules/next-auth/dist/client/index.js:22:364
      at new Promise (<anonymous>)
] 
**To Reproduce**
follow the next.js recipes regarding protected api and set NEXTAUTH_URL=http://localhost:5005 in .env.local
after this do:
yarn build
yarn start -p 5005

**Expected behavior**
getSession({ req }) to not fail

* [ ] Found the documentation helpful
* [X] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
An example of this is included in the example project and can be tested on the demo site to see it working. I cannot replicate this problem.

**Comment by ni3k** [comment]
> An example of this is included in the example project and can be tested on the demo site to see it working. I cannot replicate this problem.

the problem is that it's working in dev mode (yarn dev) but failing if it builds before

**Comment by ni3k** [comment]
```
if (!process.env.NEXTAUTH_URL) { logger.warn('NEXTAUTH_URL', 'NEXTAUTH_URL environment variable not set') }

    // Return absolute path when called server side
    return `${__NEXTAUTH.baseUrl}${__NEXTAUTH.basePath}`
```
shouldn't it be `${process.env.NEXTAUTH_URL}${__NEXTAUTH.basePath}` ?

**Comment by iaincollins** [comment]
> shouldn't it be `${process.env.NEXTAUTH_URL}${__NEXTAUTH.basePath}` ?

No, it is correct. The value `process.env.NEXTAUTH_URL` can optionally contain a custom path and wouldn't be appropriate to use here (but it's *optional* so we also extract and set a `basePath` explicitly).

The problem is not present on the demo site (which runs in production mode), if it was broken the demo site wouldn't work.

If this is your first time using NextAuth.js, I suggest starting with cloning the example repo and getting started with that.

I suspect there is some context we are missing, this is unlikely to be a bug as nobody else has reported this.

If you can post a link to a repo with steps to replicate someone should be able to take a look and figure out what is going on.

**Comment by ni3k** [comment]
The issue was in version.
The version I was using was ^2.x.x
after I changed in 3 everything was fine
