### ISSUE TITLE
Auth0 Passwordless login support

### ISSUE THREAD

**Issue by roger-king** [nextauthjs/next-auth#5503]
### Question 💬

Hello, I am evaluating Next-Auth to solve a problem in our application. I am wondering if there is a way to handle auth0 passwordless login via email and phone number within Next-Auth.

For context, we have a custom flow of managing the integration of Auth0 into our application because we wanted a custom UI to handle the passwordless login and signup flow. I am hoping to be able to continue making the API calls for the OTP (passwordless login) and let next-auth handle the cookie and Jwt management

### How to reproduce ☕️

n/a

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Not sure I fully understand, but we have built-in Passwordless support:
https://next-auth.js.org/providers/email

Also a built-in Auth0 provider: https://next-auth.js.org/providers/auth0

**Comment by IonelLupu** [comment]
hey @balazsorban44 

Auth0 offers a passwordless feature on its own. This means, when a user click on the login button, it will be redirected to the Auth0 website in order to input the email and get the authentication code (The Auth0 website can be designed to look as the website).

Is there a way to do that with the auth0 provider? We have everything user related in Auth0 and we can't move to the "email" provider
