### ISSUE TITLE
New user with credential provider

### ISSUE THREAD

**Issue by ramiel** [nextauthjs/next-auth#558]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**
I have a custom credential login. I know, during signin if user is new or not to my system. How can I get isNewUser to be true?

**What are you trying to do**
Redirect to `page/newUser` on first login

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by iaincollins** [comment]
Hi there! Interesting question!

This is currently not possible - there is no way to pass back `isNewUser` when using the Credentials Provider. 

I am not averse to a considering this as request to support this feature though!

**Comment by ramiel** [comment]
I'd like it honestly. Otherwise I have no other way to redirect to a specific page based on a custom guard, i.e. I may check `user.isNew` because I can populate that property. In this case, what can I use to redirect?

**Comment by ramiel** [comment]
Also, can I write a custom provider that works as the `credential` one but can handle `isNew`? If yes, how?

**Comment by ramiel** [comment]
Again, while we're here, which providers support the `isNewUser` info?

**Comment by iaincollins** [comment]
>  i.e. I may check user.isNew because I can populate that property. In this case, what can I use to redirect?

Yeah I think that's a good approach, I don't have a great answer right now but thinking about it.

1. It could even be a dedicated callback, like `isNewUser: async (user) => { /* code */ }`

2. Alternatively, additional options could get passed to the `redirect()` callback, like the Session Token / JWT to allow you to determine what to return when the redirect callback is triggered (that way you could return custom URL when someone signs in, which might be the URL they came from by default but could be a new user landing page or a 'hey your subscription has expired' page or something like that).

> Again, while we're here, which providers support the isNewUser info?

So it's set to true anytime a user signs in who was not already in the database (so works with any provider *except* Credentials Provider as it is the only one that doesn't use a database).

It does require you are using a database though; it's not generally possible to determine it otherwise (most OAuth Providers do not provide data that can be used to work out if it's the first time signing in to app or not, the only way to know is if you have a record of it somewhere like your own database).

**Comment by ramiel** [comment]
> Yeah I think that's a good approach, I don't have a great answer right now but thinking about it.

Great, both solutions you proposed sound good. Looking forward for any progress to support this use case.

> It does require you are using a database though

Yes indeed, Anyway there might be other ways to detemineit depending on the application specific logic
