### ISSUE TITLE
Signout does not invoke provider logout url (Cognito)

### ISSUE THREAD

**Issue by DavidPIsaac** [nextauthjs/next-auth#5862]
### Provider type

Cognito

### Environment

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 5.96 GB / 15.76 GB
  Binaries:
    Node: 19.0.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 107.0.5304.107
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    next: latest => 13.0.4
    next-auth: latest => 4.17.0
    react: ^18.2.0 => 18.2.0

### Reproduction URL

next-auth-example 

### Describe the issue

Next-auth-example with Cognito does not invoke Cognito logout URL on sign-out, leaving the user logged in with Cognito and allowing the user to re-sign-in without credentials.  This is a potential security exposure for all OAuth providers if developers use next-auth-example as a model for their application.  

### How to reproduce

Configured next-auth-example to use Amazon Cognito and successfully signed in.
Clicking "Sign Out" shows "You are not signed in" confirmation, but Cognito logout URL is never invoked, and clicking "Sign In" shows "You are signed in" confirmation without requesting user credentials.

### Expected behavior

By default, user should have to enter credentials to sign in after sign out.

**Comment by balazsorban44** [comment]
This is expected. `next-auth` does not implement federated logout at the moment. See #3938

The "potential security exposure" is incorrect, many apps that use third-party providers for login won't log you out on the identity provider either. There are workarounds in #3938 for now. If you feel to work on this, please open a PR.

**Comment by theRizwan** [comment]
I also had faced the same issue in our app, after spending hours I am able to resolved the issue.

There are couple of things you need to care:

1. First I was using the Next Auth with Cognito and when I try to logout its not working.

```
signOut({ redirect: false }).then(() => {
  window.location.href = cognitoLogoutUrl;
});
```
Since it was too quick and logged in me back to my application, without logging out. i wasn't able to debug it properly. so I check the preserve log the checkbox in network tab and download the HAR file. When Analysing it, I noticed that the session wasn't being cleared properly by next-auth. After checking the request payload being sent to /api/auth/signout, I saw this:

```
{
  "csrfToken": undefined,
  "callbackUrl": "https://cognito.myapp.com/...",
  "json": true
}
```

The issue turned out to be that signOut({ redirect: false }) requires a valid CSRF token, which isn't automatically included by next auth automatically.

✅ Solution

I manually added the CSRF Token, for this I use getCsrfToken() method from next-auth and pass it into the signOut call:

```
import { signOut, getCsrfToken } from 'next-auth/react';

const logout = async () => {
  const csrfToken = await getCsrfToken();

  await signOut({
    redirect: false,
    callbackUrl: 'https://cognito.myapp.com/afterlogout',
    csrfToken, // ✅ Required when redirect is false
  });

  // Manually redirect to Cognito logout
  window.location.href = 'https://your-cognito-domain/logout?client_id=...&logout_uri=...';
};
```
And it works 😊 Now you think why this works? When redirect: false is used in signOut, it means you're making a request to sign out programmatically which next-Auth expects from you to be protected with a valid CSRF token . If its missing or undefined the next-auth will silently fail the signout request and session remain still active.


2. Secondly Make sure you have used the correct the logout URL format as specified on AWS documentation.

`https://<YourUserPoolId>.auth.eu-west-1.amazoncognito.com/logout?client_id=<YourClientId>&logout_uri=<YourSignOutURL>`

which you already tired of checking 😫 , there is one important I would like to point in it, if you have used / at the end of your logout_uri in Logout URL but not in Signout URLs in Cognito Console it then it won't work like, like http://localhost:3000 and you are using http://localhost:3000/ then it won't work because Cognito match the URLs Exact so Make sure if you used / at the end of URL so it must be same.

3. The One most important thing which AWS documentation haven't mentioned it, If you're using a custom domain for your Cognito then standard format of Logout URL specified by AWS documentation won't work, you have to use below format:

`https://<yourcustomcognitodomain>/logout?client_id=<YourClientId>&logout_uri=<YourSignOutURL>`

like

`https://auth.example.com/logout?client_id=<YourClientId>&logout_uri=<YourSignOutURL>`

Unfortunately! It wasn't mentioned by Next-Auth or AWS in any of their documentation and I was completely confused during debugging that is it next-auth or Cognito Issue?

Hope this helps someone and save debugging time!

**Comment by adrfinance** [comment]
Have you found a solution? I am stuck with that issue and can't logout from Cognito.

**Comment by theRizwan** [comment]
Yes ✅, I found a solution!

I ran into the exact same issue with **Cognito and `next-auth`**, where calling `signOut({ redirect: false })` wasn't actually clearing the session. It seemed like nothing happened, I got redirected right back into the app as if I never logged out. Debugging was tricky because it happened too fast to inspect properly.

After checking "Preserve log" in Chrome DevTools and reviewing the HAR file, I found the issue: the **CSRF token was missing** in the sign-out request payload:

```json
{
  "csrfToken": undefined,
  "callbackUrl": "https://cognito.myapp.com/...",
  "json": true
}
```

### ✅ The Fix

You **must** manually fetch and pass the CSRF token when using `redirect: false` in `signOut`. Here's what finally worked:

```ts
import { signOut, getCsrfToken } from 'next-auth/react';

const logout = async () => {
  const csrfToken = await getCsrfToken();

  await signOut({
    redirect: false,
    callbackUrl: 'https://cognito.myapp.com/afterlogout',
    csrfToken, // ✅ Required when redirect is false
  });

  // Then manually redirect to Cognito logout
  window.location.href = 'https://your-cognito-domain/logout?client_id=...&logout_uri=...';
};
```

### Why This Works

When you use `signOut({ redirect: false })`, **NextAuth expects a valid CSRF token** because it's treated as a protected POST request. If it's missing (as in your HAR), `next-auth` silently skips the logout, keeping your session alive, which is why you get logged back in immediately.

By fetching the token via `getCsrfToken()` and including it, the session is properly invalidated. Then you can safely redirect to Cognito's logout URL to clear the Cognito session too.

Let me know if you need help.

**Comment by adrfinance** [comment]
Will this work in angular too?

**Comment by theRizwan** [comment]
No, this exact solution (with signOut, getCsrfToken, etc.) will not work in Angular.
