### ISSUE TITLE
Link to /guides/basics/overriding-jwt returns 404

### ISSUE THREAD

**Issue by MonstraG** [nextauthjs/next-auth#6069]
### What is the improvement or update you wish to see?

Searching for `encode` I see this:
![image](https://user-images.githubusercontent.com/17963791/207847916-978fee4e-ee53-4bef-b02b-94b89fc0d1b2.png)

pressing enter navigates me to 

https://next-auth.js.org/guides/basics/overriding-jwt

which gives me Page not found

### Is there any context that might help us understand?

n/a

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/guides/basics/overriding-jwt

**Comment by balazsorban44** [comment]
Thanks, it's an indexing issue we need to look at, in the meantime, the docs you are looking for:

https://next-auth.js.org/configuration/options#override-jwt-encode-and-decode-methods

or

https://authjs.dev/guides/basics/overriding-jwt

**Comment by iswarmondal** [comment]
Hey @balazsorban44, let me take this issue

**Comment by iswarmondal** [comment]
Hey @MonstraG I think the docs has changed since the issue if posted and I found the overriding docs here in this link

https://next-auth.js.org/v3/warnings#jwt_auto_generated_signing_key
And
https://next-auth.js.org/configuration/options#override-jwt-encode-and-decode-methods

Let me know if you still face any problem

**Comment by balazsorban44** [comment]
This seems to be working now.
