### ISSUE TITLE
Option to include JWT in callback URL (Auth0-style)

### ISSUE THREAD

**Issue by tomaszn** [nextauthjs/next-auth#609]
**Summary of proposed feature**
Possibility to include the signed JWT token in the callback URL on successful sign in.

**Purpose of proposed feature**
I'd like to replace Auth0 with next-auth hosted on a separate subdomain.

My backend is implemented with AWS HTTP API Gateway which currently doesn't support authorization by cookies; that has been already requested, but no timeline has been provided:
https://forums.aws.amazon.com/message.jspa?messageID=953437

The simplest solution is to stick to what my current solution with Auth0 does: using JS to add the Authorization header obtained in the auth flow and even possibly keep using the auth0 JS library to authorize the user.

**Detail about proposed feature**
Auth0 adds following information to the callback URL:
`Location: https://mysite/callback#access_token=OysC...&scope=openid%20email&expires_in=7200&token_type=Bearer&state=9IICE0...&id_token={signed_jwt}`

`id_token` is what I need, but other parameters may be required for compatibility, e.g. `state` - according to [OAuth2 specification](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#Combinations) - "the request MAY include a state parameter, and if so, the Authorization Server MUST echo its value as a response parameter when issuing either a successful response or an error response".

Additional useful feature: in case of a valid session Auth0 skips the authentication step and immediately redirects to callback URL (including all the information). This is controlled by an optional "prompt" parameter:
https://auth0.com/docs/universal-login/new-experience#signup

**Describe any alternatives you've considered**
* Switch the AWS backend from HTTP API to REST API and write a custom authorizer that uses the cookie; however, REST API is slower and more expensive.

I'm willing and able to help implement the proposed feature.

**Comment by iaincollins** [comment]
Thank you for writing this feature up.

NextAuth.js does not return the JWT in the callback response, as it's also the session token and not client readable by client side JavaScript by design, as that introduces potential security problems. There are no plans to support any flows (such as the implicit flow) that rely on storing the session token where it is accessible from client side JavaScript.

There are also no plans to return additional data by default in the callback, though you could use the `redirect` callback to append data to the URL the user is returned to after signing in (or re-write the URL entirely) to force specific behaviour after signing in (such as telling the client to go make a request to an API endpoint).

[However, it possible to access the JWT (either raw or decoded) from an API route](https://github.com/nextauthjs/next-auth-example/blob/main/pages/api/examples/jwt.js). If you need to send it to an API to make a request from the client, you can use a Serverless function to do that and make the request from the API route.

This is quite a common approach people take in a scenario like this. The `getToken` helper is even able to read JWT's passed in the header and will look for it if a cookie is not found, so that you can use the same helper method in JavaScript functions outside of a Next.js app.

The order of magnitude for Serverless functions on AWS is under $5 per million requests (that's the total cost, including Lambda, API Gateway, Route 53, CloudTrail, etc) so it is unlikely cost is a major issue, and the latency is low.

Regarding the default sign in page behaviour, you can currently do that with a custom sign in page, but it's likely we will add something like that to NextAuth.js in future (where it will default to the option to link/unlink accounts or will redirect to specified endpoint, depending on how the option is configured).
