### ISSUE TITLE
Cookie session two next-auth applications

### ISSUE THREAD

**Issue by geraldnolan** [nextauthjs/next-auth#611]
**Your question**
I am using next-auth in two dev projects localhost:3000 and localhost:3005.  Is this something that is supported or should I being doing something with the custom cookies?  

The session is getting updated from the prior one after sign in.

Sign into localhost:3000
```javascript
SESSION AFTER UPDATE -> {
  user: {
    name: 'Test User',
    family_name: 'Test',
    given_name: 'User',
    sub: 'cf1b0980-4117-4cec-9f27-c80bcfeb5175'
 }
}
```

Sign into localhost:3005

See output from localhost:3000
```javascript
SESSION AFTER UPDATE -> {
   user: {
    sub: '-20140000004807',
    name: 'New User ',
    given_name: 'New',
    family_name: 'User',
    email: '',
    iat: '2019-12-26T21:39:15.894Z',
    accessToken: 'mDgxsm3W9nKsYC1quPnyJaTSmvwBz4'
  },
}
```

**Comment by iaincollins** [comment]
That is a great question and I had to look up the answer to this.

So, the cookie domain is not set it so defaults to the current domain (e.g. 'localhost').

_Note: I'm actually thinking of making this much easier to set (including so it can be used to create a cookie that can be used across subdomains more easily, and later adding cross domain support with message passing) but it turns out like that wouldn't help here._

While some browsers support isolating cookies by port (e.g. Firefox) it seems generally most browsers don't. It turns out RFC 2965 introduced a port parameter to cookies to support this, but RFC 6265 removed it (seemingly because most clients didn't honour it and it caused confusion). So it turns out ports cannot officially be used to differentiate cookies (though it might work in some browsers, depending on how it's set). [The answers in this StackOverflow post seemed to explain it quite well](https://stackoverflow.com/questions/1612177/are-http-cookies-port-specific).

It seems like the most practical workaround is setting up an alias like localhost (e.g. 'localhost2') and using that for one of the apps. :-|

**Comment by geraldnolan** [comment]
@iaincollins That was my plan, similar to what we did with apple single sign-on.

**Comment by bduff9** [comment]
> _Note: I'm actually thinking of making this much easier to set (including so it can be used to create a cookie that can be used across subdomains more easily, and later adding cross domain support with message passing) but it turns out like that wouldn't help here._
> 

@iaincollins Currently running into this issue where I need the cookie on two different subdomains.  Was there any progress on this?  I see the docs on customizing cookies but it doesn't seem to allow setting domain, only other cookie options like SameSite and HttpOnly

**Comment by raphaelpc** [comment]
> > _Note: I'm actually thinking of making this much easier to set (including so it can be used to create a cookie that can be used across subdomains more easily, and later adding cross domain support with message passing) but it turns out like that wouldn't help here._
> 
> @iaincollins Currently running into this issue where I need the cookie on two different subdomains. Was there any progress on this? I see the docs on customizing cookies but it doesn't seem to allow setting domain, only other cookie options like SameSite and HttpOnly

@bduff9 actually, i don't know if you tried, but i just gave it a try and, despite the documentation don't referencing the field "domain", it accepts that customization. My code looks like this:

```
...
  cookies: {
    sessionToken: {
      name: 'my-service.session-token',
      options: {
        domain: environment !== 'development' ? '.my-service.com' : undefined,
        path: '/',
        httpOnly: true,
        secure: environment !== 'development',
        sameSite: 'lax',
      },
    },
  },
...
```

Anyway, i can now access the cookie on my other domains, but i still don't know what is the best approach to sharing that session. Should i just read the information in the cookie? Because, doing like that, the cookie lifespam won't be increased, like happens when i access de session api endpoint or the useSession / getSession client. Also, if that is really the case, should we also validate the value in the CSRF cookie?

Thanks in advance if someone can help!
