### ISSUE TITLE
Search bar in next-auth.js.org and authjs.dev are not working

### ISSUE THREAD

**Issue by joulev** [nextauthjs/next-auth#6121]
### What is the improvement or update you wish to see?

Search bar should work otherwise it's quite hard to navigate and look for specific information in the documentation.

### Is there any context that might help us understand?

A picture is worth more than a thousand words.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/44609036/208434384-d38257e9-9798-4708-a976-6e00028e2cb2.png">

### Does the docs page already exist? Please link to it.

All pages basically

**Comment by balazsorban44** [comment]
Thanks, we have a ticket with Algolia, trying to resolve!

**Comment by ndom91** [comment]
For a little more detail, we created a second search index in Algolia, since we have two  somewhat significantly different sets of docs sites now with different domains, paths, etc. (next-auth.js.org and authjs.dev).

Upon creating that second index, and ensuring each deployment was pointed at the right one in the `docusaurus.config.js` file, the search simply died. It does work in their "search preview" debugging window though, each index works just as expected :thinking: 

If anyone has any experience managing two indexes / domains with algolia's DocSearch we'd be happy for any help! Otherwise, as Balazs mentioned, we have a ticket open with them already, hoping to hear back soon :crossed_fingers:

**Comment by balazsorban44** [comment]
This is fixed now! Thank you for your patience!

Both  http://authjs.dev and https://next-auth.js.org has a working search again. :green_heart: :mag_right:

**Comment by joulev** [comment]
@balazsorban44 (this is perhaps too minor an issue to open a new issue)

I notice now that while the search bar works (of course), all links are opening in new tabs (`target="_blank"`). I don't know if this is how it's intended to work or not, but it's definitely unexpected behaviour for me (all other documentations I've ever read don't have this behaviour). Is this a feature or a bug?
