### ISSUE TITLE
SvelteKit: Not found: /auth/signin Not found: /auth/signout

### ISSUE THREAD

**Issue by xmlking** [nextauthjs/next-auth#6185]
### Environment

  System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 33.34 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    @auth/core: 0.2.3 => 0.2.3 
    @auth/sveltekit: 0.1.10 => 0.1.10 
    @sveltejs/kit: 1.0.1 => 1.0.1 

### Reproduction URL

https://github.com/nextauthjs/sveltekit-auth-example

### Describe the issue

When signin signout

We are seeing `Error: Not found: /auth/signin` and `Error: Not found: /auth/signout` errors in the browser console. but the route still works. 
I suspect the SvelteKit client-side routing is not aware of routes added by `AuthJS`  via hooks

<img width="757" alt="image" src="https://user-images.githubusercontent.com/627951/209482889-d384340d-ddcb-483c-a9f7-ffb634882c98.png">

### How to reproduce

got to  https://sveltekit-auth-example.vercel.app
open browser debug console 
now sugin / signout 
see errors in the  browser console 

### Expected behavior

there should be no errors in the console

**Comment by xmlking** [comment]
still having problem latest release today 


<img width="716" alt="image" src="https://user-images.githubusercontent.com/627951/214204921-cad4397b-0181-44d2-a448-ee51a720b05b.png">

**Comment by laurent512** [comment]
still seeing it

**Comment by zuk** [comment]
Same... looks like sveltekit support is broken?

**Comment by kisszoltan** [comment]
I managed to solve this issue by using the `signIn()` function directly and not allowing Auth.js to call it from a form action.

So instead of using the Svelte component provided in @auth/sveltekit package:

```
<SignIn>
    <div slot="submitButton" class="btn btn-ghost text-sm">Sign in</div>
</SignIn>
```

I used the [signIn()](https://github.com/nextauthjs/next-auth/blob/24b0e66ec81d097f0d0e9b0a81fade748d31df5a/packages/frameworks-sveltekit/src/lib/client.ts#L42) function provided in the @auth/sveltekit/client pacakge:

`<button on:click={() => signIn()} class="btn btn-ghost text-sm">Sign in</button>`

Although it does not solve the issue with the SignIn component (so a fix is needed) still it gives an errorless option for developers.
