### ISSUE TITLE
Cookie got cleared and page is refreshed when trying to login via Credentials

### ISSUE THREAD

**Issue by ilyaryabchinski** [nextauthjs/next-auth#6421]
### Provider type

Credentials

### Environment

System:
OS: macOS 13.0
CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
Memory: 86.11 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.2/bin/yarn
npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
Watchman: 2022.05.23.00 - /usr/local/bin/watchman
Browsers:
Chrome: 108.0.5359.124
Firefox: 103.0.2
Safari: 16.1
npmPackages:
next: 13.1.2 => 13.1.2
next-auth: ^4.18.8 => 4.18.8
react: 18.2.0 => 18.2.0

### Reproduction URL

https://github.com/ilyaryabchinski/next-auth-credentials-custom-page-issue

### Describe the issue

When trying to log in with credentials, the page got refreshed and the auth cookie was set and cleared after a couple of seconds. Redirect to the index page and authentication doesn't work properly.

### How to reproduce

1. Navigate to the index page
2. Press the "Sign In" button
3. Enter a random email and password and press the login button

### Expected behavior

I expect to be redirected back to the index page and the auth cookie to be set and NOT cleared

**Comment by balazsorban44** [comment]
This is a duplicate of https://github.com/nextauthjs/next-auth/issues/6384.

I looked more into your repro, and it has at least three(?) obvious issues to me:

1. you are calling `signIn()` which is supposed to send you to the sign-in page, hence you are not getting logged in. Change it to `signIn("credentials", {...credentials})`. https://github.com/ilyaryabchinski/next-auth-credentials-custom-page-issue/blob/0911b5231b01584ad566121abfa5078d255ad115/src/pages/index.tsx#L11
Although this might be intentional?
2. You are reading `user` in the `session` callback, but it's not available with the credentials provider as it only supports the JWT session strategy: https://next-auth.js.org/configuration/callbacks#session-callback. https://github.com/ilyaryabchinski/next-auth-credentials-custom-page-issue/blob/0911b5231b01584ad566121abfa5078d255ad115/src/pages/api/auth/%5B...nextauth%5D.ts#L7

The terminal shows you this error though, so you should be able to fix it easily. change `user.id` to `token.id`.

3. you are mixing a standard form and the `signIn` method for the signin page. `signIn` already handles CSRF, so it's not necessary. If you want to go the true form submission way, check out the docs: https://next-auth.js.org/configuration/pages#credentials-sign-in
