### ISSUE TITLE
Recomendation for connecting to third party websocket api that needs the token for auth?

### ISSUE THREAD

**Issue by timcash** [nextauthjs/next-auth#643]
Trying to connect to a third party graphql api that uses websockets. Should I build a secondary jwt for this api so it can connect direct from the browser or is there a way to use the jwt provided by next-auth? The service docs are here https://dgraph.io/docs/graphql/authorization/authorization-overview/

Sadly nextjs apis do not allow websockets as far as I can tell. 

Currently trying to connect from apollo client and need to grab the jwt client side.

**Comment by iaincollins** [comment]
Great question! Slightly complicated to answer but tl;dr:

The JWT for NextAuth.js isn't readable by the browser by design (following best practice, to prevent XSS and session hijacking by third party scripts), so probably I would say you might find it easier to create a separate JWT in this case.

###  Websockets

NextAuth.js isn't designed around Sockets as it's designed around Serverless, and using sockets with Serverless endpoints doesn't really work very well. I'm not averse to extending and improving the Event handling though (including documenting existing events that get fired and adding to them, to make it easier to hook into them).

That said, I have built Next.js apps that use NextAuth.js and that use Sockets, by having a separate (non-Serverless endpoint; specifically a Docker container) running as an API and passing details through to it, because there are scenarios that really need something like a Socket to work well (specifically, I build a web based video / audio manipulation app).

I approached this creating an access token and associating it with the user in a database; this of course presumes a database for session storage, but you could essentially do the same thing with a second JWT (e.g. which isn't as session token, so can't be used to update user session state or profile data, etc - but can be used to make API requests with limited permissions).

I then created a session store (Redux/Mobx) that handled sharing the Socket connection / reconnection in the Next.js app and shared the state between pages. It took a while to get the logic just right for the edge cases but works really well.

### Proxying Requests

Generally, I would use NextAuth.js and send requests through a Serverless endpoint in your app on the same domain (e.g. `/api/auth/graphql`) and use it to request data from GraphQL server and return it to the client, which simplifies things a lot as it's all same-domain and makes crafting the headers easier as it can easily access the JWT securely - but I appreciate if you want or need to use Sockets then that doesn't really help you.

I have done this approach in the past, and I much prefer using ApolloClient to make REST requests programatically in this way than loading the full ApolloClient in the browser (as it really helps performance and saves something like 100-200 KB off the bundle size) but I appreciate that's a niche view as you lose some flexibility, and suitability depends on context.

**Comment by getTobiasNielsen** [comment]
Hey @iaincollins 

Firstly thank you and your community for your hard work.

I was looking to have a websockets in my nextjs project.

I've seen people to this: https://github.com/nextauthjs/next-auth/discussions/1518

Where we see the author make a json web token that they themselves question the positional validity of.

But for the sake of quality, I was wondering if you had additional information, about how you eventually ended up doing it that might accessible to me. I've search for a blog or something similar, but sadly haven't found any.

I'm going to attempt opening a websocket connection on the client, and then connect to an external server(non-serverless endpoint).

Once again thank you for the amazing library.

**Comment by mshick** [comment]
I realize this issue is long closed, but for anybody who comes on it looking to solve this issue, I've got another solution. [NextAuthAllAccess](https://github.com/takeshape/next-auth-all-access) is a wrapper module I've put together. It re-encodes the NextAuth token using asymmetric encryption, appends the access token to the session object, and makes your public key available at a JWKS endpoint. It should work with various OpenID Connect-compatible APIs, and would make authenticating with your own custom API relatively easy.

**Comment by maitrungduc1410** [comment]
if you just want to get logged in user, here's example for socketio:

```ts
import { getSession } from "next-auth/react";

io.use(async (socket, next) => {
    const session = await getSession({
      req: socket.request
    });
    console.log(session)
    next();
  });
```
