### ISSUE TITLE
Updating Account after refreshing token

### ISSUE THREAD

**Issue by kasperkberg** [nextauthjs/next-auth#6696]
### Question 💬

I'm trying to do the database strategy as mentioned [here](https://authjs.dev/guides/basics/refresh-token-rotation), in order to update an expired accessToken. I'm using the Spotify-provider.

I am able to generate a new accessToken, but when I'm trying to update the DB with the new token, I get an error.

```
prisma:error
Invalid prisma.account.update() invocation:


Value out of range for the type. target: autopilot.-.primary: vttablet: rpc error: code = FailedPrecondition desc = Out of range value for column 'expires_at' at row 1 (errno 1264) (sqlstate 22003) (CallerID: planetscale-admin): Sql: "update Account set access_token = :v1, expires_at = :v2, refresh_token = :v3 where Account.id in (:v4) and :vtg1 = :vtg2", BindVars: {REDACTED}
```

Is the documentation wrong, or something I'm missing? 

Code snippet below.

### How to reproduce ☕️

```javascript
await prisma.account.update({
  data: {
    access_token: tokens.access_token,
    expires_at: Date.now() + (tokens.expires_in as number) * 1000,
    refresh_token: tokens.refresh_token ?? spotify.refresh_token,
  },
  where: {
    provider_providerAccountId: {
      provider: "spotify",
      providerAccountId: spotify.providerAccountId,
    },
  },
})
```

**Comment by balazsorban44** [comment]
Probably `expires_at` should be saved as a number of seconds instead of milliseconds. <picture data-single-emoji=":thinking:" title=":thinking:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..RS3UrtMU50VzvttO.fVbFdAoiAktLlQEwl4sv51m-qzMz1imE-deJPigJadcjn-b-T9w-4-d-avAcy4fRfYQYYQFEiF3JMMTU6lPatkcWp-f5VPE8Wqx5LUzfniNXceS9coOm7WjQ.qqhhOvguhZKJ_KJDldvYvA" alt=":thinking:" align="absmiddle"></picture>
