### ISSUE TITLE
Firestore authentication rules not working: FirebaseError: Missing or insufficient permissions.

### ISSUE THREAD

**Issue by RisKakaN** [nextauthjs/next-auth#6719]
### Adapter type

@next-auth/firebase-adapter

### Environment

  **System:**
    OS: macOS 13.2

  **Binaries:**
    Node: 16.18.0

  **Browsers:**
    Chrome: 110.0.5481.96

  **npmPackages:**
    @next-auth/firebase-adapter: 2.0.0
    next: 13.1.6
    react: 18.2.0
    next-auth: 4.19.2

**(Using the new nextjs 13 app dir)**

### Reproduction URL

See description below.

### Describe the issue

I am using next-auth with the firebase adapter, and my goal is to authenticate, and access data from firestore if and only if a user is authenticated. I am **not** using firebase auth.

I have followed the steps in https://authjs.dev/reference/adapter/firebase
And setup firebase firestore correctly.

It works to authenticate in my app. The adapter creates sessions, users, and accounts, in my firestore. I am able to make use of firebase admin sdk, to access the firestore, which bypasses any auth rules. 
But, I want to make use of the firebase client sdk, for usage in my client code. And that is where the firebase auth rules come in. I need to open the access for users who are authenticated.
I have tested the following rules:

```
rules_version = '2';
service cloud.firestore {
    match /databases/{database}/documents {
        match /accounts {
            allow read, write: if false;
        }
        match /users {
            allow read, write: if false;
        }
        match /sessions {
            allow read, write: if false;
        }
        // Allow users to access authenticated content
        match /recipes/{userId}/{documents=**} {
            allow read, write: if request.auth != null && request.auth.uid == userId;
        }
    }
}
```
but I am just getting permission-denied.
```
[FirebaseError: Missing or insufficient permissions.] {
  code: 'permission-denied',
  customData: undefined,
  toString: [Function (anonymous)]
}
```

the request.auth seems to be null.

So my question really is, how do i define these rules to work with next-auth, firebase adapter?
Is this possible or not?
If not, then what is the purpose of the firebase adapter? Is it just to store users, sessions, and account, in firestore?

If the direction is to use admin sdk, then why would I need the adapter? I could simply just use next-auth, and then initialize an admin firestore separately, and in that way access firestore.

My understanding was that the adapter should allow for next-auth authentication, and connect it with firestore to let authenticated users access authentication protected data. But maybe I misunderstood.

### How to reproduce

Setup project with the same environment.
Follow the instructions in https://next-auth.js.org/adapters/firebase
Setup firebase and firestore.
Add rule in firebase to only allow read/write for authenticated users.

Now try to read/write the protected content in your app, using firebase client sdk.
(firebase admin sdk will work, because it ignores the rules.)

### Expected behavior

I want authenticated users to be able to access data in firestore, that is protected by authentication access only rules.

**Comment by balazsorban44** [comment]
Since we are using the `firebase-admin` SDK, we enforce no security rules since v2.

Right now we do not integrate with Firebase Auth, so that might be the cause of confusion. `request.auth` does not have permission, because you never logged in via the client.

This is partially the main reason we moved to Firebase Admin SDK as well though, since using the client API of firebase loads a huge amount of JS to your client.

The question is if you want to hand the auth layer to us or keep using Firebase.

You could proxy requests via your backend and use the session to enforce rules, or use the Firebase client SDK instead and ignore NextAuth.js.

**Comment by RisKakaN** [comment]
thanks for the explanation @balazsorban44 

i want to use next-auth because it works well with nextjs. but my thought was that with the adapter, it would also automatically handle the firestore access with the firebase rules.
and since that is not the case, then could you explain what the benefit/purpose is of using the firebase adapter?
is it only to store user/session/account info in firestore? and what is the purpose of storing such info, when next-auth works out of the box anyway, without an adapter.

i can use next-auth, and initialize a firestore with firebase admin sdk, without using an adapter.

**Comment by kylereblora** [comment]
Hi @martinso95, have you managed to figure out using the client-side Firebase SDK with security rules in next-auth?

**Comment by martinso95** [comment]
Hi @kylereblora 
No, using client side firebase is not possible as mentioned above. so I am using admin sdk for all operations, and firebase read write rules are set to false for full safety, because admin sdk can bypass that anyways.

to access firebase in client side, you can create your own api routes, that wraps firebase admin sdk read write operations. then you can use this together with next auth, and make sure that a user must be logged in to have access to the api. with the api routes, you can build your own logic and rules.

**Comment by kylereblora** [comment]
@martinso95 I see, thanks for this. I'm exploring the client-side Firebase SDK due to its offline functionality, but it seems like going this would pose a lot of security concerns.

**Comment by ourienpaul50-dev** [comment]
FirebaseError: Missing or insufficient permissions: The following request was denied by Firestore Security Rules:

How can I solve this please
