### ISSUE TITLE
Issue importing @auth/core when using Jest

### ISSUE THREAD

**Issue by ivoilic** [nextauthjs/next-auth#6822]
### Environment

System:
    OS: macOS 13.2.1
    CPU: (12) x64 Apple M2 Pro
    Memory: 302.45 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - ~/.nvm/versions/node/v19.6.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.6.0/bin/yarn
    npm: 9.4.0 - ~/.nvm/versions/node/v19.6.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 98.0.2
    Safari: 16.3
  Packages:
     @auth/core: 0.5.0

### Reproduction URL

https://github.com/yusukebe/jest-authjs

### Describe the issue

Importing @auth/core while running Jest fails. This is not the case with other npm modules. When importing anything from @auth/core I get the following error in Jest: `Cannot find module '@auth/core/providers/github'` I encountered this while writing Auth.js Middlware for Hono: https://github.com/honojs/middleware/pull/52

### How to reproduce

Checkout this PR: https://github.com/honojs/middleware/pull/52
1. `yarn install` 
2. `yarn build`
3. `cd packages/authjs-server`
4. `jest`

The author of Hono also created this more cut down demo: https://github.com/yusukebe/jest-authjs

### Expected behavior

When running tests with Jest imports from @auth/core should import the same as other packages

**Comment by balazsorban44** [comment]
This is because `@auth/core` is published as ESM only, and Jest's ESM support is a bit funky right now.

I published your reproduction with some changes, which should make it pass the tests:

https://github.com/balazsorban44/authjs-6822

![image](https://user-images.githubusercontent.com/18369201/221722004-98e76ae3-0058-4045-9f6c-b050e2db27d2.png)

Notable additions:

- https://jestjs.io/docs/configuration#extensionstotreatasesm-arraystring
- https://jestjs.io/docs/ecmascript-modules, Step 2
- https://kulshekhar.github.io/ts-jest/docs/guides/esm-support
