### ISSUE TITLE
Invalid Compact JWE

### ISSUE THREAD

**Issue by trpipher** [nextauthjs/next-auth#6844]
### Question 💬

I'm getting an `Invalid Compact JWE bug` whenever I have my Prisma Adapter Uncommented inside of [...nextauth].ts

### How to reproduce ☕️

https://github.com/trpipher/debug

Uncomment line 8 of /pages/api/auth/[...nextauth].ts

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this

**Comment by balazsorban44** [comment]
https://github.com/trpipher/debug/blob/e36093a10e6177d446e56c1274ad32a45dadef21/app/page.tsx#L6

missing `authOptions`

https://next-auth.js.org/configuration/nextjs#in-app-directory

since the adapter is not default, you'll need to make sure that `NextAuth` and `getServerSession` are passed the same options.
