### ISSUE TITLE
difference between session token and access token?

### ISSUE THREAD

**Issue by kevinmachstudio** [nextauthjs/next-auth#693]
Got a document in the `sessions` collection for a logged in user in my test MongoDB database

![image](https://user-images.githubusercontent.com/6373887/93654186-1b511080-f9d1-11ea-9a05-199501940566.png)

What's the difference between `sessionToken` and `accessToken` and why is only `accessToken` being returned to `session` variable in `const [ session, loading ] = useSession()` .

```
{user: {…}, accessToken: "e25f790f00e553b82592626a2a948a643e90a6f3b7c3b0d7b4574e94437e52cc", expires: "2020-10-18T02:58:39.561Z"}
accessToken: "e25f790f00e553b82592626a2a948a643e90a6f3b7c3b0d7b4574e94437e52cc"
expires: "2020-10-18T02:58:39.561Z"
user: {email: "someemail@gmail.com"}
```

In what cases would you use the access token vs the session token and is there an example of how you would use these tokens?

**Comment by iaincollins** [comment]
Great question! This isn't really covered anywhere in the documentation.

A Session Token is usually used to identify a session in a browser (or other client). Typically Session Tokens are fixed and do not change unless a user signs out, but in some applications they can rotate. For optimal security, they should not be readable by client side JavaScript (i.e. they are server side only cookies).

An Access Token is usually used as a way of providing a way for clients to make requests using a token that uniquely identifies a user / session, sometimes - but not always - with less privileges (e.g. it might be read only, or may perform create and update operations, but not delete operations). Typically Access Tokens do rotate. This is done to limit the risk of exposing a token to client side JavaScript, where it could be hijacked by third party scripts.

For example, Google Access Tokens are only valid for 1 hour and you must make a request using a Refresh Token (which does not rotate, and functions like a Session Token) to request a new Access Token every hour. 

NextAuth.js implements Access Tokens in sessions as a way to provide an identifier for client side operations that can be tracked by to a session, without exposing the Session Token itself (so that a Session cannot be hijacked by a third party script).

However, it is currently only a basic implementation in that the Access Token it exposes does not change / expire and it is not used for anything internally - it's more a placeholder around which you can build on and extend on to add your own functionality, to discourage people from exposing the Session Token client side.

In practice, if you have `/api/` endpoints in a Next.js app you should be able to access the session directly from them (or JWT directly, if you are using JSON Web Tokens to store session data) so you _probably_ don't need to use the accessToken.

An example of how you might want to use it, is to pass it to another service to allow it to make API requests to your service (e.g. as callback) so that it could do so securely on behalf of your user, without exposing information about the user or their session.

**Comment by kevinmachstudio** [comment]
@iaincollins thanks for the explanation! Just want a little bit more clarification on something. 

I was looking through the cookies for my site in the browser, and I noticed a logged in user's session token under the field `next-auth.session-token`. Is this expected or should this value be the access token value? You mentioned that session tokens are server side cookies so just wondering why I see it in the browser.

![image](https://user-images.githubusercontent.com/6373887/93906153-b3404a00-fcb0-11ea-8abb-195cbc8005bd.png)

**Comment by archywillhe** [comment]
@kevinmachstudio It's a http-only cookie! It's only "accessible" when you make a http call! So is all cool!

**Comment by kevinmachstudio** [comment]
awesome thanks guys

**Comment by asifsaho** [comment]
I am looking for the accessToken since I need it to request any data from backend. Where it is stored and how to access it from Frontend end?

**Comment by OxiBo** [comment]
I have been trying to implement next-auth authorization with Credentials provider and it looked like it worked: I receive session and get get access to it and shape the data the way I need. Ones I got the need to make a follow up request to my backend (where i use serverless) I do not know how to check if user is authorized in my backend API, I do not have access to access-token since it was not provided. How to I pass authorization test on the backend to fetch data?

**Comment by abhiblancos** [comment]
> I have been trying to implement next-auth authorization with Credentials provider and it looked like it worked: I receive session and have access to it and shape the data the way I need in the session and jwt callbacks in [...nextAuth].js. Though now when I have the need to make a follow up request to my backend (where i use serverless) I do not know how to check if user is authenticated in my backend API, I do not have access to access-token since it was not provided. How do I pass authorization test on the backend to fetch data?

Do let me know If you find any solution.

**Comment by JeremyXXXuuu** [comment]
@OxiBo You do have access to accessToken, you can store accessToken in next-auth session, every time you want to call your backend api with protetcted resources, you need to provide accessToken within the request header, and the resources provider(in this case is your backend) can check if its valid or not. Check out this example for how to do that in the jwt callback: : https://github.com/nextauthjs/next-auth-refresh-token-example/blob/57f84dbc50f30233d4ee389c7239212858ecae14/pages/api/auth/%5B...nextauth%5D.js#L67

**Comment by JorgeECN** [comment]
> @OxiBo You do have access to accessToken, you can store accessToken in next-auth session, every time you want to call your backend api with protetcted resources, you need to provide accessToken within the request header(it could be done on nextjs server side function), and the resources provider can check if its valid or not. Check out this example for how to do that in the jwt callback: : https://github.com/nextauthjs/next-auth-refresh-token-example/blob/57f84dbc50f30233d4ee389c7239212858ecae14/pages/api/auth/%5B...nextauth%5D.js#L67

And how can I handle it on a node.js API? for example, my next api sends the token to the node.js API, confirms that the access_token is "valid" and proceeds to send reply with the data from database...
I managed to send the access_token to the backend, but it only checks that the token is there, not if it's still "valid"

**Comment by JoeRoddy** [comment]
> Typically Session Tokens are fixed and do not change unless a user signs out, but in some applications they can rotate. For optimal security, they should not be readable by client side JavaScript (i.e. they are server side only cookies).

@iaincollins I'm trying to understand this a bit better. Could you explain what the security drawbacks are of a session token reaching the client?  

Is it that the user is now vulnerable to having their session token leak to an attacker somehow, via an XSS attack or something?

**Comment by shamun-khatri** [comment]
@iaincollins I think this needs to be open again and specify the differences between access token and session token. All the things mentioned and specified in this discussion feel outdated.

Please specify from where we get which token. I am having a very hard time sending the correct token to my other backend so I can authorize my APIs there.

Thanks
