### ISSUE TITLE
NEXTAUTH_URL ignored when Vercel System Environment variables are enabled

### ISSUE THREAD

**Issue by lklepner** [nextauthjs/next-auth#6943]
### Environment

Error occurs in Vercel, not locally

### Reproduction URL

none

### Describe the issue

My application uses wildcard subdomains which most OAuth providers do not support. For this reason I am using the NEXTAUTH_URL to configure a specific subdomain which is registered with the OAuth providers. This works when testing locally but when the code was deployed to Vercel the NEXTAUTH_URL value was ignored. Disabling Vercel's default System Environment Variables, which is an opt-out, restored the NEXTAUTH_URL functionality. Ideally users would not need to opt-out of Vercel's System Environment Variables in order to get the NEXTAUTH_URL value to function as intended.

### How to reproduce

1. Configure NEXTAUTH_URL
2. Configure an OAuth provider (I used Google)
4. Add console logs to `options.callbacks.redirect` outputting the values of `process.env.NEXTAUTH_URL` and `baseUrl`. 
5. Test logging in when running locally. The logged values will be the same.
6. Deploy to Vercel with System Environment Variables enabled and `NEXTAUTH_URL` defined in the environment.
8. Test in Vercel. The baseUrl will match the current hostname *not* the hostname defined in the NEXTAUTH_URL.
9. Disable Vercel's System Environment Variables and redeploy
10. The baseUrl value will match the NEXTAUTH_URL configured. 

### Expected behavior

Expecting the NEXTAUTH_URL value to be honored in Vercel even when System Environment Variables is enabled.

**Comment by yeuem1vannam** [comment]
I have the same problem and had to disable the `System environment variables` in Vercel app as well.

We develop an application under the micro-frontend architecture, where the `auth-app` handle the auth. We have to set the `NEXTAUTH_URL` of the `auth-app` to point to `gateway` (expected behavior) but also have to disable the `System environment variables` to make it works (unexpected)., Same problem when using `NEXTAUTH_URL_INTERNAL`

<img width="855" alt="image" src="https://user-images.githubusercontent.com/2409560/229974935-4d6c2c2b-7da4-4d0c-b8ac-bd13742b91b6.png">

**Comment by wouter173** [comment]
Can reproduce in nextauth 4.22.0 with next 13.3.0

**Comment by climber2002** [comment]
I got same issue next-auth 4.22.0 with next 13.3.0

**Comment by rokstrnisa** [comment]
I can confirm that this is still an issue.
