### ISSUE TITLE
useSession is breaking the first rule of hooks

### ISSUE THREAD

**Issue by mrtnbroder** [nextauthjs/next-auth#701]
https://github.com/nextauthjs/next-auth/blob/e6995d21cd1c7c0e701a305c91062ece83d48dfe/src/client/index.js#L145-L155

In the react docs it says in bold:

`Don’t call Hooks inside loops, conditions, or nested functions`

However, `getSession` is called conditionally. This could potentionally lead to issues.

https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level

**Comment by iaincollins** [comment]
Please use the issue template when reporting an issue.

Please also see the "[Read before creating a new issue!](https://github.com/nextauthjs/next-auth/issues/419)" post that is pinned.

If you have a specific example of a problem / and or alternative implementation you would like to suggest please feel free to raise a bug report and/or a Pull Request.

**Comment by mrtnbroder** [comment]
I read through your thread and I searched for an already existing issue for this, which I couldn't find. So I openend up an issue. I do see some issues involving the `useSession` hook though.

> If you have a specific example of a problem / and or alternative implementation you would like to suggest please feel free to raise a bug report and/or a Pull Request.

My suggestion would be to not break the first rule of hooks. I updated the comment to match your template.

I am pointing at a potential issue/bug (and it indeed is a bug) in your code here and you are closing it. If you don't appreciate comments on your code - fair enough (even though you stated otherwise in your thread). But I generally find it pretty rude to close an issue that simply lacked of your formal templating.

**Comment by iaincollins** [comment]
> I do see some issues involving the useSession hook though.

If you see issues caused by this and/or are willing to submit a solution for them it would be great if you could share that, beyond just alluding to something you think might potentially be a conceptual problem.

>  But I generally find it pretty rude to close an issue that simply lacked of a bit formal templating syntax.

This is a community project supported for free by people in their personal time and this is our community space you are posting in. Providing information we asked for so that we can help is very much part of that baseline level of expectation for using this space

We spend hours each month providing support and assistance for people, mostly responding to things that are not specifically defects in the software, but questions or conceptual issues (e.g. regarding authentication flows, cookie policy, browser behaviour, encryption, about React, etc).

As a general rule, a report of a defect without steps to follow which can be used to replicate a demonstrable actual problem is not actionable and will be closed.

**Comment by vashisth00** [comment]
Hey, did you receive any solution for this issue? Even I am facing this issue :/

**Comment by mrtnbroder** [comment]
@vashisth00 do you have an actual issue or are you just getting a linting error/warning?

**Comment by zanzlender** [comment]
Actual error... 

![image](https://user-images.githubusercontent.com/44570474/149843629-4979e46b-be52-4deb-bf24-f9c77f89aba7.png)

**Comment by balazsorban44** [comment]
You probably have a rogue/duplicate `react` installed. Either globally, or through `npm link` or similar.
