### ISSUE TITLE
On every page refresh session is always false

### ISSUE THREAD

**Issue by bmandl** [nextauthjs/next-auth#704]
Hello guys,
I am new to next.js and I really started to like it. I am getting used to migrate from express.js routing to next.js api routing (kind of messy, but I am getting there). Now, I am developing simple calendar app, where I want to show login page, if user is not logged in, and calendar with events, if user is logged in. Now, everytime I refresh my page, I see a login page for a short period of time, then session gets populated and I can see my calendar page. Am I missing some optimization here or anything else? Here is snipped of my code:
```
import { signIn, signOut, useSession } from 'next-auth/client';

const Home = () => {
const [session, loading] = useSession();
return (
    <>
      {session
        ? (
          <div className="calendar-container">
            <Calendar
              selectable
              localizer={localizer}
              events={events}
              onSelectSlot={handleTimeSelect}
              onSelectEvent={handleEventClick}
            />
          </div>
        )
        : (
          <>
            Not signed in
            {' '}
            <br />
            <button onClick={signIn}>Sign in</button>
          </>
        )}
};
export default Home;
```

And my [...nextAuth].js file, just copied from example:
```
import NextAuth from 'next-auth';
import Providers from 'next-auth/providers';

const options = {
  // Configure one or more authentication providers
  providers: [
    Providers.GitHub({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
    Providers.Google({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET,
    }),
    // ...add more providers here
  ],

  // A database is optional, but required to persist accounts in a database
  // database: process.env.DATABASE_URL,
};

export default (req, res) => NextAuth(req, res, options);
```

So any ideas, why is this happening to me? What should I do to prevent that, so when I refresh my page, I see Calendar page, because I am already logged in.

**Comment by iaincollins** [comment]
Hi @bmandl,

If you add a file `pages/_app.js`  [like the one in the example project ](https://github.com/nextauthjs/next-auth-example/blob/main/pages/_app.js) to your site, it should resolve this problem for you.

```js
import { Provider } from 'next-auth/client'

// Use the <Provider> to improve performance and allow components that call
// `useSession()` anywhere in your application to access the `session` object.
export default function App ({ Component, pageProps }) {
  return (
    <Provider session={pageProps.session} >
      <Component {...pageProps} />
    </Provider>
  )
}
```

This will allow your client side rendered page to inherit the session data from the server side rendering pass, so that you don't see a flash of content intended for users who are not signed in.

It will also mean the session state is shared between other pages in your site, so when a user navigates to a new page on your site the client won't need to wait to check the session again before displaying the new page.

This is a scenario where Single Page Apps are able to be much more responsive to user input and feel faster than traditional web applications because they can take advantage of things like session state already being stored in memory on the client.

**Comment by SagnikPradhan** [comment]
@iaincollins Weird issue, I have got a component and a page, `session` to seems to be always `undefined` in the component. But it works on the page. This is how my app component looks.
```ts
// _app.tsx
import { AppProps } from "next/app";
import { Provider as NextAuthProvider } from "next-auth/client";
import { GeistProvider, CssBaseline } from "@geist-ui/react";

const App: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <NextAuthProvider session={pageProps.session}>
      <GeistProvider>
        <CssBaseline />
        <Component {...pageProps} />
      </GeistProvider>
    </NextAuthProvider>
  );
};

export default App;
```
![Rest of the code is here](https://gist.github.com/SagnikPradhan/25eda6f5cd7a5f56f2cc4ec034b589d6)

**Comment by darrenbutcher** [comment]
@iaincollins Hey, encountering the same issue on page refresh with JWT (SSG/client-side). I notice a flash of my 'login' button even while authenticated in the header. 

I also have the same setup for `pages/_app.js` as you mentioned & similar components setup from the example repo. As noted in the following screens, on refresh the session is always `undefined`  & loading is always `true`, both when logged in & out. Tried to combat the flash, with a loading skeleton, however since loading is always true on refresh, I see the loading skeleton even when logged out. 

I tested the output with
`  useEffect(() => {
    console.log(session, loading)
  }, [session])`

Refresh while logged out:
![Screenshot from 2020-11-24 18-45-07](https://user-images.githubusercontent.com/146984/100160453-fe7c0200-2e85-11eb-82a0-1dfdc4a345d5.png)

Refesh while logged in:
![Screenshot from 2020-11-24 18-45-56](https://user-images.githubusercontent.com/146984/100160471-08056a00-2e86-11eb-946f-e387d46fef24.png)

I also tested this out with SSR with no issues but atm didn't want to opt in to SSR. Am I missing something or a concept on how this is suppose to work.
