### ISSUE TITLE
YandexProvider missing type definitions

### ISSUE THREAD

**Issue by azeek21** [nextauthjs/next-auth#7042]
### Question 💬

YandexProvider missing type definitions

### How to reproduce ☕️

1. Install next-auth
2. import YandexProvider
3. play with it a bit, you'll find out

### Contributing 🙌🏽
I am willing to help with this with a PR

**Comment by balazsorban44** [comment]
Here are the files. 

https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/yandex.js
https://github.com/nextauthjs/next-auth/blob/v4/packages/next-auth/src/providers/yandex.js

**Comment by azeek21** [comment]
@balazsorban44  I just noticed provider logo urls are different in `v4` and latest `main` . Are logo URLs in `main` branch auto generated ? 

So should I just go ahead and create `provider-logos` folder in `src/next-auth` and  add the logos. Then they will be automatically deleted and `provider.style.logo` attributes will be set or what ?

**Comment by mainaani** [comment]
@balazsorban44 mate can I ask a question that I have been stuck on since weeks? currently I have next_auth + fb provider in my app. I need to add user to database after users signin through fb, for this I also need either email or mobile num. Currently, the user session only returns the pic and user name.

```
 FacebookProvider({
      clientId: process.env.FACEBOOK_CLIENT_ID,
      clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
      scope: 'email,user_friends,user_gender,user_age_range,user_phone_number'
    })
```

 "next": "13.2.4",
    "next-auth": "^4.20.1",
