### ISSUE TITLE
LinkedIn Provider doesn't update profile information on subsequent logins

### ISSUE THREAD

**Issue by kblizeck** [nextauthjs/next-auth#7100]
### Provider type

LinkedIn

### Environment

Next 13.0.2
NextAuth 4.20.1
React 18.2.0
macOS Ventura 13.2.1
Node.js 16.13.1

### Reproduction URL

https://github.com/nextauthjs/next-auth/blob/f8675bc24563772502e0914a95ba25a9dd6428bb/packages/core/src/providers/linkedin.ts

### Describe the issue

Using Prisma adapter with Planetscale as our database

When a user first logs in using the LinkedIn Provider, their `name` and `image` are saved to the database
If a user changes their name/image on LinkedIn, their `name` and `image` are never pulled again/resaved from LinkedIn
Event `updateUser` is only sent when a user updates their email address - but should in theory be called from LinkedIn Provider every time, to ensure the name and image are kept synchronized.

I'm hooking in to the `signIn` event to update the DB every time a user logs in.

### How to reproduce

- Login to an app with LinkedIn Provider
- change your LinkedIn profile image or name
- Re-login to the app and see that image/name were not updated in db

### Expected behavior

`updateUser` should be called from LinkedIn Provider every time a user logs in, to ensure the name and image are kept synchronized.

**Comment by balazsorban44** [comment]
So this is actually on purpose.

NextAuth.js/Auth.js - when using a database - operates with the concept of [User and Account](https://authjs.dev/reference/adapters#models).

A User is created the first time you log in with any provider (LinkedIn in your case), then an Account is also created.

Since you **can** connect multiple Accounts (providers) to a single User, we could not just update the User, because you might not want to update it based on all accounts.

Updating the Account table on the other hand would be something we could update on re-login, for which we will need something like an `updateAccount` method in the [adapter interface](https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/adapters.ts).

This will be useful when we want to implement built-in refresh token rotation too.

For your use case, I believe `callbacks.signIn` is ideal for now, but there is an open PR #6959 where we will recommend the same, but using the `callbacks.session` method instead.
