### ISSUE TITLE
Error: "Can't resolve module 'next/headers'" on building the app

### ISSUE THREAD

**Issue by moo2u2** [nextauthjs/next-auth#7103]
### Environment

    System:
        OS: Windows 10 10.0.22621
        CPU: (24) x64 12th Gen Intel(R) Core(TM) i7-1255U
        Memory: 12.19 GB / 31.64 GB
    Binaries:
        Node: 16.19.1 - C:\dev\node-v16.19.1-win-x64\node.EXE
        npm: 8.19.3 - C:\dev\node-v16.19.1-win-x64\npm.CMD

Browsers: Firefox and Chrome

### Reproduction URL

https://github.com/moo2u2/next-auth-issue-6559

### Describe the issue

I believe this is the same / similar to https://github.com/nextauthjs/next-auth/issues/6559 which itself is from https://github.com/nextauthjs/next-auth/issues/5743

I have created a minimal reproduction of my current project's setup which can reproduce the issue both on build and run. It is using a [Sitecore JSS 20.x style setup](https://github.com/Sitecore/jss/tree/release/20.0.0/packages/sitecore-jss-nextjs), however all Sitecore functionality (with the exception of a few types) is mocked and included in the project. It is making use of [component-level data fetching in JSS Next.JS apps](https://doc.sitecore.com/xp/en/developers/hd/210/sitecore-headless-development/component-level-data-fetching-in-jss-next-js-apps.html) and next-auth is used in the single component included on the page.

You can read more about Sitecore JSS for Next.JS [in the Sitecore documentation](https://doc.sitecore.com/xp/en/developers/hd/200/sitecore-headless-development/sitecore-javascript-rendering-sdk--jss--for-next-js.html) or at [the SDK repo in GitHub](https://github.com/Sitecore/jss).

If anyone can assist I would be extremely grateful, as this is currently blocking us and we don't have the option of updating to NextJS 13 (as it is not compatible with the version of Sitecore and the Sitecore JSS sdk we are using).

### How to reproduce

Clone the project https://github.com/moo2u2/next-auth-issue-6559

Simply build the project

    npm run build

or start the project

    npm run dev

and browse to http://localhost:3000/

### Expected behavior

Project should build and run successfully. 
If the 3 environment variables are populated (not required to reproduce the issue) then user's session "name" property should be output on the page.

**Comment by balazsorban44** [comment]
It sounds like Sitecore JSS is obfuscating something in a way that makes our conditional `require` error here: https://github.com/nextauthjs/next-auth/blob/40261834111156b0df1318f5a9d8bd652387ff7f/packages/next-auth/src/next/index.ts#L121-L126

I don't have a clean solution from the top of my head, and I, unfortunately, don't think that this is a widespread/common enough issue for us to investigate any deeper.

To unblock you, what you can do instead is use [`patch-package`](https://www.npmjs.com/package/patch-package) and drop the condition from `next-auth`, since you will never have the `isRSC` condition evaluate to `true` in Next.js 12.

Although Next.js 13 has been out since 2022 October and did not introduce [any major breaking changes](https://beta.nextjs.org/docs/upgrade-guide) to the `pages` directory, so I would rather investigate if Sitecore could add support for it. Note, the new App Router (`app/`) is entirely opt-in and should not interfere with `pages`.

**Comment by moo2u2** [comment]
Thanks so much for unblocking us! 
For anyone else who happens across this, I have updated [my repo](https://github.com/moo2u2/next-auth-issue-6559) with the fix instructions / pre-fixed branch
