### ISSUE TITLE
Using an environment variable other than `NEXTAUTH_SECRET` causes a `NO_SECRET` error

### ISSUE THREAD

**Issue by nozomi-iida** [nextauthjs/next-auth#7106]
### Environment

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 3.32 GB / 31.28 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.asdf/installs/nodejs/16.13.0/bin/node
    Yarn: 1.22.17 - ~/.asdf/installs/nodejs/16.13.0/.npm/bin/yarn
    npm: 8.1.0 - ~/.asdf/installs/nodejs/16.13.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chrome: 110.0.5481.96
  npmPackages:
    next: ^12.2.4
    next-auth: ^4.19.2
    react: 18.2.0

### Reproduction URL

http://localhost:3000/

### Describe the issue

I use an environment variable called `JWT_SECRET` and pass it to the `[...nextauth].ts` file as the secret variable, but I get an error `NO_SECRET`.
I had no problems when using the `NEXTAUTH_SECRET` environment variable, but I want to use `JWT_SECRET` to be consistent with other projects.

### How to reproduce

[...nextauth].ts
``` .ts
export const authOptions: AuthOptions = {
  providers: [...],
  pages: {
    signIn: '/sign-in',
  },
  secret: process.env.JWT_SECRET,
  callbacks: {...},
  debug: false,
}
```

### Expected behavior

Remove `NO_SECRET` error.

**Comment by balazsorban44** [comment]
Looks like you maybe have a typo or did not set the environment variable correctly.

We only throw a warning if the secret is truly not set:

https://github.com/nextauthjs/next-auth/blob/2d907f0004d135d7a230022800805e069ac6493f/packages/next-auth/src/core/lib/assert.ts#L54

Falling back to `NEXTAUTH_SECRET` if you forgot to pass it https://github.com/nextauthjs/next-auth/blob/2d907f0004d135d7a230022800805e069ac6493f/packages/next-auth/src/next/index.ts#L26

Cannot tell more since there was no reproduction

**Comment by Ruoyu-Klaus** [comment]
I encountered a similar issue when it was in Dev env with no secret set

<img width="392" alt="image" src="https://user-images.githubusercontent.com/57642283/232842524-e1513d11-beb9-48cf-a168-abc877474b85.png">

**Comment by kachkaev** [comment]
Same here when passing secret via `AuthOptions` instead of `NEXTAUTH_SECRET` env (I’m on version 4.24.7). @Ruoyu-Klaus, have you found a solution?
