### ISSUE TITLE
Why custom encoder is needed for JWT signing to work as intended?

### ISSUE THREAD

**Issue by MelMacaluso** [nextauthjs/next-auth#716]
**Your question**
We noticed that with the out of the box JWT signing (I guess you are using JOSE package) we can't decode it from our backend as it provides an invalid signature, we had to manually do the signing etc. as follows: 

```js
///[...nextauth].js
  jwt: {
  encode: async ({ secret, token, maxAge }) => {
    const encodedToken = jwt.sign(token, secret, { algorithm: 'HS512' })

    return encodedToken
  },
  decode: async ({ secret, token, maxAge }) => {
    const verify = jwt.verify(token, secret)

    return verify
  },

  },

**What are you trying to do**
We would like to use the out of the box signing to avoid adding to the boilerplate.

**Comment by iaincollins** [comment]
Yeah we REALLY need to improve the docs for JWT options- and maybe simplify the (undocumented) options that are support.

I have a feeling API options we support are a bit more complicated than they needs to be, which is why it's not been documented yet, but at this point us just documenting what they are and how they work is probably a good idea.

The custom encode/decode functions were basically a lazy escape hatch to allow people to do any old thing they want in case they ran into issues like this.

**Comment by MelMacaluso** [comment]
Ah amazing thanks, maybe keep them so we can still do this (as didn't find any other way ahaha), hint: maybe there's an issue in using the secrets when it comes to jwt...

**Comment by pdevito3** [comment]
I'm running into this issue when authenticating to my .NET api as well (and yet to nail down the correct encode/decode customization to get it to work. I've never ran into this with other clients/libs. Feels weird that I can't just have next-auth put my token into an httponly+secure cookie and have the browser pass it along to the api as is.

@MelMacaluso I checked the docs for more details on this and I'm not seeing much of anything here. Did this augmentation ever happen and I just can't find the write up? Happy to post details here or in another ticket if it might help

**Comment by pdevito3** [comment]
details on my problem [here](https://github.com/nextauthjs/next-auth/discussions/5214) if it helps with context @iaincollins
