### ISSUE TITLE
CLIENT_FETCH_ERROR unexpected end of JSON input 

### ISSUE THREAD

**Issue by hect1c** [nextauthjs/next-auth#7200]
### Environment

`next: 13.1.7-canary.32` (also tried with latest)
`react: 18.2.0`
`next-auth: latest`

### Reproduction URL

https://github.com/hect1c/nextjs-sentry-nextauth-lambda-error

### Describe the issue

I'm getting the `CLIENT_FETCH_ERROR unexpected end of JSON input` when loading the site. It's a bit odd as I was able to isolate the issue to my `next.config.js`. It appears it's related to my `@sentry/nextjs` configuration. When I have the `withSentryConfig` set I get this error from next auth, but when I remove it no error and `next-auth` is happy. I've tried to debug `next-auth` to try and determine why it's giving me this error but to no avail. I definitely have my `NEXTAUTH_URL` and `NEXTAUTH_SECRET` set properly in my function.

I've tried different versions across next, next-auth and sentry but going back too far with my `@sentry/nextjs` config is just not an option. 

Though the issue stems from `@sentry/nextjs` I've decided to post here first as the error is coming from `next-auth` so I was hoping you would be able to point me in the right direction as to what may be causing this as I have not been able to figure it out aside from just removing withSentryConfig and setting`module.exports = nextConfig` in the repro. I'm just not sure why a sentry config would affect next-auth in any way.

### How to reproduce

It's detailed in the ReadME file in the repro

- Clone project
- Install dependencies
- Build
- Deploy

There is one caveat that the deployment is done to AWS Lambda thus an AWS profile / credentials will be required to be able to get this running. I understand this may be challenging as an OSS project but this is currently where and how I am getting the issue. I could try Vercel but I noticed Vercel has a sentry integration which possibly may not render this issue. If required I can try and set it up via Vercel to see if the issue would persist

### Expected behavior

What should of happened is no error is displayed since I have the required environment variables and `nextauth` path setup correctly.

**Comment by hect1c** [comment]
The issue was with `@sentry/nextjs` they seem to be doing something with the api routes in webpack that would cause `next-auth` to break, details and solution that worked for me here: https://github.com/getsentry/sentry-javascript/issues/7797#issuecomment-1501122013

**Comment by MateusSantosFonseca** [comment]
Hey, although this issue is closed, I thought about adding this comment as I was experiencing this error but I wasn't using Sentry at all.

What fixed my problem was adding:    

`binaryTargets = ["native", "linux-arm64-openssl-1.0.x"]`

on schema.prisma, like that:
```
generator client {
    provider      = "prisma-client-js"
    binaryTargets = ["native", "linux-arm64-openssl-1.0.x"] //Just added
}
```

I noticed that after looking for `/api/auth/[...nextauth]` logs on SST console, which was bringing this error:
![image](https://github.com/nextauthjs/next-auth/assets/45724993/0fc919f6-b49f-4237-96ea-2959ea622e9d)

I'm not 100% sure how it is related, but after I added this line of code on my prisma's schema, it started working...

My stack is composed of: SST, Prisma w/ Postgres, and React next app with TS and next-auth (bootstrapped by T3).
