### ISSUE TITLE
Updating from 4.19.1 to 4.22.1 breaks getSession

### ISSUE THREAD

**Issue by SteveSonoa** [nextauthjs/next-auth#7438]
### Environment

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 6.62 GB / 15.85 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.19041.1566

### Reproduction URL

https://www.ridetheteacups.com

### Describe the issue

In order to use the new `update()` method from `useSession()` in my react app, I updated `next-auth` from `4.19.1` to `4.22.1`.

Previously, I had been using `getSession({ req })` on my server for session information. Now I need to use `getServerSession(req, res, authOptions)` instead. That's totally fine - except that getSession no longer functions as intended. The server now throws a `CLIENT_FETCH_ERROR` error, which sent me on a bit of a wild goose chase to find the actual issue (because my NEXTAUTH_URL env variable was set appropriately).

I believe somewhere between 4.19.x and 4.22.x, there should have been a major semvar upgrade to reflect the breaking change.

Even if we immediately close this, I'm mostly interested in documenting this to help others who will troubleshoot the same issue. I didn't see a more appropriate classification than `bug` to file it; apologies if it needs to be moved.

### How to reproduce

Setup any project with next-auth v4.19.x and run getSession on the API route. Then update that project to at least v4.22.1.

### Expected behavior

Either getSession continues to function as intended, or a new major version is released to reflect the breaking change.

**Comment by Naddiseo** [comment]
@SteveSonoa, does it work on 4.20.1 ? I'm having a similar issue once I move from 4.20.1 to 4.21.0

**Comment by monastyrskiiden** [comment]
"next-auth": "^4.22.0",
I'm facing the same issue. I was using getSession to get jwt token from the session and set it to the Authorization header inside my axios request interceptor as suggested in this issue https://github.com/nextauthjs/next-auth/discussions/3550#discussioncomment-1898233
Now this functionality is completely broken because getSession only runs on the client side instead of the server-side and client side. Such changes should be considered breaking changes at least. We still need a way to get session data both on the server and a client for cases like mine.

**Comment by balazsorban44** [comment]
@monastyrskiiden https://github.com/nextauthjs/next-auth/issues/7438#issuecomment-1534264451

**Comment by daliusd** [comment]
Here is next-auth PR in my project that fails because of this if you need reproducible case: https://github.com/daliusd/apskaita/pull/1048

**Comment by daliusd** [comment]
@SteveSonoa thanks for suggested fix. It works.

**Comment by Naddiseo** [comment]
> @SteveSonoa, does it work on 4.20.1 ? I'm having a similar issue once I move from 4.20.1 to 4.21.0

Just in case it helps someone else:

It turns out my problem is that getSession changed between the releases and doesn't use the same `callbacks` that I supplied in the `NextAuth` default function. I've now refactored so that the `callbacks` are in the `NEXT_AUTH_BASE_OPTIONS` and I'm now using `getServerSession` instead

**Comment by tiagopiccinin** [comment]
simular issue here... 

I had to downgrade from version 4.22 to 4.17. 

The functions getCsrfToken and getSession were returning undefined or null on server side.
