### ISSUE TITLE
Using Next-Auth with wildcard domains

### ISSUE THREAD

**Issue by junaid33** [nextauthjs/next-auth#744]
**Your question**
I'm using Next-Auth with Prisma and everything is working smoothly. My question is how can I implement Auth using wildcard domains. Each user will have their own subdomain host like junaid.myapp.com. Their login and JWT should only work on that domain. Is this possible with Next-Auth?

**What are you trying to do**
Each signed up user will have their own subdomain to sign-in to. Their login should not work on other subdomains.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by SharadKumar** [comment]
Related #600

**Comment by kripod** [comment]
@junaid33 May I ask how you've implemented user-created wildcard domains with Next.js? I found no official documentation for that and would be highly curious about your approach.

**Comment by junaid33** [comment]
@kripod Here is what I used for reference:

https://vercel.com/blog/wildcard-domains
https://github.com/vercel/static-fun  -  uses faunaDB as backend
https://github.com/leerob/nextjs-multiple-domains

From what I understand, in the index page, we include this code:


```
export async function getServerSideProps({ req, res }) {
  res.setHeader(
    'Cache-Control',
    'public, s-maxage=1, stale-while-revalidate=59'
  );

  return {
    props: {
      host: req.headers.host
    }
  };
```

We can get the host here from the URL and fetch data using the host name from Prisma or any API.

**Comment by kripod** [comment]
@junaid33 Awesome, I’ve missed that blog post. Thank you for the tip, I appreciate it!

**Comment by skilesare** [comment]
I've tried to address this here: https://github.com/skilesare/next-auth/commit/86ea3de736d566737c2e3d9082480e30309fd5fe

It may need some changes....and I only really focused on the session call back because I needed to get some data based on the domain in the session, but the pattern should be easy to follow for the other callbacks. Basically the request (req) just needs to be passed to these callbacks so that you can key in on the domain/sub domain. The other potential gotcha is the http vs https so if anyone has a suggestion for that, let me know.

If any one wants to walk me through how to get this set up so that it can eventually be pulled in, let me know as well...haven't contributed to projects this big before and don't want to step on any toes.
