### ISSUE TITLE
why is `jwt.decode` used instead of `jwt.verify`?

### ISSUE THREAD

**Issue by archywillhe** [nextauthjs/next-auth#748]
**Your question**
I was going through the source, and noticed there are a few places where `jwt.decode` is used instead of `jwt.verify`:

for example, at `server/routers/sessions.js` line 22:

```
  const decodedJwt = await jwt.decode({ ...jwt, token: sessionToken })
```

doesn't `jwt.decode` only decodes and not verifies the token (i.e. unlike `jwt.verify`) and shouldn't `jwt.verify` be used for example in `server/routers/sessions.js`? 

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
If you look at the source for [decode](https://github.com/nextauthjs/next-auth/blob/main/src/lib/jwt.js#L53) function, you can see it handles both verification and optionally encryption.

By default, NextAuth.js uses JSON Web Tokens that are signed but not encrypted, to reduce the token size; to help prevent cookies from hitting the 4 KB per domain limit in browsers. If the `jwt.encrypted` option is set to true, then encryption is also enabled.

The decode function abstracts this so that the code elsewhere doesn't need to worry about what options are enabled.

Additionally, the `encode` and `decode` methods can be specified as options, so people can use entirely custom schemes for encoding and decoding JSON Web Tokens, including methods that may not be RFC compliant but are compatible with vendor software or other needs, such as using compression to reduce token sizen.

So, we don't assume the cookies are _only_ signed (as they might also be encrypted) and we also assume someone might have specified custom encode / decode functions.

**Comment by archywillhe** [comment]
Thanks for writing back!

I see! I was mistaken and thought you guys were using the jsonwebtoken by Auth0 which didn’t hv verification in jet.decode. 

Also super cool to know the implementation comes with the decryption in mind & even supports a custom encode & decode! This library rocks!
