### ISSUE TITLE
How can I implement JWT authentication with another backend like NestJS

### ISSUE THREAD

**Issue by izundo-viennv** [nextauthjs/next-auth#753]
**Your question**
Currently I don't know how to implement JWT authentication with from another backend (for example I'm implementing JWT Authentication on NestJS and I don't know how to integrate with next-auth. It really doesn't flexible)

**What are you trying to do**
Integrate NestJS JWT Authentication with next-auth

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by vv1n3k** [comment]
You can perform api call with oauth token to your api backend in nextauth signIn callback.
Then in nestjs api based on auth_token call for user to oauth provider
This is sample, but not well written overview how to achieve it: 
https://gist.github.com/SumitGA/97d77c39be5c370c906972e14e809cdd

then you can follow my question: https://github.com/nextauthjs/next-auth/issues/745 
Theoretically JWT token to authenticate user in you api can be store in nextauth JWT Token. Still I am not sure if it's 100% safe approach however it seems legit with encryption flag.

**Comment by jamiedavenport** [comment]
This [article](https://arunoda.me/blog/add-auth-support-to-a-next-js-app-with-a-custom-backend) gives a good approach.

The approach I'm thinking:
* On your API have `/token/<provider>` endpoints that validate the provider token and exchange that for your own JWT access token.
* For all other endpoints provide your token (stored in the NextAuth session)

The issue I have with this is the potential maintenance overhead for supporting lots of providers (which might not be that much with Passport).

I have a suspicion that Auth0 might be a better method (if you're not opposed to using experimental tech) because it handles all of the specific OAuth provider tokens behind the scenes and you can focus on your API logic instead of building all the `/token/<provider>` endpoints.

https://github.com/auth0/nextjs-auth0
