### ISSUE TITLE
Allow set-cookie from credentials provider

### ISSUE THREAD

**Issue by bscaspar** [nextauthjs/next-auth#756]
I am using two provider options - Facebook and a custom credentials provider that uses .net cookie auth. For the credentials auth, in an attempt to make this work with next-auth, I am making the auth request in the authorize provider option. The response includes a set-cookie header. It doesn't look like it's currently possible to forward this to the client, like the set-cookie headers are for oauth and email providers.

Is this something that could be supported in the future? Worth investigating more?

**Comment by dolie** [comment]
+1
I need this feature, as the datas that I add to next-auth's cookie are bigger than 4ko. So I must use another cookie to split the size.

**Comment by leopku** [comment]
+1

Need this feature too.

But my project was little different.

My project was mixed by nextjs+next-auth(with custom oidc provider)+golang+keycloak.

* Original working process:
`/auth/openid-connect/authorize`(golang) -->  keycloak --> `/auth/openid-connect/access_token`(golang)

* After adding next-auth, process was broken at the last step:
`/api/auth/signin`(next-auth) --> `/auth/openid-connect/authorize`(golang) --> keycloak --> `/api/auth/callback/oidc`(next-auth) -x-> `/auth/openid-connect/access_token`

The reason was golang middleware would check cookie/session in context.

Could this awesome project add an option to pass cookie while access `/auth/openid-connect/access_token`?
