### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by KNIF** [nextauthjs/next-auth#797]
**Summary of proposed feature**
Add dark theme to all pages (login page, error pages, ...).

**Purpose of proposed feature**
Make the entire UI look better with a opt in dark theme.

**Detail about proposed feature**
Add a `darkTheme` boolean to the configuration that is disabled by default.
The developer can enable it and then all the pages are dark themed.

**Potential problems**
Rewriting most of the UI code's styles I guess.

**Describe any alternatives you've considered**
Just leave it like it is.

**Additional context**
None.

*Please indicate if you are willing and able to help implement the proposed feature.*
If I have time I will.

**Comment by iaincollins** [comment]
I think this is a great idea and have been mulling it over but not captured it anywhere!

Having it auto by default and able to be forced on or off seems reasonable.

The instructions for how to edit the CSS aren't obvious - it's can be bit of a hassle to test and mean rebuild the lib on each change due to the way the CSS bundled for compatibility with different peoples build systems - so maybe that's something we can work on improving.

Happy to keep this in mind the next time I update the UI for the built-in pages!

**Comment by balazsorban44** [comment]
@KNIF thanks for this request, I think I found a way to implement this with a very low amount of code, and this will be soon available in the next `canary` release!

To try it out, you don't need to do anything. If you are on a system that supports the [`prefer-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media query, the pages will be dark now, if your system prefers dark themes. You can force a dark or light theme by setting the new `theme` option in `NextAuth`. It can take one of these values `auto`, `light` or `dark`.

**Comment by balazsorban44** [comment]
@iaincollins do you think I should move this under `options.pages.theme` or is it ok to leave this top-level?
