### ISSUE TITLE
Encode accessToken and refreshToken in database

### ISSUE THREAD

**Issue by stefanbuck** [nextauthjs/next-auth#800]
**Your question**
Both the `accessToken` as well as the `refreshToken` are stored in plain text in the database. Isn't this a potential security issue? 

**What are you trying to do**
I would like to be able to encode both `accessToken` and `refreshToken` in the database to ensure a database leak doesn't reveal the actual values. I assume a custom provider is one possible option to solve this, right? Would you accept a PR to make this a core feature of next-auth?

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
This would be ideal yes, although is challenging, especially in a non SaaS solution. I'm happy to accept this as a core feature but it's likely a significant undertaking.

Challenges include that it needs to be fast and reversible - it can't be hashed and the keys used to encrypt and decrypt it could never change, or individuals users would have manually revoke access to services like Google and re-authorize the app to issue a new Refresh Token (as it is only provided on initial login with some providers).

It needs to be easily reversible for any user without them being logged in so that Access Tokens can be used for server side jobs / off line tasks for which the scope of Access Token has permission, and so that it can be returned to the client.


We could use a separate key in the database to track the encryption method which would mean a database schema change (implemented across all databases and functional with all adapters) *or* a config option for the encryption method (so people can continue to use older methods if we change the mechanism in future) and updated documentation, so is likely

You could auto-generate keys, but then the only place to store them would be. in the same database, so it would need to be encrypted. Using the primary secret to generate all other secrets (and store them encrypted in the database) is a viable option but would require some review of the onboarding process (as well as provision of a dedicated table to store configuration info). 

Obviously if that secret (or env vars ,in any scenario) are compromised the entire database is compromised, but I don't see that anything can be done about that; ultimate the keys need to be able to be encrypted and decrypted (and send to the client decrypted). Obviously this is of value, but it's a different situation to passwords.

**Comment by stefanbuck** [comment]
Thanks for your detailed response. You pointed out many things I haven't thought about and I see why this is much more complicated than it sounds. I'm afraid I can't help much with this since this is not my specialty. I like the idea of not saving tokens by default. My gut feeling is that most users of this lib need to deal with tokens anyway. Should I raise a separate issue to make this new behaviour actionable?

**Comment by stefanbuck** [comment]
I thought about this issue for a bit and I came to the conclusion that maybe all is needed is a hook into the data before persisting the data in the database. This would also unlock other requested features:

- Access and Refresh tokens not updating #854
- How to persist custom fields in database? #613

How does this sound @iaincollins?
