### ISSUE TITLE
google auth connect 1 user to 2 accounts when user back

### ISSUE THREAD

**Issue by guiaramos** [nextauthjs/next-auth#828]
**Describe the bug**
first sign in with google account A and click on to go back and select google account B links the user from account A to account B, please see the screen shots.

On live demo its working so I think it could be miss config, mine is as follows:

[...nextauth].ts
```ts
import NextAuth, { InitOptions } from 'next-auth';
import Providers from 'next-auth/providers';
import { sendVerificationRequest } from '@libraries/sendVerificationRequest';

const options: InitOptions = {
  providers: [
    Providers.Email({
      from: process.env.NEXT_PUBLIC_EMAIL_FROM,
      sendVerificationRequest
    }),
    Providers.Google({
      clientId: String(process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID),
      clientSecret: String(process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET),
      // @ts-ignore
      authorizationUrl:
        'https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline&response_type=code'
    })
  ],
  database: {
    type: 'postgres',
    database: String(process.env.NEXT_PUBLIC_DATABASE_DATABASE),
    host: String(process.env.NEXT_PUBLIC_DATABASE_HOST),
    port: Number(process.env.NEXT_PUBLIC_DATABASE_PORT),
    username: String(process.env.NEXT_PUBLIC_DATABASE_USERNAME),
    password: String(process.env.NEXT_PUBLIC_DATABASE_PASSWORD),
    synchronize: false // for customize db
  },
  pages: {
    signIn: '/',
    signOut: '/login',
    error: '/auth/error', // Error code passed in query string as ?error=
    verifyRequest: '/verify', // (used for check email message)
    newUser: '/create/profile' // If set, new users will be directed here on first sign in
  },
  session: {
    jwt: false
  }
};

export default (req, res) => NextAuth(req, res, options);

```

**Steps to reproduce**
1. Go to google sign in
2. Log in
3. Click to go back on browser btn
4. Select another google account from the list
5. The 1 and 2 account are now connected to same user

**Expected behavior**
It should create another user instead of connecting to the previous user

**Screenshots or error logs**
User create when sign in with Account A:
![Screen Shot 2020-11-04 at 3 20 41 PM](https://user-images.githubusercontent.com/49703106/98076372-7bccdc00-1eb1-11eb-9219-04c212d67c63.png)

Accounts when click back and select Account B:
![Screen Shot 2020-11-04 at 3 21 13 PM](https://user-images.githubusercontent.com/49703106/98076450-9c953180-1eb1-11eb-9352-393856794ee2.png)

**Additional context**

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Hi there,

Thank you for raising this and providing detailed descriptions and screenshots!

This is enormously helpful and very much appreciated!

Interestingly, this is actually intended behaviour, It's a consequence of a design intended to support account linking but it's not been fully built out yet.

When using a database, if you are already signed in and then sign in with another OAuth account (with the same provider, or with a different provider) the accounts are linked rather than a new account being created.

I understand it's confusing and fair to describe it as unexpected - it's largely undocumented, and it's functionally incomplete; linking is not explicitly behaviour and there is no option to unlink accounts.

The intention is to explicitly support linking and unlinking, which was a feature of version 1.0 (the original version designed for Express that used PassportJS); the version designed for Serverless and  Next.js API routes does not have pages for linking/unlinking yet.

Until we do have explicit pages for linking and unlinking we could do something like have the sign routes page redirect to the homepage if you are already signed in, to effectively disable this feature until it's more explicitly supported.

**Comment by guiaramos** [comment]
Hi!!

Thank you for your answer and the amazing work you guys are doing!

Ohh that makes sense!! actually on our app this behaviour should not happen. but I think it depends on each case...

Is good to know that and I will close the issue and post our way to mitigate this:
```ts
const handleWindowClose = () => {
    client.clearStore();
    signOut({ callbackUrl: `${callbackUrl}login` });
};

React.useEffect(() => {
    window.addEventListener('beforeunload', handleWindowClose);
    return () => {
      window.removeEventListener('beforeunload', handleWindowClose);
    };
});
```
