### ISSUE TITLE
Drizzle Adapter: Module not found: Can't resolve './lib/mysql.js'

### ISSUE THREAD

**Issue by pingustar** [nextauthjs/next-auth#8299]
### Environment

  System:
    OS: macOS 13.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 3.56 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.6.6 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 115.0.5790.170
    Safari: 16.6

"@auth/core": "^0.11.1",
"@auth/drizzle-adapter": "^0.3.0",
"@vercel/postgres": "^0.4.1",
"next": "^13.4.13",
"next-auth": "^0.0.0-manual.83c4ebd1",

### Reproduction URL

will add soon

### Describe the issue

using pnpm I get the following error when running dev server:

```
- error ./node_modules/.pnpm/@auth+drizzle-adapter@0.3.0/node_modules/@auth/drizzle-adapter/index.js:18:0
Module not found: Can't resolve './lib/mysql.js'
```

I am not using mysql, but pg ... 

### How to reproduce

will add soon

### Expected behavior

not throw

**Comment by neyasov** [comment]
+1

**Comment by edereagzi** [comment]
+++

**Comment by montnyc** [comment]
+1, same issue + setup

**Comment by balazsorban44** [comment]
@jrysana thanks for the research, I can confirm! Not sure what happened, will do a new release 🙏

**Comment by balazsorban44** [comment]
Fix is out in `0.3.1`! :tada: 
You can verify that the `lib` directory is correctly included again:
https://www.npmjs.com/package/@auth/drizzle-adapter/v/0.3.1?activeTab=code

It was an incorrect cache configuration in our Turborepo config.

**Comment by montnyc** [comment]
@balazsorban44 honest question - why was my +1 post marked as spam?

Will try the fix later today!

**Comment by balazsorban44** [comment]
@montnyc, thanks for asking!

Comments like that add no value to the maintainers and only create noise, making real issue discussions hard to track. You can just 👍 the original description if you want to indicate that you have the same problem. Or you can subscribe to the issue by the subscribe button, instead of adding that comment if you just want updates.

same category comments are "are there any updates" (if there was, it would be posted), "same issue" (see above), "doesn't work for me either" (post a minimal reproduction, doesn't work isn't actionable).

Also, usually tagging maintainers have the opposite effect of gaining more visibility. It might come off as pushy and in most cases are totally unnecessary. Maintainers are aware of the issue already.

Good to remember for any future comment on open source projects!

Hope this helps and make sense! 🙏💚
