### ISSUE TITLE
[UntrustedHost]: Host must be trusted. What does this mean?

### ISSUE THREAD

**Issue by Arinautic** [nextauthjs/next-auth#8327]
### What is the improvement or update you wish to see?

Upon looking at the documentation for this error, it says Todo. There is also pretty much nothing online about this. It'd be great if this could be added to the documentation.

### Is there any context that might help us understand?

I've been playing around with Auth.js on my SvelteKit project, and everything is going perfect, until I build for production. When the app is built for production, as soon as I try to access the page, I get the error: 

[UntrustedHost]: Host must be trusted. 

Since there is pretty much nothing about it anywhere, I'm not sure what my next course of action is. I have the .env variable pointing to my URL, and everything works in the DEV environment. 

### Does the docs page already exist? Please link to it.

https://authjs.dev/reference/core/errors#untrustedhost

**Comment by symbolicsorcerer** [comment]
Copying this over from the other thread, here is my first stab at better understanding the situation:

> https://medium.com/@iamxali/unveiling-vulnerabilities-host-header-injection-in-oauth-functionality-4ec80557ada7
> https://hackerone.com/reports/317476
> If I understand correctly, an attacker can give someone a specially-crafted link that looks like an oauth-style form for a > given provider, but actually sends the token to an attacker-controlled domain.

> So does this mean basically that the oauth provider should be validating the host? And therefore you just need to confirm whether the provider does this or not, e.g. Google probably does validation?

However, judging from @balazsorban44's most recent comment, the validation should be happening on the hosting provider's side, so I think I may be missing something.

**Comment by zemunkh** [comment]
You need to update or add these in your environment variables as following:

In .env.production or` env.local `files

```
NEXTAUTH_URL=http://YOUR_LOCAL_OR_DEPLOYED_HOST_URL:HOST_PORT
AUTH_TRUST_HOST=http://YOUR_LOCAL_OR_DEPLOYED_HOST_URL:HOST_PORT
```
Results be like:

```
NEXTAUTH_URL=http://192.152.1.1:3000
AUTH_TRUST_HOST=ttp://192.152.1.1:3000
```

**Comment by EnablingLogic** [comment]
The code suggests that `AUTH_TRUST_HOST` should be a boolean, not an URL. The `trustHost` option in `@auth/core` will be set to `true` when `AUTH_TRUST_HOST` is set and `true`. It also looks at other environment variables, like `AUTH_URL`.

**Comment by phil-w** [comment]
I was trying to test my production build (dev worked fine) on a local machine and hit this problem. All I needed to do was to add the domain of the local dev site, like so:
~~~
 AUTH_TRUST_HOST=http://localhost:4173/
~~~
I played with trustHost also, but that didn't seem to matter either way.

**Comment by zemunkh** [comment]
This value should be boolean. I missed that.

` AUTH_TRUST_HOST=TRUE`

**Comment by ndom91** [comment]
TLDR; Enable `AUTH_TRUST_HOST=true` if yuo're running in Docker, or behind Nginx, etc.

This issue stems from the issue of whether or not the node server should trust the values it gets from a reverse proxy thats potentially infront of it.

So for example, if you have nginx, or Vercel or Cloudflare taking your request for `app.company.com` and terminating SSL there, and then forwarding the request on to the node process runnign your app it'll have the headers and metadata of the reverse proxy (like `origin=http://localhost:8080` instead of `origin=https://app.company.com`). That's why they then include a header like `x-forwarded-for` which passes on the original origin. 

This env var basically tells auth.js to trust this. It is set to `true` by default if we detect that we're being run on Vercel, or in Cloudflare pages, among some other scenarios (See: `packages/core/src/lib/utils/env.ts:32`).

**Comment by biladinn** [comment]
Adding AUTH_TRUST_HOST=TRUE fixed it for me...
