### ISSUE TITLE
Cannot Sign in using X (Twitter) on mobile devices (iOS)

### ISSUE THREAD

**Issue by ksuhara** [nextauthjs/next-auth#8444]
### Environment

https://next-auth-example.vercel.app/

### Reproduction URL

https://next-auth-example.vercel.app/

### Describe the issue

I have developed an app using next-auth and enabled twitter sign in. The app works fine with my laptop but not with my iPhone, and I found the same issue with the official live demo.
I can sign in to [https://next-auth-example.vercel.app/ ](https://next-auth-example.vercel.app/ ) with my laptop (Macbook Air) but not with my iPhone.
I keep getting this error below. "Request canceled from preloader"

![IMG_9989](https://github.com/nextauthjs/next-auth/assets/45842611/d2e75023-d703-48d0-9047-715fb01d46a3)

### How to reproduce

- Access [https://next-auth-example.vercel.app/](https://next-auth-example.vercel.app/) with your mobile device.
- Try sign in with Twitter

My Twitter App version is 10.3.2

### Expected behavior

Able to sign in as laptop

**Comment by balazsorban44** [comment]
This is a very mystical error, and I'm not even sure if it is caused by some recent unknown changes by Twitter/X, or something related to iOS. A quick Google search suggests that this error happens outside `next-auth` context too, so unfortunately until it's verified that NextAuth.js is responsible here (and consistently possible to reproduce), we cannot do much about this. Feel free to open a new issue when you have a consistent reproduction. :pray:
