### ISSUE TITLE
Next-Auth + App Router - Is it Production-Ready ?

### ISSUE THREAD

**Issue by NickDelta** [nextauthjs/next-auth#8486]
### Question 💬

Hi all👋

We are in the process of developing a new front-end for our new series of products. We have chosen Next.js as our framework and currently this is our setup (from package.json) :

```
  "dependencies": {
    "@types/node": "20.5.4",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "eslint": "8.47.0",
    "eslint-config-next": "13.4.19",
    "jwt-decode": "^3.1.2",
    "next": "13.4.19",
    "next-auth": "^4.23.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "5.1.6"
  }
```

Currently, we are debating whether we should start development with the classic Page Router which is more battle-tested or with the new App Router. What troubles us is that we have seen lots of issues here on the project's issue tracker such as:

- #7522
- #7558
- #6642 

From what I've read and understood is what PaulWild summarizes on their issue:  

_" The app directory feature of Next.js does not allow the cookies to be updated on the server. This means that any usages of getServerSession that would trigger a refresh token rotation as described in the docs would not set the new access token / refresh token / expires time in the next-auth cookie. "_

This means that we cannot properly use the next-auth hooks (like getServerSession) in React Server Components (RSC), probably affecting the session management of the application.

We would appreciate everyone's opinion on the following:

- Would you recommend using App Router for a production-ready frontend that uses next-auth or do you think that there might be issues ?
- If you do recommend App Router, then by your current experience is there something we should be careful in the design of the app ?
- From what we're reading, the next major release of auth.js (v5 - #7443 ) will make the library more App Router friendly. Do we have an estimation of when it will be released ?

Thank you a lot for your time ! 💯

### How to reproduce ☕️

No reproduction needed for this question.

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR

**Comment by balazsorban44** [comment]
Yes, it is production-ready. It's been for a while. Related thread on Twitter: https://twitter.com/nextauthjs/status/1689599931810549760

NextAuth.js + App Router is absolutely battle-tested.

Regarding token rotation, it's been a hard-to-solve problem for a while.

The current status quo is that it might be very difficult to solve without having some kind of cache/DB to store sessions, since token rotation uses OAuth `refresh_token`s which can only be used once. It's been difficult to solve holistically in Pages Router too, where even multiple open tabs could cause an unwanted race condition. We keep investigating how to solve this issue for now.

If you have any other issues, please report it as a bug with a minimal reproduction.

The linked PR will absolutely make the DX nicer, but I don't have an ETA.

**Comment by dimash-git** [comment]
But why then JWT token rotation does not work as expected causing whole application to break in Next.js 13 App router?
