### ISSUE TITLE
MongoDB is missing indexes

### ISSUE THREAD

**Issue by damieng** [nextauthjs/next-auth#886]
**Describe the bug**

The MongoDB collections created by NextAuth.JS are missing indexes necessary to provide fast access via the methods in typeorm.js, specifically:

- Session lookup by sessionToken
- User lookup by email
- Account lookup by userid, providerId and providerAccountId
- VerificationRequest lookup by token

**Steps to reproduce**

Run a query similar to the ones in typeorm.js inside MongoDB Compass but add `.explain()` to the end, e.g.

`db.users.find({ email: 'damieng@gmail.com' }).explain()`

And you will see in the queryPlanner result and see something like this:

```
winningPlan: 
 { stage: 'COLLSCAN',
  filter: { email: { '$eq': 'damieng@gmail.com' } },
  direction: 'forward' },
```

Which indicates it is scanning every single document looking for a match (COLLSCAN).

**Expected behavior**

Running this query should instead produce a result such as:

```
     winningPlan: 
      { stage: 'FETCH',
        inputStage: 
         { stage: 'IXSCAN',
           keyPattern: { email: 1 },
           indexName: 'email_1',
           isMultiKey: false,
           multiKeyPaths: { email: [] },
           isUnique: true,
           isSparse: false,
           isPartial: false,
           indexVersion: 2,
           direction: 'forward',
           indexBounds: { email: [ '["damieng@gmail.com", "damieng@gmail.com"]' ] } } },
```

The presence here of IXSCAN indicates a fast index-scan.

**Additional context**

The indexes required are:

- `db.sessions.createIndex({sessionToken:1}, {unique: true})`
- `db.users.createIndex({email:1}, {unique: true})`
- `db.accounts.createIndex({userId:1, providerId: 2, providerAccountId: 3}, {unique: true})`
- `db.verificationRequest.createIndex({token:1}, {unique: true})`

I can add these to a PR if somebody can let me know where they should go.

**Comment by iaincollins** [comment]
Hi there,

1. Are you seeing no indexes / unique constraints on fields at all in MongoDB?

2. Can you confirm if seeing this behaviour even after connecting to a MongoDB instance with the `sync` option?

e.g. `mongodb://username:password@127.0.0.1:27017/nextauth?synchronize=true`

**Comment by iaincollins** [comment]
We are still missing some automated tests to check this, but FYI I checked this manually and it seems to be working as intended, as long as synchronize=true is specified as part of the initial collection set up.

I think the issue is that it's less obvious that you need to connect with the `synchronize` option to a document DB to ensure the indexes get created (as with a relational / SQL DB it just fails completely if there is no schema defined, but if it's MongoDB it still seems to work, it just doesn't actually create any indexes).

I've been thinking about a sort of healthcheck / debug page for folks; a check for indexes (with recommended action to fix) seems like a good candidate for the sort of thing we could add to something like that.

We could also improve the documentation to make this clearer (and even add run time checks to log an error on the console).

Am also open to considering enabling `synchronize: true` by default on MongoDB connections - as unlike an SQL database I don't think there is any scenario it would ever lead to data loss; perhaps we could mull that one over and see if that holds true.

**Comment by damieng** [comment]
`synchronize=true` has now created some indexes, thanks!

**Comment by wordemoideen** [comment]
sychronize=true will create indexes.
