### ISSUE TITLE
signIn callback returning before promise resolves

### ISSUE THREAD

**Issue by wwsalmon** [nextauthjs/next-auth#897]
**Your question**
I use the `signIn` callback to access MongoDB before letting the user through. My code looks like this:

```
signIn: async (user, account, profile) => {
    try {
        mongoose.connect(process.env.MONGODB_URL, {
            useNewUrlParser: true,
            useUnifiedTopology: true,
            useFindAndModify: false,
        });

        userModel.findOne({ email: user.email }, (err, foundItem) => {
            if (err) return Promise.reject(new Error(err));

            // if user object already exists, return
            if (foundItem) return Promise.resolve(true);

            const urlName = user.name.split(" ").join("-") + "-" + short.generate();

            // otherwise, create new user object
            userModel.create({
                email: user.email,
                name: user.name,
                image: user.image,
                urlName: urlName,
                private: false,
            }, (err, newUser) => {
                if (err) return Promise.reject(new Error(err));
                return Promise.resolve(newUser);
            });
        });
    } catch (e) {
        console.log(e);
        return Promise.reject(new Error(e));
    }
}
```

However, the callback returns true and redirects to the homepage before the promise is even returned. As a minimal reproduction:

```
signIn: async (user, account, profile) => {
     setTimeOut(() => {
		return Promise.resolve(false);
	}, 2000);
}
```

does not stop the user, but rather lets them through. Wrapping everything in a promise doesn't work either:

```
signIn: async (user, account, profile) => {
	return Promise((res, rej) => {
		setTimeOut(() => {
			res(false);
		}
	});
}
```

This request just returns a pending promise and never resolves.

How do I make the callback return, and the page redirect, only after the function has fun and the promise has resolved?

Here's my whole project repo for further context: https://github.com/wwsalmon/updately

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by balazsorban44** [comment]
Hi there! Since you are using Promises inside `userModel.findOne`, I assume it is also an async method. I think you should actually return `userModel.findOne` in your try block, or if I may suggest, you could try using async/await for better readability like so:

```js
signIn: async (user, account, profile) => {
    await mongoose.connect(process.env.MONGODB_URL, {
        useNewUrlParser: true,
        useUnifiedTopology: true,
        useFindAndModify: false,
    })
    const userExists = Boolean(await userModel.findOne({ email: user.email }).exec())
    if (!userExists) {
      const urlName = user.name.split(" ").join("-") + "-" + short.generate();
      await userModel.create({
        email: user.email,
        name: user.name,
        image: user.image,
        urlName: urlName,
        private: false,
      })
    }
    return true
}
```

Some explanation. I am not entirely sure about the `mongoose` API, so I made the assumptions from the docs [here](https://mongoosejs.com/docs/connections.html#callback) and [here](https://mongoosejs.com/docs/api/model.html#model_Model.findOne) that those operations return a promise, and you can use that instead of callbacks.
This fairly simplifies the code, as you can see. Also, you don't have to try to catch errors, in case you just want the sign-in to fail in case of an error. When `async/await` code fails, it will throw an error, just like a rejected Promise. `next-auth` handles it by not showing the user signed in. If you do wish to add some extra functionality, like redirect the user to a special URL if the sign-in process failed, you can throw a string, which should be a valid URL, like so:

```js
try {
  do some async/await work here
  return true // don't forget to return true at the end
} catch(error) {
  if(errorIWantToHandle(error)) {
    throw "/signin-error"
  }
  throw error
}
```

(@iaincollins I think the API here could be improved:
https://github.com/nextauthjs/next-auth/blob/5126f4e3428f2b4b8ebdd38b10066edfdd4ea2fa/src/server/routes/signin.js#L62
returning a string would probably enough, instead of throwing.)


I advocate for using async/await over Promises and callbacks because you will quickly end up with a lot of nested calls, which makes it much harder to read the code and accidentally forget to add a missing return.

**Comment by wwsalmon** [comment]
@balazsorban44 changing everything to async/await instead of callbacks and returning booleans instead of promises fixed my problem, thanks so much!

re: documentation, I'm a fairly new frontend dev who hasn't worked all that much with async/await and promise patterns before, so maybe a more experienced backend dev wouldn't have run into this problem. For me, though, seeing `return true` in the documentation definitely would have been clearer!
