### ISSUE TITLE
Either prod or dev not working

### ISSUE THREAD

**Issue by fsa317** [nextauthjs/next-auth#8985]
### Environment

System:
OS: macOS 13.3
CPU: (8) arm64 Apple M2
Memory: 62.55 MB / 8.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.3.1 - /opt/homebrew/bin/node
npm: 9.6.7 - /opt/homebrew/bin/npm
pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
Browsers:
Chrome: 118.0.5993.117
Safari: 16.4

### Reproduction URL

https://github.com/apsquared/ap2

### Describe the issue

I seem to have one of two issues. I am using next auth with Vercel. If I deploy version 4.x my local vercel dev does not work for what is this issue: https://github.com/nextauthjs/next-auth/pull/7214 . If I use the experimental build referenced in that link than my production deployment doesn't work as it tries to redirect to localhost (even though I can see NEXTAUTH_URL set to my domain). I can't seem to get both to work.

### How to reproduce

When using the experimental build from https://github.com/nextauthjs/next-auth/pull/7214 attempting to login redirects to localhost. The redirect callback below prints localhost:3000

```
      async redirect({ url, baseUrl }) {
        console.log(`URL: ${url}`)
        console.log(`BASEURL: ${baseUrl}`)
        return baseUrl
      },
```
If not using the experiment build the issue described in that issue occurs.

### Expected behavior

Both dev and prod should work.

**Comment by ashokasec** [comment]
![image](https://github.com/nextauthjs/next-auth/assets/108524973/985f9ffc-e96f-48da-8146-00fb086d67ba)

may be changing the **Authorization Callback URL** resolve the issue

**Comment by balazsorban44** [comment]
We could not detect a valid reproduction link. **Make sure to follow the bug report template carefully.**

### Why was this issue closed?

To be able to investigate, we need access to a reproduction to identify what triggered the issue. We need a link to a **public** GitHub repository. Example: ([NextAuth.js example repository](https://github.com/nextauthjs/next-auth-example)).

The bug template that you filled out has a section called "Reproduction URL", which is where you should provide the link to the reproduction.

- If you did not provide a link or the link you provided is not valid, we will close the issue.
- If you provide a link to a private repository, we will close the issue.
- If you provide a link to a repository but not in the correct section, we will close the issue.

### What should I do?

Depending on the reason the issue was closed, you can do the following:

- If you did not provide a link, please open a new issue with a link to a reproduction.
- If you provided a link to a private repository, please open a new issue with a link to a public repository.
- If you provided a link to a repository but not in the correct section, please open a new issue with a link to a reproduction in the correct section.

**In general, assume that we should not go through a lengthy onboarding process at your company code only to be able to verify an issue.**

### My repository is private and cannot make it public

In most cases, a private repo will not be a sufficient **minimal reproduction**, as this codebase might contain a lot of unrelated parts that would make our investigation take longer. Please do **not** make it public. Instead, create a new repository using the templates above, adding the relevant code to reproduce the issue. Common things to look out for:

- Remove any code that is not related to the issue. (pages, API Routes, components, etc.)
- Remove any dependencies that are not related to the issue.
- Remove any third-party service that would require us to sign up for an account to reproduce the issue.
- Remove any environment variables that are not related to the issue.
- Remove private packages that we do not have access to.
- If the issue is not related to a monorepo specifically, try to reproduce the issue without a complex monorepo setup

### I did not open this issue, but it is relevant to me, what can I do to help?

Anyone experiencing the same issue is welcome to provide a minimal reproduction following the above steps by opening a new issue.

### I think my reproduction is good enough, why aren't you looking into it quickly?

We look into every issue and monitor open issues for new comments.

However, sometimes we might miss a few due to the popularity/high traffic of the repository. We apologize, and kindly ask you to refrain from tagging core maintainers, as that will usually not result in increased priority.

Upvoting issues to show your interest will help us prioritize and address them as quickly as possible. That said, every issue is important to us, and if an issue gets closed by accident, we encourage you to open a new one linking to the old issue and we will look into it.

### Useful Resources

- [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
- [Bug report: Framework](https://github.com/nextauthjs/next-auth/issues/new?assignees=&labels=triage&projects=&template=1_bug_framework.yml)
- [Bug report: Provider](https://github.com/nextauthjs/next-auth/issues/new?assignees=&labels=triage%2Cproviders&projects=&template=2_bug_provider.yml)
- [Bug report: Adapter](https://github.com/nextauthjs/next-auth/issues/new?assignees=&labels=triage%2Cadapters&projects=&template=3_bug_adapter.yml)
