### ISSUE TITLE
NextAuth Example App on Vercel giving me a 404 when I click "Sign in"

### ISSUE THREAD

**Issue by andrewschaeffer** [nextauthjs/next-auth#9299]
### What is the improvement or update you wish to see?

I'd like to be able to interact with the Vercel example app, but it is giving me a 404 page every time I click "Sign in."

### Is there any context that might help us understand?

I navigate here: https://next-auth-example.vercel.app/ and when I click sign in I'm greeted with a 404 page.

Not sure why this is happening.  I've used the example app before without any problems - I signed in (I believe it was with Github provider) and now I can't sign in again.

Any help appreciated.  Thanks.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/getting-started/example

**Comment by simon-v-swyftx** [comment]
Looks related to https://github.com/nextauthjs/next-auth/issues/9050

**Comment by sandercoffee** [comment]
Urls with Error:
Sign In https://next-auth-example.vercel.app/signin?callbackUrl=https%3A%2F%2Fnext-auth-example.vercel.app%2F
Server Side > Midleware Example https://next-auth-example.vercel.app/%7D/signin?callbackUrl=https%3A%2F%2Fnext-auth-example.vercel.app%2F%257D%2Fsignin

**Comment by typle** [comment]
session:{strategy : "jwt"}

**Comment by balazsorban44** [comment]
Should be fixed via https://github.com/nextauthjs/next-auth/commit/0f2c979020631023b894baec4a77cec301037f1c

The issue was a failing build. The final solution will probably be using https://react.dev/reference/react/experimental_taintObjectReference to taint the server-session and force the user to create a client-safe version that can be passed to `SessionProvider`. This means we likely need to introduce a new `ClientSession` interface too. I will think about it.
