### ISSUE TITLE
Extend the documentation for the Credentials provider instead of limiting it.

### ISSUE THREAD

**Issue by XiovV** [nextauthjs/next-auth#9314]
### What is the improvement or update you wish to see?

I understand and appreciate the promotion of passwordless logins and oauth, however, considering that this is documentation, I don't think it makes sense to purposely limit it. 

Some people either have to use their own authentication system or want to use it, for various reasons. For example, I'm working on a personal project where I want to use my own authentication system (that is, manage usernames and passwords myself). I then come to the documentation to figure out how to use the Credentials provider, only to see that it is limited on purpose, rendering the point of the documentation almost useless. 

Because the documentation is limited, I now have to do a lot more extra research and troubleshooting, when it all could've been written and explained in the docs. What is the point of having documentation that doesn't explain how to use something on purpose? I know that the rest of the details are explained in other parts of the docs, but that still ties to the point I made about having to do a lot more research. I hope you see what I mean. 

Admittedly, I am new to frontend development and have started using Next.js 14 and NextAuth very recently.

My proposed solution is to leave the warning that it's usually not the best idea to do your own authentication, but proceed to explain how to use the Credentials provider anyway. That way people are warned about the dangers of doing their own authentication and can extract the most amount of value from the documentation at the same time.

When I learn how to use the Credentials provider in more detail, I have no issue with extending the docs myself and submitting a PR.

### Is there any context that might help us understand?

I almost got my own authentication working, but where I failed is here: https://next-auth.js.org/getting-started/typescript#module-augmentation

I had to augment the Sessions interface because the User my backend returned is different from the default one, but the `declare module "next-core"` line would give me an error. After trying some solutions I found in GitHub issues, I still couldn't augment the interface. Even if I got no errors, the getSession() function would always return the default user.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/providers/credentials

**Comment by xVinniVx** [comment]
yeah... Auth.js docs are in bad shape. Nothing is exaplained. Examples are with errors.... 
Very bad experience.

**Comment by balazsorban44** [comment]
> only to see that it is limited on purpose

This is incorrect, you can fully implement any flow you wish, the `authorize()` callback gives you all the flexibility you need. If we wanted to limit this flow, the provider would not exist in the first place.

> I now have to do a lot more extra research and troubleshooting

This is the precise intention. Implementing this login flow from scratch **should** require much more consideration, understanding the consequences and the drawbacks of this approach, and should not be done lightly.

> What is the point of having documentation that doesn't explain how to use something on purpose

The point is to explain that this flow is fully supported (and [always will be](https://twitter.com/nextauthjs/status/1718745904012837260)) but it needs further consideration on the developer's part.

> Admittedly, I am new to frontend development and have started using Next.js 14 and NextAuth very recently.

The exact use case where we would like to discourage this approach in favor of an established/battle-tested provider instead.

> but proceed to explain how to use the Credentials provider anyway

There is no single way to explain this. The credentials provider is the most powerful of all of them, since it can literally be used with any existing auth system. We could simply not cover all cases. In addition, you can see how if we would explain for example the starting steps of the most common email+password flow in more details, how everyone would just ignore the warning, leaving their systems potentially vulnerable. As an auth library, our first priority is security, and thus will only promote ways of authentication that we recommend for production/wider user-groups. You are however welcome to do the research and implement the flow that your app requires. This provider is _never_ going to go away.

> I almost got my own authentication working, but where I failed is here

Certainly something we can help with, if you open a bug report with a minimal reproduction!

> Auth.js docs are in bad shape

Thanks for the feedback @xVinniVx, I'm aware and am constantly working on it, when my time allows it! Since this is a public, open-source project, PRs/help are always welcome! If there is a certain area that is unclear, please open an issue explaining what you are missing. If you need further assistance, you can consider sponsoring the project. Thanks for understanding! :green_heart:


---

FYI, as the documentation is being migrated to a new domain, you can read a slightly better explanation on the decisions made here: https://authjs.dev/guides/providers/credentials#example---username--password, hope it helps.

We would like to invest more into more modern alternatives like Passkeys/WebAuthn, that has the potential to eliminate passwords for all users on supported devices. Even then, the Credentials provider will stay supported, but no further development is planned.

As though these decisions might not sound what you would like to hear, the same opinion is shared by other similar libraries. I'll mention one specifically which Auth.js has been compared against lately:

See the discussion from this [popular alternative](https://github.com/lucia-auth/lucia/discussions/1231#:~:text=a%20single%20table.-,Passwords,-Next%2C%20password%20based)

> But I do want to discourage people from implementing it if they're not willing to put the care required to pull it off. Because here's the thing: email/password auth is tedious. It's not hard, but there's a lot of steps required to implement it correctly. And you're not making your password based auth any more secure by using Lucia's keys. Besides, if you're willing to take time to implement email verification, password reset tokens, and login throttling, keys aren't really making your work significantly easier.

The leading sentence 

> Unlike Auth.js, I don't want to make it harder to implement it.

is pretty misleading in my opinion, as the author goes into details right after, arriving to the same conclusion as what I just explained. Nothing about our implementation makes this flow hard to implement, we just discourage it. It literally takes a few lines, but then much more to make it a robust solution that would meet our standards, hence it is left up to the developer who is expected to have the required expertise.

But they are fully entitled to their opinion about Auth.js regardless, and I have nothing but admiration about their work and effort put into writing up the leading thoughts.

**Comment by ArmantG** [comment]
Irritated by most of the comments downplaying how pad the credentials documentation is and saying it requires more consideration from the developer. 

For my app, I can ONLY use credentials. My clients, most from a rural or slightly technological disadvantaged background dont understand all these other auth providers and how to log in using them. Email and password works best, but still a struggle to implement properly following the docs. 

Would agree there still needs to be an example app and proper explanation and pros and cons of using it if its offered. 

But that's what youtube is for, to have someone else explain the documentation to you, show you the work arounds and give you the actual information you need to get going.

**Comment by XiovV** [comment]
I agree with what you said. The developer's decision/mindset to push OAuth makes sense and it's great, however, some people just have to use password/email, like you and me for example (and I bet there are thousands of other developers out there with the exact same need). Limiting the documentation on purpose doesn't benefit anyone. 

If you're going to offer something, then I think it would make sense to document it properly. A note at the beginning of docs can be put in place which will warn the user that using email/password authentication can be insecure, and that they should consider OAuth, then proceed to properly document the rest of the functionality.

**Comment by XiovV** [comment]
@balazsorban44 

> > only to see that it is limited on purpose
> 
> This is incorrect, you can fully implement any flow you wish, the `authorize()` callback gives you all the flexibility you need. If we wanted to limit this flow, the provider would not exist in the first place.

I should've explained that better, sorry. What I meant is that the documentation is limited on purpose, not the Credentials provider itself. I was referring to this note left on the documentation:

> The functionality provided for credentials based authentication is intentionally limited to discourage use of passwords due to the inherent security risks associated with them and the additional complexity associated with supporting usernames and passwords.
---
> > I now have to do a lot more extra research and troubleshooting
> 
> This is the precise intention. Implementing this login flow from scratch **should** require much more consideration, understanding the consequences and the drawbacks of this approach, and should not be done lightly.

I understand your point, however, when someone goes to read documentation, they're expecting pretty much all of their answers to be answered there. The way the documentation for the Credentials is designed at the moment, it just ends up raising a lot more questions.  

---
> > What is the point of having documentation that doesn't explain how to use something on purpose
> 
> The point is to explain that this flow is fully supported (and [always will be](https://twitter.com/nextauthjs/status/1718745904012837260)) but it needs further consideration on the developer's part.

This ties to my point I made above. Yes, the developer should consider what the best way to approach authentication for their project is. But, some developers understand all the implications that come with using email/password authentication, and all they want to do is figure out how to implement it properly using a specific library. At the moment, like I mentioned earlier, the user leaves the documentation with more questions than answers. Despite your best intentions, this is the exact opposite of what documentation is supposed to do. 

Again, I understand the intention behind pushing OAuth and moving away from emails and passwords, I'm all for that, and I'm not trying to hate. I am aware you put in a ton of work into this entire project and many people are grateful for it, including me. 

However, in my opinion, if you're going to offer something I think it would make sense to document it properly. Documentation should explain the user how to do something and to answer as many questions as possible, not to tell them how they *should* do it and leave them hanging.

I, and probably many other developers out there (judging by the thumbs up and a few comments left in this thread, imagine how many people share the same opinion/problems but didn't see this issue), would be very grateful if you would consider re-opening this issue and improving the documentation by providing a few more details and examples. Thank you :-)
