### ISSUE TITLE
CLIENT_FETCH_ERROR during build /api/auth/providers

### ISSUE THREAD

**Issue by FallenDeity** [nextauthjs/next-auth#9597]
### Environment

  System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 3.85 GB / 15.79 GB
  Binaries:
    Node: 20.5.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (15.4.0), Chromium (15.4.0), ChromiumDev (15.4.0)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    next: ^13.4.4 => 13.5.6
    next-auth: ^4.22.3 => 4.24.5
    react: ^18.2.0 => 18.2.0

### Reproduction URL

https://github.com/FallenDeity/react-next-tailwind-template/tree/nextauth

### Describe the issue

```
   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types ...
   Collecting page data ...
   Generating static pages (0/5) ...
   Generating static pages (1/5) 
   Generating static pages (2/5)
   Generating static pages (3/5) 
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11576:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://localhost:3000/api/auth/providers',
  message: 'fetch failed'
}
 ✓ Generating static pages (5/5)
   Finalizing page optimization ...
   Collecting build traces ...
```
Error when building the project using `npm run build` don't see any visible effects when running using `npm run start` or `npm run dev` everything seems to work as intended.

I tried different versions of node `18.14.1` and `16.20.0` no difference
Tried a few different next and next-auth versions too

### How to reproduce

Run the following commands to setup the repo
```
git clone https://github.com/FallenDeity/react-next-tailwind-template
git checkout nextauth
cd react-next-tailwind-template
npm install
npm run build
```

Make sure you have the following setup in a `.env` file

```
GITHUB_ID=
GITHUB_SECRET=
NEXTAUTH_URL=
NEXTAUTH_SECRET=
```

You can test by running `npm run dev` any linting or formatting issues can be fixed using `npm run prettier:fix` and `npm run lint:fix`

### Expected behavior

Ideally this error shouldn't be occurring at all

**Comment by nahtnam** [comment]
I'm noticing similar behavior, and when I call `signIn('id')` it does not auto-redirect them to the oauth provider. Instead it shows the next-auth page

**Comment by Yunfei1982** [comment]
i have same error

**Comment by balazsorban44** [comment]
This is due to the fact that `getProviders` do a fetch call to the endpoint in the shown error. during build, the server is not up, so  the request will fail. in the new version of next-auth, `getProviders` will actually be marked with `"use client"`.

You can create a client component in your code base for now, and call getProviders there in some way. or you can directly iterate over your `authOptions.providers` object. since you are in a server component, it's safe to do so.

**Comment by FallenDeity** [comment]
I see thank you

**Comment by prem911** [comment]
I all of a sudden started getting this error today. I had node 18, nextjs 14. 
I upgraded to node20 as per some blogs. Didnot help.
Deleted the node_modules and .next folder. That also didnot help.
Changed the server call of getProviders to authOptions.getProviders and it gave some different problems.

When I reverted the changes, the error is gone! Not sure whats the issue is? 
If its going to be magical, will my production build on vercel fail without explanation anytime?

**Comment by GideonKoenig** [comment]
I had a similar issue, not sure though, if it was caused by the node updated (it's possible, I just can't confirm it).

For me, I was able to use the `authOptions` like this to obtain the provider information. The only reason why I map the providers like this, is because I pass them to a client component and the full objects contain functions, which can't be passed as props.

```typescript
import { authOptions } from "~/server/auth";

const provider = authOptions.providers
    .map((provider) => ({
        name: provider.name,
        id: provider.id,
    }))
```

More specifically, in my SignIn Page I use this snippet.
```typescript
import { OAuthProviderButton } from "./_components/provider-button";
import { authOptions } from "~/server/auth";

export default async function AuthSignIn() {
    const providers = authOptions.providers;
    const ProviderButtonList = providers
        .filter((provider) => provider.type === "oauth")
        .map((provider) => ({
            name: provider.name,
            id: provider.id,
        }))
        .map((provider, index) => (
            <OAuthProviderButton key={index} provider={provider} />
        ));
...
}
```
