### ISSUE TITLE
PrismaClientValidationError on OAuth User Creation with Different Providers in Next-Auth Using T3 Stack

### ISSUE THREAD

**Issue by TheHikuro** [nextauthjs/next-auth#9605]
### Provider type

GitLab

### Environment

```
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 82.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.volta/tools/image/node/18.17.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.6.7 - ~/.volta/tools/image/node/18.17.1/bin/npm
    bun: 1.0.21 - ~/.bun/bin/bun
    Watchman: 2023.09.25.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.199
    Edge: 120.0.2210.121
    Safari: 17.2.1
  npmPackages:
    next: ^14.0.4 => 14.0.4
    next-auth: ^4.24.5 => 4.24.5
    react: 18.2.0 => 18.2.0
```

### Reproduction URL

https://github.com/t3-oss/create-t3-app

### Describe the issue

I am encountering a PrismaClientValidationError when creating user accounts through OAuth with next-auth in a T3 stack application. This issue specifically arises when using GitLab as a provider, where the created_at field is receiving an integer (Unix timestamp), leading to a format mismatch. Notably, when using Google as a provider, the created_at field correctly receives a DateTime format, and there are no issues.

```
PrismaClientValidationError: Invalid `prisma.account.create()` invocation:
{
  data: {
    // ... other data ...
    created_at: 1704884425, // Expected DateTime or Null, received Int
    // ... other data ...
  }
}
```

### How to reproduce

1. Implement user authentication in a T3 stack application using next-auth and Prisma.
2. Configure OAuth with GitLab and Google as providers.
3. Attempt to sign in with a GitLab account, triggering the user creation process.
4. Observe the error during the account creation step.
5. Note that this error does not occur when signing in with a Google account.

### Expected behavior

The created_at field should accept the timestamp provided by the OAuth process, regardless of the provider, and successfully create a new user record in the database.

**Comment by balazsorban44** [comment]
We could not detect a valid reproduction link. **Make sure to follow the bug report template carefully.**

### Why was this issue closed?

To be able to investigate, we need access to a reproduction to identify what triggered the issue. We need a link to a **public** GitHub repository. Example: ([NextAuth.js example repository](https://github.com/nextauthjs/next-auth-example)).

The bug template that you filled out has a section called "Reproduction URL", which is where you should provide the link to the reproduction.

- If you did not provide a link or the link you provided is not valid, we will close the issue.
- If you provide a link to a private repository, we will close the issue.
- If you provide a link to a repository but not in the correct section, we will close the issue.

### What should I do?

Depending on the reason the issue was closed, you can do the following:

- If you did not provide a link, please open a new issue with a link to a reproduction.
- If you provided a link to a private repository, please open a new issue with a link to a public repository.
- If you provided a link to a repository but not in the correct section, please open a new issue with a link to a reproduction in the correct section.

**In general, assume that we should not go through a lengthy onboarding process at your company code only to be able to verify an issue.**

### My repository is private and cannot make it public

In most cases, a private repo will not be a sufficient **minimal reproduction**, as this codebase might contain a lot of unrelated parts that would make our investigation take longer. Please do **not** make it public. Instead, create a new repository using the templates above, adding the relevant code to reproduce the issue. Common things to look out for:

- Remove any code that is not related to the issue. (pages, API Routes, components, etc.)
- Remove any dependencies that are not related to the issue.
- Remove any third-party service that would require us to sign up for an account to reproduce the issue.
- Remove any environment variables that are not related to the issue.
- Remove private packages that we do not have access to.
- If the issue is not related to a monorepo specifically, try to reproduce the issue without a complex monorepo setup

### I did not open this issue, but it is relevant to me, what can I do to help?

Anyone experiencing the same issue is welcome to provide a minimal reproduction following the above steps by opening a new issue.

### I think my reproduction is good enough, why aren't you looking into it quickly?

We look into every issue and monitor open issues for new comments.

However, sometimes we might miss a few due to the popularity/high traffic of the repository. We apologize, and kindly ask you to refrain from tagging core maintainers, as that will usually not result in increased priority.

Upvoting issues to show your interest will help us prioritize and address them as quickly as possible. That said, every issue is important to us, and if an issue gets closed by accident, we encourage you to open a new one linking to the old issue and we will look into it.

### Useful Resources

- [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
- [Bug report: Framework](https://github.com/nextauthjs/next-auth/issues/new?assignees=&labels=triage&projects=&template=1_bug_framework.yml)
- [Bug report: Provider](https://github.com/nextauthjs/next-auth/issues/new?assignees=&labels=triage%2Cproviders&projects=&template=2_bug_provider.yml)
- [Bug report: Adapter](https://github.com/nextauthjs/next-auth/issues/new?assignees=&labels=triage%2Cadapters&projects=&template=3_bug_adapter.yml)
