### ISSUE TITLE
Handle online state and force update session accordingly

### ISSUE THREAD

**Issue by Robbilie** [nextauthjs/next-auth#987]
**Summary of proposed feature**
Currently when the navigator.onLine state changes to offline the session object gets emptied because the session network calls fail. This per se is not an issue, it would be nice though if the session object would get updated automatically once network becomes available again.
Sidenote: When changing the network state in the network tab of chrome, setting it to online, the first interactoin with the website causes the session to get updated. It would be nice, maybe in addition to the aforementioned feature request, that a manual getSession call would update the useSession state too?

**Purpose of proposed feature**
Handling offline state of a PWA properly and possibly being able to manually force session updates on the client side.

**Detail about proposed feature**
For the online state changes there are hooks available:
https://github.com/rehooks/online-status
About the manual force refresh, i would have to take a deeper look at the nextauth source :)

**Potential problems**
Not seeing any right now…

**Describe any alternatives you've considered**
I wasnt able to trigger the session update in any way…

**Additional context**
~

*Please indicate if you are willing and able to help implement the propos ed feature.*
If someone would give me a hint at where to put the code (and the force update) i would be happy to add this, seems like a tiny change…

**Comment by Robbilie** [comment]
i guess you can do this:
```
window.dispatchEvent(new Event("focus"));
```

**Comment by fedeant** [comment]
I have the same need for offline support for the following use case:

In a regular web app (not PWA) the user opens one or more private pages (require valid session) which show some large contents, like documentation, and the user leaves the pages open to continue reading them later.
Later when the user goes back to the web browser to continue reading, it might be offline (no wifi, subway, airplane, etc.).

Expected: The webpage with the private content remains shown.
Obtained: Private content is not shown because NextAuth tried to check the session, it failed and set session=null.

For now I solved it modifying the NextAuth source code in this way but I don't know if it's a safe solution and won't have undesirable side effects:

**In this file:**
Npm module: `/node_modules/next-auth/dist/client/index.js`
(Source: https://github.com/nextauthjs/next-auth/blob/canary/src/client/index.js)

**Changed from line 367:**
```JavaScript
      return Promise.resolve(null);
```

**To:**
```JavaScript
      return Promise.resolve('CLIENT_FETCH_ERROR');
```

**And changed from line 253:**
```JavaScript
       __NEXTAUTH._clientSession = newClientSessionData;
        setData(newClientSessionData);
```

**To:**
```JavaScript
        if (newClientSessionData != 'CLIENT_FETCH_ERROR') {
          __NEXTAUTH._clientSession = newClientSessionData;
          setData(newClientSessionData);
        } else {
          setData(__NEXTAUTH._clientSession);
        }
```

Note: Needs restarting the dev server for changes to take effect.

**Comment by mjewell** [comment]
I am currently using next-auth for a react native app and experiencing the same issue. I have an authenticated page where you track your location, but because people may track their location in remote areas it needs to keep you logged in if you lose signal for some part of the session. Not sure what the best solution is, but the two I can think of are

- useSession can continue to return the last session if the request fails due to network inactivity (like https://github.com/nextauthjs/next-auth/issues/987#issuecomment-766423959 suggests)
- useSession can return a third variable representing the error. e.g. `const [session, loading, error] = useSession();`. Then you could store your own reference to the session and choose to not discard it if the error is based on network inactivity.

Also happy to hear any other suggestions you have for ways to solve this. I can make a PR for it if we can agree on the right approach.
