### ISSUE TITLE
Update apple sign in to show PKCE steps?

### ISSUE THREAD

**Issue by Tigatok** [nextauthjs/next-auth#9893]
### What is the improvement or update you wish to see?

From what I was reading, it does not seem possible to do the apple sign in flow without sending cookies. I get this error: PKCE code_verifier cookie was missing.

Most other threads call out that adding the following cookies solves that:
```
    cookies: {
      pkceCodeVerifier: {
        name: 'next-auth.pkce.code_verifier',
        options: {
          httpOnly: true,
          sameSite: 'none',
          path: '/',
          secure: true,
        },
      },
    },
```

but this is not mentioned anywhere in the docs. If it is not required, I'd like to know how to get around this. If it is required, we should add it to the documentation?

### Is there any context that might help us understand?

Errors when using the Apple Sign in flow that are not apparent.

### Does the docs page already exist? Please link to it.

https://next-auth.js.org/providers/apple#testing-on-a-development-server

**Comment by HitOP2509** [comment]
Hey @Tigatok , Just curious to know if Apple sign in is working for you?

**Comment by Tigatok** [comment]
@HitOP2509 Hi Rohit, yes, I do have Apple Sign in working.

**Comment by HitOP2509** [comment]
Could you please share the working code as I'm stuck from the last 2 days. After signing in, I'm getting redireacted to callbackError page. Vercel logs showing that the [auth] [cause] is authorization server did not provide a userinfo enpoint.

**Comment by trevorpfiz** [comment]
when I add that I get the error `[auth][error] InvalidCheck: PKCE code_verifier cookie was missing. .Read more at https://errors.authjs.dev#invalidcheck`

**Comment by marlon307** [comment]
I have the same problem but to authenticate on my subdomains.

**Comment by Tigatok** [comment]
@HitOP2509 did you figure your problem out?

**Comment by HitOP2509** [comment]
@Tigatok  Not yet. It seems there's a problem with how Apple sends data and how Auth JS handles it. Auth JS expects a userinfo endpoint, but there's no userinfo endpoint in the Apple OpenID config file [https://appleid.apple.com/.well-known/openid-configuration](url).

**Comment by tahakucukkatirci** [comment]
@HitOP2509 did you figure out a way to solve this problem? I am getting the exact same error.

**Comment by joeblau** [comment]
Also running into the same issue. I can have Sign in with Apple or sign in with everything else (Google/Discord/Twitter)

**Comment by luanvpereira** [comment]
@joeblau  I think I was facing the same issue using next-auth **v4.24.7**. I couldn't use Apple Provider and Google Provider at the same time.
When you set up the **pkceCodeVerifier** as `sameSite: "none"`, the Google Provider will use this cookie with the same configuration, but Google Provider needs it to be `"Lax"` instead. So, we have two options here:

- On Google Provider, configure "checks" property with ["state"] instead of ["pkce", "state"] (maybe you will have the same issue with "next-auth.callback-url" cookie)
- Or create a wrapper for the POST in Api routes to change the response of the NextAuth() according to the provider. You can change the cookies to **Lax** or **None** using the URL requested. 

I chose the second one, and did that:

```
// [...nextauth]/route.ts

const handler = NextAuth(authOptions);

async function POSTWrapper(request: NextRequest, response: NextResponse) {
  const authResponse = (await handler(request, response)) as Response;

  return transformCookiesByProvider(request, authResponse);
}

export { handler as GET, POSTWrapper as POST };
```

```
const CALLBACK_URL_COOKIE = "next-auth.callback-url";
const PKCE_CODE_VERIFIER = "next-auth.pkce.code_verifier";

const EXPIRES_IN_FIFTEEN_MINUTES = new Date(
  new Date().getTime() + 15 * 60 * 1000
).toUTCString();

export function transformCookiesByProvider(
  request: NextRequest,
  response: Response
) {
  /**
   * Change the cookies' SameSite property to "Lax" because it is required for Google authentication
   */
  if (!request.url.endsWith("/auth/signin/google")) {
    return response;
  }

  const cookiesAsString = response.headers.getSetCookie().join(";");

  const callbackUrlValue = getCookie(CALLBACK_URL_COOKIE, cookiesAsString);
  const pkceCodeVerifierValue = getCookie(PKCE_CODE_VERIFIER, cookiesAsString);

  const responseCookies = response.headers.getSetCookie().filter((cookie) => {
    return (
      cookie.indexOf(CALLBACK_URL_COOKIE) === -1 &&
      cookie.indexOf(PKCE_CODE_VERIFIER) === -1
    );
  });

  if (callbackUrlValue) {
    responseCookies.push(
      `${CALLBACK_URL_COOKIE}=${callbackUrlValue}; sameSite=Lax; path=/; ${
        isSecure ? `secure=true` : ""
      }`
    );
  }

  if (pkceCodeVerifierValue) {
    responseCookies.push(
      `${PKCE_CODE_VERIFIER}=${pkceCodeVerifierValue}; httpOnly=true; sameSite=Lax; path=/; ${
        isSecure ? `secure=true` : ""
      }; expires=${EXPIRES_IN_FIFTEEN_MINUTES}`
    );
  }

  response.headers.delete("Set-Cookie");

  responseCookies.forEach((currentCookie) => {
    response.headers.append("Set-Cookie", currentCookie);
  });

  return response;
}


// external function
function getCookie(name: string, cookieAsText: string = '') {
  const cookieValue = typeof window === 'undefined' ? cookieAsText : document.cookie
  const cookieCollection = decodeURIComponent(cookieValue).split(';')

  const cookie = cookieCollection.reduce((cookieAcc: CookieMap, currentCookieText) => {
    const [key, value] = currentCookieText.split('=')

    cookieAcc[key.trim()] = value

    return cookieAcc
  }, {})

  return cookie[name]
}

```

I am going to revise this logic because the error seems to originate from the Apple Provider.

If you play the video below and pause at the right time, after clicking the  Google button, you will see that the **pkceCodeVerifier** cookie gets yellow with "None" message on the "Same Site" column. 

https://github.com/user-attachments/assets/e8c307f1-6833-43e3-9796-ac16b9a8d546

**Comment by balazsorban44** [comment]
Hi all, since https://github.com/nextauthjs/next-auth/pull/11239 is out, this should be fixed in later releases. The default was `"pkce"`, hence the issue you were seeing.

Unfortunately, Apple's provider is simply horrible to work with, I haven't had the luck of setting up a local dev environment...
